--[[--------------------------------------------------
003_Horde_40to50.lua
Authors: mrmr
Version: 1.04.2
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 40 to Lvl 50
    1.04.1
        -- First Release
            Horde's Guide
            from level 40 to lever 50
    1.04.2
    	-- no changes in here for this revision
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Horde_40to50 = {
-----------40-41 Badlands
	--[401] = {
	[4041] = {
		title = "40-41 Badlands",
		--n = "40-41 Badlands",
		--pID = 311, nID = 402,
		--itemCount = 29,
		items = {
			[1] = { str = "40-41 Badlands" },
			[2] = { str = "The goal here is not to leave till your level 41, so grind mobs every where you go to...As you enter Badlands, run southwest to #COORDS[42,52]#...", x = 42, y = 52, zone = "Badlands" },
			[3] = { str = "Turn in #TURNIN\"Martek the Exiled\"# at #COORDS[42,52]# ... accept #ACCEPT\"Indurium\"# and #ACCEPT\"Barbecued Buzzard Wings\"# ", x = 42, y = 52, zone = "Badlands" },
			[4] = { str = "Go down south a little and do #DOQUEST\"Indurium\"# #COORDS[51,67]#", x = 51, y = 67, zone = "Badlands" },
			[5] = { str = "Go back up and turn #TURNIN\"Indurium\"# in ... accept #ACCEPT\"News for Fizzle\"# " },
			[6] = { str = "Then go north-west and accept #ACCEPT\"Study of the Elements: Rock\"# at #COORDS[25,44]#.  #VIDEONOTE:# If you have the #NPCFrost Oil#, the #NPCGyrochronatom#, the #NPCHealing Potion#, the #NPCLesser Invisibility Potion# and the #NPCPatterned Bronze Bracers# items, accept and complete all the quests there.", x = 25, y = 44, zone = "Badlands" },
			[7] = { str = "Grind your way west to Kargath #COORDS[4,46]#...", x = 4, y = 46, zone = "Badlands" },
			[8] = { str = "Get FP at Kargath." },
			[9] = { str = "Do NOT make Kargath your home. (it should still be BB)" },
			[10] = { str = "Accept: #ACCEPT\"Coyote Thieves\"# #ACCEPT\"Report to Helgrum\"# #ACCEPT\"Broken Alliances\"# and #ACCEPT\"Badlands Reagent Run\"# " },
			[11] = { str = "Then go do:" },
			[12] = { str = "#DOQUEST\"Barbecued Buzzard Wings\"# " },
			[13] = { str = "#DOQUEST\"Coyote Thieves\"# " },
			[14] = { str = "#DOQUEST\"Broken Alliances\"# (skip the next part to this quest)" },
			[15] = { str = "#DOQUEST\"Badlands Reagent Run\"# " },
			[16] = { str = "#DOQUEST\"Study of the Elements: Rock\"# (#NPClesser rock elementals#), turn in, then do..." },
			[17] = { str = "#DOQUEST\"Study of the Elements: Rock\"# (#NPCrock elementals#), turn in, then do..." },
			[18] = { str = "#DOQUEST\"Study of the Elements: Rock\"# (#NPCgreater rock elementals#)" },
			[19] = { str = "Then make sure all Badlands quests (besides #ACCEPT\"Report to Helgrum\"# ) are done and turned in." },
			[20] = { str = "You should be about level 41 right now, if not grind to it." },
			[21] = { str = "Hearth to BB and check if you have #DOQUEST\"Dream Dust in the Swamp\"# in your questlog. If not, go accept it from Krazek at #COORDS[27,77]#", x = 27, y = 77, zone = "Stranglethorn Vale" },
			[22] = { str = "Fly to Grom'gol." },
			[23] = { str = "Go turn in all the #NPCThe Green Hills of Stranglethorn Chapters/Quests# at Nesingwary's Expedition #COORDS[35,10]# if you have all the pages for it, if not you have another chance to turn this in again later.  You can also look in the AH for your missing pages.", x = 35, y = 10, zone = "Badlands" },
			[24] = { str = "Then run all the way to Swamp of Sorrows, stopping along the way to accept this quest: #ACCEPT\"Nothing But the Truth\"# (in Duskwood at #COORDS[87,35]#)", x = 87, y = 35, zone = "Duskwood" },
			[25] = { str = "Then turn in #TURNIN\"Nothing But the Truth\"# (the guy right next to him)" },
			[26] = { str = "#ACCEPT\"Nothing But the Truth\"# again" },
			[27] = { str = "Then run into Swamp of Sorrows..." },
			--[28] = { str = "." },
			--[29] = { str = "." },
		}
	},

-----------41-42 Swamp of Sorrows
	--[402] = {
	[4142] = {
		title = "41-42 Swamp of Sorrows",
		--n = "41-42 Swamp of Sorrows",
		--pID = 401, nID = 403,
		--itemCount = 27,
		items = {
			[1] = { str = "41-42 Swamp of Sorrows" },
			[2] = { str = "Start off doing: #DOQUEST\"Dream Dust in the Swamp\"# #COORDS[14,59]# It may take several trips to that area to complete it..", x = 14, y = 59, zone = "Swamp of Sorrows" },
			[3] = { str = "#DOQUEST\"Nothing But the Truth\"#  kill the Mire Lord for the Mire Lord Fungus at #COORDS[6,32]#", x = 6, y = 32, zone = "Swamp of Sorrows" },
			[4] = { str = "Find and kill #NPCCudgel#, he drops Noboru's Cudgel, which starts #ACCEPT\"Noboru the Cudgel\"# " },
			[5] = { str = "Go turn in #TURNIN\"Noboru the Cudgel\"# #COORDS[25,31]# ... accept #ACCEPT\"Draenethyst Crystals\"# ", x = 25, y = 31, zone = "Swamp of Sorrows" },
			[6] = { str = "Grind to Stonard #COORDS[45,54]#", x = 45, y = 54, zone = "Swamp of Sorrows" },
			[7] = { str = "Make Stonard your home." },
			[8] = { str = "Accept #ACCEPT\"Lack of Surplus\"# and #ACCEPT\"#NPCFresh Meat\"# " },
			[9] = { str = "Get FP." },
			[10] = { str = "Turn in #TURNIN\"Report to Helgrum\"# ... accept #ACCEPT\"Pool of Tears\"# (Elite)" },
			[11] = { str = "Go do the following quests:" },
			[12] = { str = "#DOQUEST\"Pool of Tears\"# (the artifacts are in the water around temple of atal'hakkar)" },
			[13] = { str = "#DOQUEST\"Lack of Surplus\"# then turn it in at #COORDS[81,80]# ... accept #ACCEPT\"Lack of Surplus\"# part2 and go do it", x = 81, y = 80, zone = "Swamp of Sorrows" },
			[14] = { str = "Go do #DOQUEST\"Fresh Meat\"# and #DOQUEST\"Nothing But the Truth\"# (#NPCShadow Panthers#' hearts) " },
			[15] = { str = "#DOQUEST\"Draenethyst Crystals\"# then turn it in at #COORDS[25,31]#", x = 25, y = 31, zone = "Swamp of Sorrows" },
			[16] = { str = "#DOQUEST\"Ongeku\"# " },
			[17] = { str = "turn in #TURNIN\"Lack of Surplus\"# part2 ... accept #ACCEPT\"Threat From the Sea\"#" },
			[18] = { str = "turn in #TURNIN\"Threat From the Sea\"# then accept #ACCEPT\"Threat From the Sea\"# again" },
			[19] = { str = "go do #DOQUEST\"Threat From the Sea\"# along with #DOQUEST\"Fresh Meat\"# " },
			[20] = { str = "turn in #TURNIN\"Threat From the Sea\"# ... accept #ACCEPT\"Continued Threat\"# " },
			[21] = { str = "go do #DOQUEST\"Continued Threat\"# then turn it in." },
			[22] = { str = "Hearth to Stonard." },
			[23] = { str = "Turn in #TURNIN\"Fresh Meat\"# and #TURNIN\"Pool of Tears\"# ... accept #ACCEPT\"The Atal'ai Exile\"# " },
			[24] = { str = "Should be about lvl 42 now, if not grind to it.  #HUNTERGet new hunter spells/abilities.#" },
			[25] = { str = "Fly to Grom'gol..." },
			--[26] = { str = "." },
			--[27] = { str = "." },
		}
	},

-----------42-43 Stranglethorn Vale
	--[403] = {
	[4243] = {
		title = "42-43 Stranglethorn Vale",
		--n = "42-43 Stranglethorn Vale",
		--pID = 402, nID = 404,
		--itemCount = 23,
		items = {
			[1] = { str = "42-43 Stranglethorn Vale" },
			[2] = { str = "accept #ACCEPT\"Mok'thardin's Enchantment\"# part4 and #ACCEPT\"Split Bone Necklace\"# " },
			[3] = { str = "fly to BB" },
			[4] = { str = "accept ALL quests in BB: #ACCEPT\"The Bloodsail Buccaneers\"# #ACCEPT\"Up to Snuff\"# #ACCEPT\"Zanzil's Secret\"# #ACCEPT\"Akiris by the Bundle\"# #ACCEPT\"Voodoo Dues\"# #ACCEPT\"Stoley's Debt\"# #ACCEPT\"Stranglethorn Fever\"# and #ACCEPT\"Keep An Eye Out\"#" },
			[5] = { str = "Turn in #TURNIN\"Dream Dust in the Swamp\"# " },
			[6] = { str = "Make BB your home." },
			[7] = { str = "Then go do in the following order:" },
			[8] = { str = "#DOQUEST\"The Bloodsail Buccaneers\"# along with #DOQUEST\"Up to Snuff\"# and #DOQUEST\"Keep An Eye Out\"# (these are done at the shore around #COORDS[31,80]#, and some more mobs can be found at #COORDS[27,70]#).  Also do #DOQUEST\"Stranglethorn Fever\"# (for #DOQUEST\"Stranglethorn Fever\"# you will need one gorilla fang, and the witch doctor is in the cave at #COORDS[34,60]#)", x = 31, y = 80, zone = "Stranglethorn Vale" },
			[9] = { str = "#DOQUEST\"Mok'thardin's Enchantment\"# part4 along with #DOQUEST\"Akiris by the Bundle\"# #COORDS[25,63]#", x = 25, y = 63, zone = "Stranglethorn Vale" },
			[10] = { str = "#DOQUEST\"Zanzil's Secret\"# along with #DOQUEST\"Voodoo Dues\"# (#COORDS[34,52]# and #COORDS[39,58]#)", x = 34, y = 52, zone = "Stranglethorn Vale" },
			[11] = { str = "#DOQUEST\"Skullsplitter Tusks\"# along with #DOQUEST\"Split Bone Necklace\"# " },
			[12] = { str = "I keep grinding away at Skullsplitter trolls until im at least 2-3 bars away from 43." },
			[13] = { str = "Hearth to BB" },
			[14] = { str = "Turn in ALL quests and make sure to accept #ACCEPT\"Tran'Rek\"# and #ACCEPT\"Rumors for Kravel\"# from Krazek and  #ACCEPT\"Whiskey Slim's Lost Grog\"# from Whiskey Slim" },
			[15] = { str = "Fly to Grom'gol " },
			[16] = { str = "turn in #TURNIN\"Mok'thardin's Enchantment\"# part4 and #TURNIN\"Split Bone Necklace\"# " },
			[17] = { str = "Accept #ACCEPT\"Grim Message\"#" },
			[18] = { str = "Get on the zeppelin to Orgrimmar" },
			[19] = { str = "Once there go to Belgrom Rockmaul at #COORDS[75,34]# and accept #ACCEPT\"A Threath in Ferelas\"#", x = 75, y = 34, zone = "Orgrimmar" },
			[20] = { str = "Fly to Thunder Bluff" },
			[21] = { str = "turn in #TURNIN\"Frostmaw\"# ... accept #ACCEPT\"Deadmire\"# (hint: i usually keep Frostmaw's mane in my bank for a long time)" },
			[22] = { str = "Fly to Desolace if you're not 4/5 bars into lvl 43 or Dustwallow Marsh if you're." },
			--[22] = { str = "." },
			--[23] = { str = "." },
		}
	},

-----------43-43 Desolace
	--[404] = {
	[4342] = {
		title = "43-43 Desolace",
		--n = "43-43 Desolace",
		--pID = 403, nID = 405,
		--itemCount = 16,
		items = {
			[1] = { str = "43-43 Desolace" },
			[2] = { str = "OPTIONAL: This whole section can be skipped if you are 4-5 blocks or more into lvl 43, it would not hurt to skip this section and go straight to Dustwallow Marsh." },
			[3] = { str = "make Shadowprey Village your home." },
			[4] = { str = "accept #ACCEPT\"Portals of the Legion\"# " },
			[5] = { str = "go turn in #TURNIN\"Ongeku\"# at #COORDS[36,79]# ... SKIP #NPC\"Khan Jehn\"# ", x = 36, y = 79, zone = "Desolace" },
			[6] = { str = "while your in Desolace, keep an eye out for an Elite Giant for the quest #NPC\"Nothing But the Truth\"#..." },
			[7] = { str = "...if you don’t find the giant and get the \"#NPCDeepstrider Tumor#\", then the quest will have to be abandoned, i don’t spend time going all over looking for a deepstrider gaint." },
			[8] = { str = "then go to Mannoroc Coven at #COORDS[50,76]# and do:", x = 50, y = 76, zone = "Desolace" },
			[9] = { str = "#DOQUEST\"Portals of the Legion\"# " },
			[10] = { str = "#DOQUEST\"The Corrupter\"# (Elite) (Slay #NPCLord Azrethoc# and #NPCJugkar Grim'rod#)" },
			[11] = { str = "turn in #TURNIN\"The Corrupter\"# (Elite) at #COORDS[53,54]#", x = 53, y = 54, zone = "Desolace" },
			[12] = { str = "then hearth to Shadowprey Village" },
			[13] = { str = "turn in #TURNIN\"Portals of the Legion\"# " },
			[14] = { str = "fly to TB, then to Dustwallow Marsh..." },
			--[15] = { str = "." },
			--[16] = { str = "." },
		}
	},

-----------43-43 Dustwallow Marsh
	--[405] = {
	[4343] = {
		title = "43-43 Dustwallow Marsh",
		--n = "43-43 Dustwallow Marsh",
		--pID = 404, nID = 406,
		--itemCount = 14,
		items = {
			[1] = { str = "43-43 Dustwallow Marsh" },
			[2] = { str = "Accept #ACCEPT\"Identifying the Brood\"# " },
			[3] = { str = "Go down to #COORDS[40,36]# and accept #DOQUEST\"Questioning Reethe\"# then do it.", x = 40, y = 36, zone = "Dustwallow Marsh" },
			[4] = { str = "Go down and do:" },
			[5] = { str = "#DOQUEST\"Deadmire\"# " },
			[6] = { str = "#DOQUEST\"Marg Speaks\"# Kill the mobs at around #COORDS[58,63]#", x = 58, y = 63, zone = "Dustwallow Marsh" },
			[7] = { str = "#DOQUEST\"Identifying the Brood\"# " },
			[8] = { str = "Then grind your way back to Brackenwall Village" },
			[9] = { str = "Turn in #TURNIN\"Questioning Reethe\"# and #TURNIN\"Identifying the Brood\"# ... accept #ACCEPT\"The Brood of Onyxia\"# " },
			[10] = { str = "Run back and forth until #DOQUEST\"The Brood of Onyxia\"# is done, but don't actually do the final quest yet (this will be done later at #NPClevel 48#, so you can abandon it for now)." },
			[11] = { str = "Turn in #TURNIN\"Marg Speaks\"# ... accept #ACCEPT\"Report to Zor\"# " },
			[12] = { str = "Fly to Tanaris..." },
			--[13] = { str = "." },
			--[14] = { str = "." },
		}
	},

-----------43-44 Tanaris
	--[406] = {
	[4344] = {
		title = "43-44 Tanaris",
		--n = "43-44 Tanaris",
		--pID = 405, nID = 407,
		--itemCount = 36,
		items = {
			[1] = { str = "43-44 Tanaris" },
			[2] = { str = "Go into Gadgetzan..." },
			[3] = { str = "Accept: #ACCEPT\"WANTED: Caliph Scorpidsting\"# and #ACCEPT\"WANTED: Andre Firebeard\"#   (Wanted Poster)" },
			[4] = { str = "Turn in #TURNIN\"Tran'Rek\"# " },
			[5] = { str = "Accept: #ACCEPT\"Gadgetzan Water Survey\"# #ACCEPT\"Wastewander Justice\"# and #ACCEPT\"Water Pouch Bounty\"# " },
			[6] = { str = "Make Gadgetzan your home." },
			[7] = { str = "Go to the Shimmering Flats (in Thousand Needles at #COORDS[78,77]#) and turn in #TURNIN\"Rumors for Kravel\"# #TURNIN\"News for Fizzle\"# and #TURNIN\"Razzeric's Tweaking\"# ... accept #ACCEPT\"Safety First\"# ", x = 53, y = 76, zone = "Tanaris" },
			[8] = { str = "Accept #ACCEPT\"Keeping Pace\"# " },
			[9] = { str = "Turn #TURNIN\"Keeping Pace\"# in at Zamek, then go pick up Rizzle's Plans at #COORDS[77,77]# ... accept #ACCEPT\"Rizzle's Schematics\"# " },
			[10] = { str = "Accept #ACCEPT\"Back to Booty Bay\"# (at Kravel Koalbeard)" },
			[11] = { str = "Go turn in #TURNIN\"Rizzle's Schematics\"# at Pozzik." },
			[12] = { str = "Hearth back to Gadgetzan." },
			[13] = { str = "Turn in #TURNIN\"Safety First\"# ... i SKIP the next part to this quest." },
			[14] = { str = "Then grind your way east to Steamwheedle Port. #COORDS[67,23]#", x = 67, y = 23, zone = "Tanaris" },
			[15] = { str = "Accept: #ACCEPT\"Pirate Hats Ahoy!\"# #ACCEPT\"Screecher Spirits\"# and #ACCEPT\"Southsea Shakedown\"# " },
			[16] = { str = "Turn in #TURNIN\"Stoley's Debt\"# ... accept #ACCEPT\"Stoley's Shipment\"# " },
			[17] = { str = "Then go complete these quests:" },
			[18] = { str = "#DOQUEST\"Wastewander Justice\"# along with #DOQUEST\"Water Pouch Bounty\"# (at #COORDS[64,29]#", x = 64, y = 29, zone = "Tanaris" },
			[19] = { str = "Then go do all of the following (steps 19 - 23) at Lost Rigger Cove #COORDS[72,47]#:", x = 72, y = 47, zone = "Tanaris" },
			[20] = { str = "#DOQUEST\"Southsea Shakedown\"# " },
			[21] = { str = "#DOQUEST\"Pirate Hats Ahoy!\"# " },
			[22] = { str = "#DOQUEST\"Stoley's Shipment\"# " },
			[23] = { str = "#DOQUEST\"Ship Schedules\"# (find this in one of the #NPCPirate's footlocker# at Lost Rigger Cove.  If the item cannot be found, just skip it)" },
			[24] = { str = "#DOQUEST\"WANTED: Andre Firebeard\"# " },
			[25] = { str = "Once they're all done, hearth to Gadgetzan." },
			[26] = { str = "Turn in #TURNIN\"Water Pouch Bounty\"# #TURNIN\"Wastewander Justice\"# ... accept #ACCEPT\"More Wastewander Justice\"# " },
			[27] = { str = "Go do #DOQUEST\"Gadgetzan Water Survey\"# (grinding mobs along the way, coords are at #COORDS[38,29]#), then go back and turn it in.", x = 38, y = 29, zone = "Tanaris" },
			[28] = { str = "Go to Steamwheedle Port." },
			[29] = { str = "Turn in ALL quests there ... accept #ACCEPT\"Deliver to MacKinley\"# " },
			[30] = { str = "Then go do: #DOQUEST\"More Wastewander Justice\"# along with #DOQUEST\"WANTED: Caliph Scorpidsting\"# #COORDS[59,37]#", x = 59, y = 37, zone = "Tanaris" },
			[31] = { str = "Then hearth to Gadgetzan.  Make sure you save (put in your bank) all the Wastewander Water Pouches you have, because you will need them for a later quest." },
			[32] = { str = "Turn in #TURNIN\"More Wastewander Justice\"# and #TURNIN\"WANTED: Caliph Scorpidsting\"# " },
			[33] = { str = "Fly to Freewind Post." },
			[34] = { str = "Run west into Feralas..." },
			--[35] = { str = "." },
			--[36] = { str = "." },
		}
	},

-----------44-46 Feralas
	--[407] = {
	[4446] = {
		title = "44-46 Feralas",
		--n = "44-46 Feralas",
		--pID = 406, nID = 408,
		--itemCount = 51,
		items = {
			[1] = { str = "44-46 Feralas" },
			[2] = { str = "Run into Camp Mojache. #COORDS[75,44]#", x = 75, y = 44, zone = "Feralas" },
			[3] = { str = "Accept ALL quests there: #ACCEPT\"A New Cloak's Sheen\"# #ACCEPT\"The Ogres of Feralas\"# #ACCEPT\"Gordunni Cobalt\"# #ACCEPT\"War on the Woodpaw\"# #ACCEPT\"The Mark of Quality\"# #ACCEPT\"A Strange Request\"# " },
			[4] = { str = "Get FP." },
			[5] = { str = "Make Camp Mojache your home." },
			[6] = { str = "Then go do in the following order:" },
			[7] = { str = "#DOQUEST\"War on the Woodpaw\"# go just north of Camp Mojache to do this. #COORDS[71,37]#", x = 71, y = 37, zone = "Feralas" },
			[8] = { str = "#DOQUEST\"The Ogres of Feralas\"# along with #DOQUEST\"Gordunni Cobalt\"# #COORDS[75,31]#", x = 75, y = 31, zone = "Feralas" },
			[9] = { str = "Make sure you click on one of the scrolls laying on the ground which starts: #ACCEPT\"The Gordunni Scroll\"# " },
			[10] = { str = "Then go do: #DOQUEST\"A New Cloak's Sheen\"# #COORDS[67,48]#", x = 67, y = 48, zone = "Feralas" },
			[11] = { str = "Go back to Camp Mojache, turn in ALL those quests, accept all new quests." },
			[12] = { str = "Go do #DOQUEST\"Alpha Strike\"# at #COORDS[72,56]# then turn it in. ... accept #ACCEPT\"Woodpaw Investigation\"# ", x = 72, y = 56, zone = "Feralas" },
			[13] = { str = "Go do #DOQUEST\"Woodpaw Investigation\"# at #COORDS[71,55]# complete it ... accept #ACCEPT\"The Battle Plans\"# ", x = 71, y = 55, zone = "Feralas" },
			[14] = { str = "Then go do #DOQUEST\"A Grim Discovery\"# #COORDS[66,46]#", x = 66, y = 46, zone = "Feralas" },
			[15] = { str = "Hearth back to Camp Mojache, turn in #TURNIN\"The Battle Plans\"# and #TURNIN\"A Grim Discovery\"# , accept ALL new quests." },
			[16] = { str = "PLEASE NOTE:  If the 'OOX-22/FE Distress Beacon' item drops, accept the quest #ACCEPT\"Find OOX-22/FE!\"# .  Turn in #TURNIN\"Find OOX-22/FE!\"# at #COORDS[53,55]#.  Then go do:", x = 53, y = 55, zone = "Feralas" },
			[17] = { str = "#DOQUEST\"Stinglasher\"# along with #DOQUEST\"Zukk'ash Infestation\"# #COORDS[74,62]#", x = 74, y = 62, zone = "Feralas" },
			[18] = { str = "#DOQUEST\"Screecher Spirits\"# #COORDS[55,56]#", x = 55, y = 56, zone = "Feralas" },
			[19] = { str = "#DOQUEST\"The Ogres of Feralas\"# part2 #COORDS[59,68]#", x = 59, y = 68, zone = "Feralas" },
			[20] = { str = "#VIDEONOTE:#  While in this area, make sure you pick up a #NPCHippogryph Egg# down south-west (around #COORDS[55,76]#), this will be turned in at Tanaris for a later #NPCquest#.", x = 53, y = 76, zone = "Feralas" },
			[21] = { str = "#DOQUEST\"Dark Ceremony\"# #COORDS[59,68]#", x = 59, y = 68, zone = "Feralas" },
			[22] = { str = "#DOQUEST\"The Mark of Quality\"# #COORDS[53,55]#", x = 53, y = 55, zone = "Feralas" },
			[23] = { str = "Run back to Camp Mojache, then go turn those quests in, accept all new quests just from those quest givers. " },
			[24] = { str = "Then do the following (If you have 90+ gold, go buy your mount! You should have them by now...):" },
			[25] = { str = "Fly to Orgrimmar..." },
			[26] = { str = "Make sure to get 120 Silk Cloths and 120 Mageweave out from either your bank or mailbox. For those of you who can't add, that's 6 stacks of 20 for both Silk and Mageweave." },
			[27] = { str = "Then go turn in: #TURNIN\"Zukk'ash Report\"# #COORDS[56,46]#", x = 56, y = 46, zone = "Orgrimmar" },
			[28] = { str = "Go complete #DOQUEST\"A Donation of Silk\"# and #DOQUEST\"A Donation of Mageweave\"# at #COORDS[63,51]#", x = 63, y = 51, zone = "Orgrimmar" },
			[29] = { str = "Accept #ACCEPT\"Ripple Recovery\"# (from Dran Droffers) #COORDS[59,36]#", x = 59, y = 36, zone = "Orgrimmar" },
			[30] = { str = "Then turn in #TURNIN\"Ripple Recovery\"# (the guy right next to Dran) ... accept #ACCEPT\"Ripple Recovery\"# again." },
			[31] = { str = "Turn in #TURNIN\"Parts of the Swarm\"# and #TURNIN\"A Grim Discovery\"# at #NPCBelgrom Rockmaul#... accept #ACCEPT\"Betrayed\"# #COORDS[75,34]#.  Also get new spells/abilities while you are in Orgrimmar.", x = 75, y = 34, zone = "Orgrimmar" },
			[32] = { str = "Go turn in #TURNIN\"A Strange Request\"# ... Accept #ACCEPT\"Retrun to Witch Doctor Uzer'i\"# (cleft of shadow, #COORDS[49,50]#)", x = 49, y = 50, zone = "Orgrimmar" },
			[33] = { str = "Go turn in #ACCEPT\"Report to Zor\"# ... accept/complete #DOQUEST\"Service to the Horde\"# (valley of wisdom, #COORDS[38,38]#)", x = 38, y = 38, zone = "Orgrimmar" },
			[34] = { str = "Go turn in #TURNIN\"The Gordunni Orb\"# (valley of spirits, #COORDS[39,86]#)", x = 39, y = 86, zone = "Orgrimmar" },
			[35] = { str = "Turn in #TURNIN\"A Donation of Silk\"# and #TURNIN\"A Donation of Mageweave\"# (for the troll faction, at #COORDS[37,87]#)", x = 37, y = 87, zone = "Orgrimmar" },
			[36] = { str = "Now, before hearting back to Ferelas, go Durotar and buy your mount!" },
			[37] = { str = "turn in #TURNIN\"Retrun to Witch Doctor Uzer'i\"# ... accept #ACCEPT\"Natural Materials\"# and #ACCEPT\"Testing the Vessel\"# " },
			[38] = { str = "then do #DOQUEST\"Natural Materials\"# " },
			[39] = { str = "grind away at hippogryphs till it's completed." },
			[40] = { str = "If the \"#NPCOOX-22/FE Distress Beacon#\" item drops, accept the quest #ACCEPT\"Find OOX-22/FE!\"# " },
			[41] = { str = "turn in #TURNIN\"Find OOX-22/FE!\"# at #COORDS[51,57]#", x = 51, y = 57, zone = Ferelas },
			[42] = { str = "if your not level 46, grind till you are on hippogryphs.." },
			[43] = { str = "hearth back to Camp Mojache." },
			[44] = { str = "turn #TURNIN\"Natural Materials\"# in ... accept #ACCEPT\"The Sunken Temple\"# " },
			[45] = { str = "fly to Thunder Bluff" },
			[46] = { str = "turn in #TURNIN\"Deadmire\"# " },
			[47] = { str = "get new spells/abilites." },
			[48] = { str = "Fly to XRs, then to Splintertree Post (Ashenvale)" },
			[49] = { str = "Then go east into Azshara..." },
			--[50] = { str = "." },
			--[51] = { str = "." },
		}
	},

-----------46-46 Azshara
	--[408] = {
	[4646] = {
		title = "46-46 Azshara",
		--n = "46-46 Azshara",
		--pID = 407, nID = 409,
		--itemCount = 16,
		items = {
			[1] = { str = "46-46 Azshara" },
			[2] = { str = "Go accept #DOQUEST\"Spiritual Unrest\"# and #DOQUEST\"A Land Filled with Hatred\"# at #COORDS[10,78]#", x = 10, y = 78, zone = "Azshara" },
			[3] = { str = "Then go do them (at #COORDS[17,66]# and #COORDS[20,62]#), and turn them in.", x = 17, y = 66, zone = "Azshara" },
			[4] = { str = "Then go to Valormok at #COORDS[21,52]#", x = 21, y = 52, zone = "Azshara" },
			[5] = { str = "Turn in #TURNIN\"Betrayed\"# (skip the next part to this quest for now)" },
			[6] = { str = "Then get FP there and fly to Orgrimmar." },
			[7] = { str = "Then head to Under City." },
			[8] = { str = "Then go to Magic Quarter and accept #ACCEPT\"Lines of Communication\"# " },
			[9] = { str = "Head to Apothecarium Quarter and accept: #ACCEPT\"Seeping Corruption\"# and #ACCEPT\"Errand for Apothecary Zinge\"# " },
			[10] = { str = "Then go turn in #ACCEPT\"Errand for Apothecary Zinge\"# (out in the other room)" },
			[11] = { str = "Go return back, and turn in #TURNIN\"Errand for Apothecary Zinge\"# again ... accept #ACCEPT\"Into the Field\"# " },
			[12] = { str = "You can put the 'Field Testing Kit' and the 'Box of Empty Vials' in the Bank for now." },
			[13] = { str = "Fly to Tarren Mill and make it your home." },
			[14] = { str = "Head to the Hinterlands. There a passage at around #COORDS[83,33]#", x = 83, y = 33, zone = "Hillsbard Foothills" },
			--[15] = { str = "." },
		}
	},

-----------46-47 Hinterlands
	--[409] = {
	[4647] = {
		title = "46-47 Hinterlands",
		--n = "46-47 Hinterlands",
		--pID = 408, nID = 410,
		--itemCount = 38,
		items = {
			[1] = { str = "46-47 Hinterlands" },
			[2] = { str = "go turn in #TURNIN\"Ripple Recovery\"# at #COORDS[27,49]# ... accept #ACCEPT\"A Sticky Situation\"# ", x = 27, y = 49, zone = "Hinterlands" },
			[3] = { str = "Ride all the way to Revantusk Village at #COORDS[77,80]#", x = 77, y = 80, zone = "Hinterlands" },
			[4] = { str = "accept: #ACCEPT\"Vilebranch Hooligans\"#, #ACCEPT\"Cannibalistic Cousins\"#, #ACCEPT\"Message to the Wildhammer\"#, #ACCEPT\"Stalking the Stalkers\"#, #ACCEPT\"Hunt the Savages\"# and #ACCEPT\"Avenging the Fallen\"# " },
			[5] = { str = "then go do the following:" },
			[6] = { str = "#DOQUEST\"Whiskey Slim's Lost Grog\"# " },
			[7] = { str = "#DOQUEST\"Vilebranch Hooligans\"# " },
			[8] = { str = "#DOQUEST\"Cannibalistic Cousins\"# " },
			[9] = { str = "#DOQUEST\"A Sticky Situation\"# turn in later ... accept #ACCEPT\"Ripple Delivery\"# " },
			[10] = { str = "#DOQUEST\"Stalking the Stalkers\"# " },
			[11] = { str = "#DOQUEST\"Hunt the Savages\"# " },
			[12] = { str = "#DOQUEST\"Testing the Vessel\"# " },
			[13] = { str = "#DOQUEST\"Avenging the Fallen\"# " },
			[14] = { str = "#DOQUEST\"Lines of Communication\"# " },
			[15] = { str = "#DOQUEST\"Message to the Wildhammer\"# " },
			[16] = { str = "#DOQUEST\"Rin'ji is Trapped!\"# (the escort quest, starts at #COORDS[31,48]#)", x = 31, y = 48, zone = "Hinterlands" },
			[17] = { str = "#DOQUEST\"Grim Message\"# ...while doing this quest accept #ACCEPT\"Venom Bottles\"# (one of those little bottles on the table)" },
			[18] = { str = "Yeah the good 'ol hinterlands grind.. have fun LOL." },
			[19] = { str = "If the \"#NPCOOX-09/HL Distress Beacon#\" item drops, accept the quest #ACCEPT\"Find OOX-09/HL!\"# " },
			[20] = { str = "Turn in #TURNIN\"Find OOX-09/HL!\"# at #COORDS[49,38]#", x = 49, y = 38, zone = "Hinterlands" },
			[21] = { str = "Turn in #TURNIN\"Rin'ji is Trapped!\"# at #COORDS[86,59]# ... accept #ACCEPT\"Rin'ji's Secret\"# ", x = 86, y = 59, zone = "Hinterlands" },
			[22] = { str = "Go to Revantusk Village." },
			[23] = { str = "Turn in ALL quests." },
			[24] = { str = "Then get FP and fly to TM." },
			[25] = { str = "turn in #TURNIN\"Venom Bottles\"# ... accept #ACCEPT\"Undamaged Venom Sac\"# " },
			[26] = { str = "I then get all my magewaeve out from my mailbox, then fly to Hammerfall..." },
			[27] = { str = "Then go to Doctor Gregory Victor to build up first aid..." },
			[28] = { str = "...I’m usually able to get to 290 first aid for Heavy Runecloth bandage." },
			[29] = { str = "Then fly back to TM." },
			[30] = { str = "then ride back into Hinterlands (don’t fly)" },
			[31] = { str = "go do #DOQUEST\"Undamaged Venom Sac\"# and #DOQUEST\"The Atal'ai Exile\"# ... accept #ACCEPT\"Return to Fel'Zerul\"# " },
			[32] = { str = "Then hearth to TarrenMill." },
			[33] = { str = "turn in #TURNIN\"Undamaged Venom Sac\"# ... i SKIP #NPC\"Consult Master Gadrin\"# Only accept this quest if you still need to get a mount as orc/troll, as you turn it in in the same spot." },
			[34] = { str = "Fly to the Undercity." },
			[35] = { str = "go to magic quarter and turn in #TURNIN\"A Donation of Mageweave\"# (you need 60 mageweave cloth for this quest) " },
			[36] = { str = "then turn in: #TURNIN\"Lines of Communication\"# and #TURNIN\"Rin'ji's Secret\"# ..then complete #TURNIN\"Oran's Gratitude\"# " },
			[37] = { str = "get on the zeppelin to go to Grom'gol..." },
			--[38] = { str = "." },
			--[39] = { str = "." },
		}
	},

-----------47-47 Stranglethorn Vale
	--[410] = {
	[4747] = {
		title = "47-47 Stranglethorn Vale",
		--n = "47-47 Stranglethorn Vale",
		--pID = 409, nID = 411,
		--itemCount = 20,
		items = {
			[1] = { str = "47-47 Stranglethorn Vale" },
			[2] = { str = "Go do #DOQUEST\"Raptor Mastery\"# (#NPCTethis#) #COORDS[28,44]# and go turn it in", x = 28, y = 44, zone = "Stranglethorn Vale" },
			[3] = { str = "accept #ACCEPT\"Big Game Hunter\"# (Elite), go do it, then turn it in." },
			[4] = { str = "Go to Grom'gol and turn in #TURNIN\"Grim Message\"# (if you did the Hinterlands section)." },
			[5] = { str = "Fly to BB." },
			[6] = { str = "Accept #ACCEPT\"The Bloodsail Buccaneers\"# part5 and #ACCEPT\"Whiskey Slim's Lost Grog\"# " },
			[7] = { str = "Make BB your home." },
			[8] = { str = "Accept #ACCEPT\"The Captain's Chest\"# (Elite) then go do it at #COORDS[36,65]#  NOTE:  This quest is tough to solo, it can be soloed, but you should find a group to help you kill Gorlash, I personally skip it while racing to 60.", x = 36, y = 65, zone = "Stranglethorn Vale" },
			[9] = { str = "Turn in #TURNIN\"Back to Booty Bay\"# and #TURNIN\"Deliver to MacKinley\"# " },
			[10] = { str = "Make sure that #DOQUEST\"The Captain's Chest\"# is accepted, then go do it at #COORDS[36,65]#  .  If your class has troubles, either find a group to help, or you can simply skip it.", x = 36, y = 65, zone = "Stranglethorn Vale" },
			[11] = { str = "Find a small bottle laying around the shore east of BB, until this item: #NPCCarefully Folded Note# shows up ... which starts #ACCEPT\"Message in a Bottle\"# " },
			[12] = { str = "Go turn #TURNIN\"Message in a Bottle\"# in at #COORDS[38,80]#", x = 38, y = 80, zone = "Stranglethorn Vale" },
			[13] = { str = "Then go do #DOQUEST\"The Bloodsail Buccaneers\"# part5 (kill the three pirates in the three ships) ...while doing it, find #ACCEPT\"Cortello's Riddle\"# (it's usually a little scroll downstairs in the middle ship)" },
			[14] = { str = "Then hearth back to BB, if hearth stone still is on a cooldown, die on purpose." },
			[15] = { str = "Turn in #TURNIN\"The Captain's Chest\"# and #TURNIN\"The Bloodsail Buccaneers\"# part5" },
			[16] = { str = "Fly to Kargath (Badlands).." },
			[17] = { str = "I get a stack of Silk Cloth out of the mailbox for the quest #ACCEPT\"Caught\"# , then..." },
			[18] = { str = "Go into Searing Gorge..." },
			--[19] = { str = "." },
			--[20] = { str = "." },
		}
	},

-----------47-48 Searing Gorge
	--[411] = {
	[4748] = {
		title = "47-48 Searing Gorge",
		--n = "47-48 Searing Gorge",
		--pID = 410, nID = 412,
		--itemCount = 26,
		items = {
			[1] = { str = "47-48 Searing Gorge" },
			[2] = { str = "First thing I do here is go south-east and do #DOQUEST\"Caught!\"# (guy in the outhouse, #COORDS[65,62]#), then turn it in. ... accept #ACCEPT\"Ledger from Tanaris\"# ... click on outhouse to get the #NPCGoodsteel Ledger#", x = 65, y = 62, zone = "Searing Gorge" },
			[3] = { str = "I then go start killing Glassweb Spiders for the #DOQUEST\"Ledger from Tanaris\"# quest." },
			[4] = { str = "Then go up north-west, Talk to #NPCKalaran Windblade# at #COORDS[39,38]# on way to Thorium Point #COORDS[35,25]#. Do first his listen to me quest #DOQUEST\"Divine Retribution\"#. In order to get #ACCEPT\"The Flawless Flame\"# Once at Thorium Point collect ALL quests there and get the FP there too.", x = 35, y = 25, zone = "Searing Gorge" },
			[5] = { str = "Then do the following (steps 5 - 13 in any order):" },
			[6] = { str = "#DOQUEST\"Fiery Menace!\"# " },
			[7] = { str = "#DOQUEST\"Curse These Fat Fingers\"# " },
			[8] = { str = "#DOQUEST\"STOLEN: Smithing Tuyere and Lookout's Spyglass\"# " },
			[9] = { str = "#DOQUEST\"The Flawless Flame\"# turn in, then get and do #DOQUEST\"Forging the Shaft\"# " },
			[10] = { str = "#DOQUEST\"JOB OPPORTUNITY: Culling the Competition\"# " },
			[11] = { str = "#DOQUEST\"WANTED: Overseer Maltorius\"# (Elite) (only do this quest with a group, even a level 60 has a hard time soloing this quest)." },
			[12] = { str = "#DOQUEST\"What the Flux?\"#  (the plans for #DOQUEST\"What the Flux?\"# quest is right behind Overseer Maltorius)" },
			[13] = { str = "#DOQUEST\"Incendosaurs? Whateverosaur is More Like It\"# " },
			[14] = { str = "#DOQUEST\"The Key to Freedom\"# starts from an item drop #NPCGrimsite Outhouse Key#, turn in at the outhouse (south-east, #COORDS[65,62]#)", x = 65, y = 62, zone = "Searing Gorge" },
			[15] = { str = "Turn in #TURNIN\"Forging the Shaft\"# ... accept #ACCEPT\"The Flame's Casing\"# " },
			[16] = { str = "Do #DOQUEST\"The Flame's Casing\"# (around #COORDS[24,36]#).  Just keep killing the mobs there until the item drops.", x = 24, y = 36, zone = "Searing Gorge" },
			[17] = { str = "Then turn in #TURNIN\"The Flame's Casing\"# ... accept and do #DOQUEST\"The Torch of Retribution\"# , then turn it in ... accept and do #DOQUEST\"The Torch of Retribution\"# Part2 (just pick up the torch on the ground." },
			[18] = { str = "Accept #ACCEPT\"Squire Maltrake\"# , then turn it in ... accept #ACCEPT\"Set Them Ablaze!\"# " },
			[19] = { str = "Do #DOQUEST\"Set Them Ablaze!\"# (north=#COORDS[33,54]#, south=#COORDS[44,61]#, east=#COORDS[50,54]#, west=#COORDS[35,60]#).  Once that is done, go back and turn it in.", x = 33, y = 54, zone = "Searing Gorge" },
			[20] = { str = "Click on the little chest on the ground at #COORDS[38,38]# and accept #ACCEPT\"Trinkets...\"# , then click on the chest again to turn it in.", x = 38, y = 38, zone = "Searing Gorge" },
			[21] = { str = "Make sure you keep the #NPCBlack Dragonflight Molt# in your inventory as you will need it for a later #NPCquest#." },
			[22] = { str = "Once all that's done, turn all Searing Gorge quests in. make sure you have all 20 solid crystal leg shafts." },
			[23] = { str = "Head south into Burning Steppes (You have to go through Black Rock Mountains).." },
			[24] = { str = "I discover some areas, then get FP there at #COORDS[65,25]#, and fly directly to Stonard (swamp of sorrows)...", x = 65, y = 25, zone = "Searing Gorge" },
			--[25] = { str = "." },
			--[26] = { str = "." },
		}
	},

-----------48-48 Swamp of Sorrows
	--[412] = {
	[4848] = {
		title = "48-48 Swamp of Sorrows",
		--n = "48-48 Swamp of Sorrows",
		--pID = 411, nID = 413,
		--itemCount = 29,
		items = {
			[1] = { str = "48-48 Swamp of Sorrows" },
			[2] = { str = "Do NOT make Stonard your home. (it should still be Booty Bay)" },
			[3] = { str = "Go to the #NPCFallen Hero of the Horde# #COORDS[34,66]# ... keep talking to him till you get this quest: #ACCEPT\"The Disgraced One\"# ", x = 34, y = 66, zone = "Searing Gorge" },
			[4] = { str = "Then go do #DOQUEST\"Cortello's Riddle\"# (#COORDS[22,48]# under the bridge)", x = 22, y = 48, zone = "Searing Gorge" },
			[5] = { str = "Accept #ACCEPT\"Cortello's Riddle\"# part2" },
			[6] = { str = "Go back to Stonard." },
			[7] = { str = "Go turn in #TURNIN\"The Disgraced One\"# (and #TURNIN\"Return to Fel'Zerul\"# if you did Hinterlands)... accept #ACCEPT\"The Missing Orders\"# " },
			[8] = { str = "#HUNTER07) Get new hunter spells/abilities#" },
			[9] = { str = "Go turn in #TURNIN\"The Missing Orders\"# (in the inn) ... accept #ACCEPT\"The Swamp Talker\"# " },
			[10] = { str = "Go do #DOQUEST\"The Swamp Talker\"# (in the cave at #COORDS[65,78]#)", x = 65, y = 78, zone = "Searing Gorge" },
			[11] = { str = "Then head north east and.." },
			[12] = { str = "Go kill the mob #NPCJarquia# (at around #COORDS[94,50]# or #COORDS[92,65]#), he drops #NPCGoodsteel's Balanced Flameberge#... for the quest #DOQUEST\"Ledger from Tanaris\"# ", x = 94, y = 50, zone = "Searing Gorge" },
			[13] = { str = "Then die on purpose, so you end up at Stonard." },
			[14] = { str = "Go to the #NPCFallen Hero of the Horde# #COORDS[34,66]# and turn in #TURNIN\"The Swamp Talker\"# ", x = 34, y = 66, zone = "Searing Gorge" },
			[15] = { str = "Accept and do #DOQUEST\"A Tale of Sorrow\"# (Just talk to the guy)" },
			[16] = { str = "Hearth to Booty Bay." },
			[17] = { str = "Get on the boat to go to Ratchet." },
			[18] = { str = "Fly to Brackenwall Village (Dustwallow Marsh).  Once there accept #ACCEPT\"The Brood of Onyxia\"# " },
			[19] = { str = "Then head south and get the #NPCOverdue Package# for the quest #DOQUEST\"Ledger from Tanaris\"# at #COORDS[54,55]#", x = 54, y = 55, zone = "Dustwallow Marsh" },
			[20] = { str = "Go down a bit and do #DOQUEST\"The Brood of Onyxia\"#   (the eggs can be found at #COORDS[53,72]# and #COORDS[48,75]#)", x = 53, y = 72, zone = "Dustwallow Marsh" },
			[21] = { str = "Then head west to Bloodfen Burrow cave #COORDS[32,67]#, and do #DOQUEST\"Cortello's Riddle\"# ... accept the next part to it.", x = 32, y = 67, zone = "Dustwallow Marsh" },
			[22] = { str = "Then die on purpose, so you end up back at Brackenwall Village." },
			[23] = { str = "Turn in #TURNIN\"The Brood of Onyxia\"# ... accept #ACCEPT\"Challenge Overlord Mok'Morokk\"# (??? TBC Quest)" },
			[24] = { str = "Do #DOQUEST\"Challenge Overlord Mok'Morokk\"# Then turn it in. (??? TBC Quest)" },
			[25] = { str = "Then fly to Tanaris.." },
			[26] = { str = "Turn in #TURNIN\"Ledger from Tanaris\"# and #TURNIN\"Into the Field\"# ... accept and complete #DOQUEST\"Slake that Thirst\"#" },
			[27] = { str = "Then fly to Ferelas.." },
			--[28] = { str = "." },
			--[29] = { str = "." },
		}
	},

--------48-49 Feralas
	--[413] = {
	[4849] = {
		title = "48-49 Ferelas",
		--n = "48-49 Feralas",
		--pID = 412, nID = 414,
		--itemCount = 27,
		items = {
			[1] = { str = "48-49 Feralas" },
			[2] = { str = "turn in #TURNIN\"Testing the Vessel\"# ... accept #ACCEPT\"Hippogryph Muisek\"# " },
			[3] = { str = "accept: #ACCEPT\"Improved Quality\"#, #ACCEPT\"Vengeance on the Northspring\"# and #ACCEPT\"Dark Heart\"# (Elite)" },
			[4] = { str = "make it your home." },
			[5] = { str = "go do #DOQUEST\"Hippogryph Muisek\"# " },
			[6] = { str = "then hearth back to Camp Mojache." },
			[7] = { str = "turn in #TURNIN\"Hippogryph Muisek\"# ... accept #ACCEPT\"Faerie Dragon Muisek\"# " },
			[8] = { str = "go do #DOQUEST\"Faerie Dragon Muisek\"# .. then turn it in ... accept #ACCEPT\"Treant Muisek\"# " },
			[9] = { str = "go do #DOQUEST\"Treant Muisek\"# .. then turn it in ... accept #ACCEPT\"Mountain Giant Muisek\"# (Elite)" },
			[10] = { str = "Stable pet." },
			[11] = { str = "go accept #ACCEPT\"Zapped Giants\"# at #COORDS[44,44]#" },
			[12] = { str = "go tame an Ironfur Patriarch (for Claw Rank7)" },
			[13] = { str = "then use that pet to Do the following quests:" },
			[14] = { str = "#DOQUEST\"Improved Quality\"# " },
			[15] = { str = "#DOQUEST\"Perfect Yeti Hide\"# (you should find this item/quest while doing this quest: #NPC\"Improved Quality\"#)" },
			[16] = { str = "#DOQUEST\"Vengeance on the Northspring\"# " },
			[17] = { str = "#DOQUEST\"Dark Heart\"# (Elite)" },
			[18] = { str = "#DOQUEST\"Mountain Giant Muisek\"# (Elite) along with #DOQUEST\"Zapped Giants\"#" },
			[19] = { str = "once those quests are completed and #TURNIN\"Zapped Giants\"# is turned in..." },
			[20] = { str = "..hearth to Camp Mojache." },
			[21] = { str = "abandon bear, get cat back out." },
			[22] = { str = "Turn in #TURNIN\"Mountain Giant Muisek\"# (Elite) ... accept #ACCEPT\"Weapons of Spirit\"# ... then turn it in complete it." },
			[23] = { str = "Turn in #TURNIN\"Improved Quality\"#, #TURNIN\"Perfect Yeti Hide\"#, #TURNIN\"Vengeance on the Northspring\"# and #TURNIN\"Dark Heart\"# " },
			[24] = { str = "Accept #ACCEPT\"The Strength of Corruption\"# " },
			[25] = { str = "Fly to Tanaris..." },
			--[26] = { str = "." },
			--[27] = { str = "." },
		}
	},

-----------49-50 Tanaris
	--[414] = {
	[4950] = {
		title = "49-50 Tanaris",
		--n = "49-50 Tanaris",
		--pID = 413, nID = 501,
		--itemCount = 33,
		items = {
			[1] = { str = "49-50 Tanaris" },
			[2] = { str = "Go to the Egg-O-Matic machine in Gadgetzan, and turn in the #NPCHippogryph Egg# for #DOQUEST\"The Super Egg-O-Matic\"# quest." },
			[3] = { str = "Make Gadgetzan your home." },
			[4] = { str = "Accept: #ACCEPT\"The Thirsty Goblin\"# #ACCEPT\"Noxious Lair Investigation\"# #ACCEPT\"Super Sticky\"# #ACCEPT\"Thistleshrub Valley\"# and #ACCEPT\"The Dunemaul Compound\"# " },
			[5] = { str = "Go turn in #TURNIN\"The Sunken Temple\"# at #COORDS[52,45]# ... accept #ACCEPT\"The Stone Circle\"# and #ACCEPT\"Gahz'ridian\"# ", x = 52, y = 45, zone = "Tanaris" },
			[6] = { str = "Go do in the following order:" },
			[7] = { str = "#DOQUEST\"The Dunemaul Compound\"# along with #DOQUEST\"Gahz'ridian\"# (done at #COORDS[46,66]# and #COORDS[40,73]#, Gor'marok is in the cave at #COORDS[40,58]#)", x = 40, y = 58, zone = "Tanaris" },
			[8] = { str = "#DOQUEST\"Noxious Lair Investigation\"# #COORDS[34,47]#", x = 34, y = 47, zone = "Tanaris" },
			[9] = { str = "#DOQUEST\"Thistleshrub Valley\"# along with #DOQUEST\"The Thirsty Goblin\"# #COORDS[28,65]#", x = 28, y = 65, zone = "Tanaris" },
			[10] = { str = "#DOQUEST\"Tooga's Quest\"# (escort turtle quest starts in the Thistleshrub Valley, lead Tooga to Torta at #COORDS[66,25]#).", x = 66, y = 25, zone = "Tanaris" },
			[11] = { str = "Then turn in #TURNIN\"Tooga's Quest\"# along with #TURNIN\"Screecher Spirits\"# " },
			[12] = { str = "Run to Gadgetzan." },
			[13] = { str = "Turn in #TURNIN\"The Thirsty Goblin\"# ... accept #ACCEPT\"In Good Taste\"# turn it in ... accept #ACCEPT\"Sprinkle's Secret Ingredient\"# " },
			[14] = { str = "Turn in #TURNIN\"Thistleshrub Valley\"#  #TURNIN\"The Dunemaul Compound\"# and #TURNIN\"Noxious Lair Investigation\"# " },
			[15] = { str = "Accept #ACCEPT\"The Scrimshank Redemption\"# " },
			[16] = { str = "Remember to get your Sampling Kit from the bank and go do:" },
			[17] = { str = "#DOQUEST\"Tanaris Field Sampling\"# and turn in #TURNIN\"Gahz'ridian\"# at #COORDS[52,45]#.", x = 52, y = 45, zone = "Tanaris" },
			[18] = { str = "#DOQUEST\"The Scrimshank Redemption\"#   (in the cave at #COORDS[53,70]#)  The secret for finding the item for this quest is keep making right turns in the cave and it will lead you to it.  ", x = 53, y = 70, zone = "Tanaris" },
			[19] = { str = "If the \"OOX-17/TN Distress Beacon\" item drops, accept the quest #ACCEPT\"Find OOX-17/TN!\"# " },
			[20] = { str = "Turn in #TURNIN\"Find OOX-17/TN!\"# at #COORDS[60,64]#", x = 60, y = 64, zone = "Tanaris" },
			[21] = { str = "Then do the Chicken escort #DOQUEST\"Rescue OOX-17/TN!\"# " },
			[22] = { str = "Once all those quests are finished.." },
			[23] = { str = "Hearth to Gadgetzan." },
			[24] = { str = "Turn in #TURNIN\"Tanaris Fiels Sampling\"# ... accept #ACCEPT\"Return to Apothecary Zinge\"# " },
			[25] = { str = "Turn in #TURNIN\"The Scrimshank Redemption\"# ... accept #ACCEPT\"Insect Part Analysis\"# " },
			[26] = { str = "Turn in #TURNIN\"Insect Part Analysis\"# ... accept #ACCEPT\"Insect Part Analysis\"# again." },
			[27] = { str = "Turn in #TURNIN\"Insect Part Analysis\"# ... accept #ACCEPT\"Rise of the Silithid\"# " },
			[28] = { str = "Fly to Orgrimmar.." },
			[29] = { str = "Make Orgrimmar your home." },
			[30] = { str = "Get the Box of Empty Vials out of your Bank." },
			[31] = { str = "Fly to Azshara..." },
			--[32] = { str = "." },
			--[33] = { str = "." },
		}
	},
}
