Table_002_ElwynnForest = {
-----------1-10 Elwynn Forest
	[0110] = {
		title = "1-10 Elwynn Forest",
		items = {
			[1] = { str = "1-10 Elwynn Forest" },
			[2] = { str = "Directly in front of where you start accept #Q_'A Threat Within'# then go in the building and turn it in, accept #Q_'Kobold Camp Cleanup'#." },
			[3] = { str = "Run back out, and turn in 'Welcome!' at the wagons at #C_[47,41]#.", x = 47, y = 41, zone = "Elwynn Forest" },
			[4] = { str = "Go to the nook at the NW corner of the building at #C_[48,40]# and accept #Q_'Wolves Across the Border'#.", x = 48, y = 40, zone = "Elwynn Forest" },
			[5] = { str = "Kill the wolves all in front of you for #Q_'Wolves Across the Border'# while working your way to the kobold vermin at #C_[47,35]# for #Q_'Kobold Camp Cleanup'#.", x = 47, y = 35, zone = "Elwynn Forest" },
			[6] = { str = "Go back to #C_[48,40]# and turn in #Q_'Wolves Across the Border'#.", x = 48, y = 40, zone = "Elwynn Forest" },
			[7] = { str = "Run into the house at #C_[48,41]# and turn in #Q_'Kobold Camp Cleanup'# accept #Q_'Simple Letter'# and #Q_'Investigate Echo Ridge'#.", x = 48, y = 41, zone = "Elwynn Forest" },
			[8] = { str = "Talk to your #N_Class Trainer# to learn new spells and abilities.", x = 50, y = 42, zone = "Elwynn Forest" },
			[9] = { str = "Exit the house and grab #Q_'Brotherhood of Thieves'# just outside." },
			[10] = { str = "Go NW toward the cave at #C_[47,32]# and kill kobold workers on the way up to it for #Q_'Investigate Echo Ridge'#.", x = 47, y = 32, zone = "Elwynn Forest" },

			[11] = { str = "Go West to #C_[54,40]# and go south killing the defias until you finish #Q_'Brotherhood of Thieves'# you should have dinged 4 by the time you’re done, if not just kill until you are.", x = 54, y = 40, zone = "Elwynn Forest" },
			[12] = { str = "Run back to the abbey at #C_[48,42]# and turn in #Q_'Brotherhood of Thieves'# accept #Q_'Milly Osworth'# and #Q_'Bounty on Garrick Padfoot'#.", x = 48, y = 42, zone = "Elwynn Forest" },
			[13] = { str = "Go inside the house and turn in #Q_'Investigate Echo Ridge'# accept #Q_'Skirmish at Echo Ridge'#. Talk to your #N_Class Trainer# to learn new spells and abilities." },
			[14] = { str = "Go north of the house at #C_[50,39]# next to the barn, turn in #Q_'Milly Osworth'#. Accept #Q_'Milly's Harvest'#.", x = 50, y = 39, zone = "Elwynn Forest" },
			[15] = { str = "Go back east and grab the grapes in the garden at #C_[54,48]# for #Q_'Milly's Harvest'# then NE to #C_[57,48]# you’ll see a shack with padfoot and a thug. Kill him for #Q_'Bounty on Garrick Padfoot'#.", x = 57, y = 48, zone = "Elwynn Forest" },
			[16] = { str = "Go back to #C_[50,39]# and turn in #Q_'Milly's Harvest'#. Accept #Q_'Grape Manifest'#.", x = 50, y = 39, zone = "Elwynn Forest" },
			[17] = { str = "Go into the cave at #C_[47,31]# and kill kobold laborer’s for #Q_'Skirmish at Echo Ridge'#.", x = 47, y = 31, zone = "Elwynn Forest" },
			[18] = { str = "Use your #I_[Hearthstone]# to return to the Abbey." },
			[19] = { str = "Turn in #Q_'Bounty on Garrick Padfoot'# right in front of you." },
			[20] = { str = "Go inside the house, turn in #Q_'Skirmish at Echo Ridge'#. Accept #Q_'Report to Goldshire'#." },

			[21] = { str = "Go to the top of the tower through the spiral staircase, turn in #Q_'Grape Manifest'#." },
			[22] = { str = "Go to #C_[45,47]# and accept #Q_'Rest and Relaxation'#.", x = 45, y = 47, zone = "Elwynn Forest" },
			[23] = { str = "If you’re not 6 you should be close, just grind on a few mobs while you head towards the house near #A_Goldshire# (#A_Elwynn Forest#) at #C_[46,62]# and pick up skinning if you want it.", x = 46, y = 42, zone = "Elwynn Forest" },
			[24] = { str = "Reach #A_Goldshire# (#A_Elwynn Forest#) and enter the Inn at #C_[42,65]#.", x = 42, y = 65, zone = "Elwynn Forest" },
			[25] = { str = "Just to your left accept #Q_'Kobold Candles'#." },
			[26] = { str = "Near the bar turn in #Q_'Rest and Relaxation'# and make #A_Goldshire# (#A_Elwynn Forest#) your home." },
			[27] = { str = "Exit the Inn and go straight out, turn in #Q_'Report to Goldshire'#. Accept #Q_'The Fargodeep Mine'#." },
			[28] = { str = "Talk to your #N_Class Trainer# to learn new spells and abilities." },
			[29] = { str = "Go near the carts at #C_[42,67]# and accept #Q_'Gold Dust Exchange'#.", x = 42, y = 67, zone = "Elwynn Forest" },
			[30] = { str = "Go south to the Fargodeep Mine at #C_[39,82]# and kill the kobold until you complete all 3 quests #Q_'The Fargodeep Mine'#, #Q_'Gold Dust Exchange'#, and #Q_'Kobold Candles'# Make sure you go in the lower entrance so The Fargodeep Mine is easier.", x = 39, y = 82, zone = "Elwynn Forest" },

			[31] = { str = "Once all 3 are done go to the stonefield farm just up the hill east at #C_[34,84]# and accept #Q_'Lost Necklace'# SKIP #Q_'Princess Must Die!'# it’s just too hard to do alone.", x = 34, y = 84, zone = "Elwynn Forest" },
			[32] = { str = "Go east to the Maclure Vinyard at #C_[43,80]# and accept #Q_'Young Lovers'#.", x = 43, y = 80, zone = "Elwynn Forest" },
			[33] = { str = "Go to #C_[43,85]# and turn in #Q_'Lost Necklace'# accept #Q_'Pie For Billy'# then turn around and kill boars until it’s finished.", x = 43, y = 85, zone = "Elwynn Forest" },
			[34] = { str = "Go back west to #C_[34,84]# and turn in #Q_'Pie For Billy'# and accept #Q_'Back to Billy'#.", x = 34, y = 84, zone = "Elwynn Forest" },
			[35] = { str = "Go west some to the river at #C_[29,85]# and turn in #Q_'Young Lovers'# accept #Q_'Speak with Gramma'#.", x = 29, y = 85, zone = "Elwynn Forest" },
			[36] = { str = "Go back to #C_[34,84]# and turn in #Q_'Speak with Gramma'# in the house, accept #Q_'Note to William'#.", x = 34, y = 84, zone = "Elwynn Forest" },
			[37] = { str = "Run back east to #C_[43,85]# and turn in #Q_'Back to Billy'# accept #Q_'Goldtooth'#.", x = 43, y = 85, zone = "Elwynn Forest" },
			[38] = { str = "Go in the bottom entrance of the fargodeep mine at #C_[39,82]# and to about #C_[41,78]# inside and kill goldtooth for #Q_'Goldtooth'# You should ding 7 sometime in the cave or before you came in.", x = 41, y = 78, zone = "Elwynn Forest" },
			[39] = { str = "Use your #I_[Hearthstone]# to return to back to #A_Goldshire# (#A_Elwynn Forest#)." },
			[40] = { str = "In the Inn turn in #Q_'Kobold Candles'# accept #Q_'Shipment to Stormwind'# also turn in #Q_'Note to William'# accept #Q_'Collecting Kelp'#." },

			[41] = { str = "Straight outside the Inn, turn in The Fargodeep Mine accept #Q_'The Jasperlode Mine'#." },
			[42] = { str = "South near the fence, turn in #Q_'Gold Dust Exchange'# You should have dinged lvl 7 now, accept #Q_'A Fishy Peril'#." },
			[43] = { str = "Turn around by the blacksmith and turn it in, accept #Q_'Further Concerns'#." },
			[44] = { str = "Kill murlocs around the lake at #C_[51,65]# for #Q_'Collecting Kelp'#.", x = 51, y = 65, zone = "Elwynn Forest" },
			[45] = { str = "Grind up to the Jasperlode mine at #C_[61,53]# and run through it about half way to #C_[60,50]# for #Q_'The Jasperlode Mine'#.", x = 60, y = 50, zone = "Elwynn Forest" },
			[46] = { str = "Run to the bridge at #C_[73,72]# and turn in #Q_'Further Concerns'# accept #Q_'Find the Lost Guards'# and #Q_'Protect the Frontier'#.", x = 73, y = 72, zone = "Elwynn Forest" },
			[47] = { str = "Stop at the house NE of here at #C_[79,68]# and accept #Q_'Red Linen Goods'#.", x = 79, y = 68, zone = "Elwynn Forest" },
			[48] = { str = "At the center of the camp, #C_[81,66]#, accept #Q_'A Bundle of Trouble'#.", x = 81, y = 66, zone = "Elwynn Forest" },
			[49] = { str = "Run just west of the waterfall at #C_[72,60]# touch the mangled body and turn in #Q_'Find the Lost Guards'#. Accept #Q_'Discover Rolf’s Fate'# if this doesn’t make you ding 8 then grind that last tiny bit.", x = 72, y = 60, zone = "Elwynn Forest" },
			[50] = { str = "Go to the murloc camp at #C_[79,55]# and loot the mangled body there (might need a group, but usually always people here) and turn in #Q_'Discover Rolf’s Fate'#. Accept #Q_'Report to Thomas'#.", x = 79, y = 55, zone = "Elwynn Forest" },

			[51] = { str = "Go south to #C_[81,66]# and turn in #Q_'A Bundle of Trouble'#.", x = 81, y = 66, zone = "Elwynn Forest" },
			[52] = { str = "Cross the road and go south and east and finish killing the bears and wolves for #Q_'Protect the Frontier'# bears are kinda scarce so you might have to search." },
			[53] = { str = "While doing this you can get some, if not all, of the red bandannas for #Q_'Red Linen Goods'# at #C_[90,78]#.", x = 90, y = 78, zone = "Elwynn Forest" },
			[54] = { str = "Go back to #C_[73,72]# near the bridge and turn in #Q_'Protect the Frontier'# and #Q_'Report to Thomas'# acept #Q_'Deliver Thomas' Report'#.", x = 73, y = 72, zone = "Elwynn Forest" },
			[55] = { str = "Go down to the pumpkin patch at #C_[69,78]# and kill the rest of the defias for #Q_'Red Linen Goods'#.", x = 69, y = 78, zone = "Elwynn Forest" },
			[56] = { str = "You might find #I_[Furlbrow's Deed]# on the defias while you’re killing defias just hold it for now." },
			[57] = { str = "Go to #C_[79,68]# and turn in #Q_'Red Linen Goods'# it should make you lvl 9 or bring you really close.", x = 79, y = 68, zone = "Elwynn Forest" },
			[58] = { str = "Stop at the bridge again at #C_[73,72]# and accept #Q_'Report to Gryan Stoutmantle'# must be 9 to accept.", x = 73, y = 72, zone = "Elwynn Forest" },
			[59] = { str = "Use your #I_[Hearthstone]# to return to #A_Goldshire# (#A_Elwynn Forest#)." },
			[60] = { str = "By the front door turn in #Q_'Collecting Kelp'# accept #Q_'The Escape'#." },

			[61] = { str = "Just outside the Inn turn in #Q_'The Jasperlode Mine'# and #Q_'Deliver Thomas' Report'# SKIP #Q_'Cloth and Leather Armor'#. Accept #Q_'Westbrook Garrison Needs Help!'#." },
			[62] = { str = "In the blacksmith house right here accept #Q_'Elmore's Task'# then get training." },
			[63] = { str = "Run south to the maclure vinyard at #C_[43,89]# and turn in #Q_'The Escape'#.", x = 43, y = 89, zone = "Elwynn Forest" },
			[64] = { str = "Run west to the stonefield farm at #C_[34,84]# and turn in #Q_'Goldtooth'#.", x = 34, y = 84, zone = "Elwynn Forest" },
			[65] = { str = "Go NW to #C_[34,74]# and turn in #Q_'Westbrook Garrison Needs Help!'#. Accept #Q_'Riverpaw Gnoll Bounty'# You will also see the wanted poster and it’s the famous old hogger quest. He’s a tough lvl 11 elite and is not easy so skip it, unless you have a group it’s up to you. Remember on new servers you’re probably still within range of everyone so it shouldn’t be hard to get done.", x = 34, y = 74, zone = "Elwynn Forest" },
			[66] = { str = "Go just south of the road and start killing gnolls for #Q_'Riverpaw Gnoll Bounty'# they can also drop a gold schedule which starts a quest." },
			[67] = { str = "Go back up to #C_[34,74]# and turn in #Q_'Riverpaw Gnoll Bounty'#.", x = 34, y = 74, zone = "Elwynn Forest" },
			[68] = { str = "You should be very close to 10 now." },
			[69] = { str = "Follow the road west into #A_Westfall#." },
		}
	},

-----------10-12 Westfall and Loch Modan
	[1012] = {
		title = "10-12 Westfall and Loch Modan",
		items = {
			[1] = { str = "10-12 Westfall and Loch Modan" },
			[2] = { str = "Go to #C_[59,19]# and turn in #Q_'Furlbrow’s Deed'# if you found it before.", x = 59, y = 19, zone = "Westfall" },
			[3] = { str = "Accept #Q_'Westfall Stew'# SKIP #Q_'Poor Old Blanchy'#." },
			[4] = { str = "Go in the house at #C_[56,30]# and turn in #Q_'Westfall Stew'#.", x = 56, y = 30, zone = "Westfall" },
			[5] = { str = "Go to #C_[56,47]# and turn in #Q_'Report to Gryan Stoutmantle'#.", x = 56, y = 47, zone = "Westfall" },
			[6] = { str = "Go in the tower and accept #Q_'A Swift Message'#." },
			[7] = { str = "Unlock the flight path by talking to the #N_Flight Master# at #C_[56,52]# and turn in #Q_'A Swift Message'# accept #Q_'Continue to Stormwind'#.", x = 56, y = 52, zone = "Westfall" },
			[8] = { str = "Fly to #A_Stormwind# unless you did hogger, then use your #I_[Hearthstone]# to return to #A_Goldshire# (#A_Elwynn Forest#) and turn it in outside the Inn then train." },
			[9] = { str = "In #A_Stormwind# go to #C_[56,64]# and turn in #Q_'Shipment to Stormwind'#.", x = 56, y = 64, zone = "Stormwind" },
			[10] = { str = "Train new weapons at #C_[57,57]#.", x = 57, y = 57, zone = "Stormwind" },

			[11] = { str = "Go to #C_[74,47]# and turn in #Q_'Continue to Stormwind'# accept #Q_'Dungar Longdrink'#.", x = 74, y = 47, zone = "Stormwind" },
			[12] = { str = "Go to #C_[51,12]# and turn in #Q_'Elmore's Task'#. Accept #Q_'Stormpike's Delivery'# this will be done on the way to the #A_Wetlands#.", x = 51, y = 12, zone = "Stormwind" },
			[13] = { str = "Go to #C_[78,45]# and accept 'A Warrior’s Training' or your classes lvl 10 quest.", x = 78, y = 45, zone = "Stormwind" },
			[14] = { str = "Go to #C_[66,62]# and turn in #Q_'Stormpike's Delivery'#. Accept #Q_'Return to Lewis'# then fly back to #A_Westfall#.", x = 66, y = 62, zone = "Stormwind" },
			[15] = { str = "Go to the tower at #C_[56,47]# and turn in #Q_'Return to Lewis'# super easy xp.", x = 56, y = 47, zone = "Westfall" },
			[16] = { str = "Fly back to #A_Stormwind# Go in the bar at #C_[74,37]# and turn in 'A Warrior’s Training'. Accept #Q_'Bartleby the Drunk'# then turn around and hand it in. Accept #Q_'Beat Bartleby'#.", x = 74, y = 37, zone = "Stormwind" },
			[17] = { str = "Kick bartleby’s ass then talk to him again and accept #Q_'Bartleby's Mug'# then turn it in behind you and learn your defense." },
			[18] = { str = "Go into the tram at #C_[63,8]# and take it to #A_Ironforge#.", x = 63, y = 8, zone = "Stormwind" },
			[19] = { str = "Once it stops accept #Q_'Deeprun Rat Roundup'# just collect 5 rats and turn it in. You could skip this and keep the flute, It can really piss people off if you play it non stop around the #A_Ironforge# bank. SKIP #Q_'Me Brother, Nipsy'# unless you go back to #A_Stormwind# on the tram because you get crap xp." },
			[20] = { str = "Unlock the flight path by talking to the #N_Flight Master# at #C_[55,47]#.", x = 55, y = 47, zone = "Ironforge" },

			[21] = { str = "After the rat quest you should be real close to 11." },
			[22] = { str = "Leave #A_Ironforge# and head into #A_Dun Morogh#." },
			[23] = { str = "Run east to #C_[68,55]# and accept #Q_'The Public Servant'#.", x = 68, y = 55, zone = "Dun Morogh" },
			[24] = { str = "Go behind him and accept #Q_'Those Blasted Troggs!'#." },
			[25] = { str = "Go in the pidd below and kill the troggs here and in the cave for both quests then turn them back in at #C_[68,55]#.", x = 68, y = 55, zone = "Dun Morogh" },
			[26] = { str = "Go east to #C_[80,51]# and follow the path into #A_Loch Modan#.", x = 80, y = 51, zone = "Dun Morogh" },
			[27] = { str = "Go to #C_[22,73]# and accept #Q_'In Defense of the King's Lands'#.", x = 22, y = 73, zone = "Loch Modan" },
			[28] = { str = "Go up in the tower and accept #Q_'The Trogg Threat'#." },
			[29] = { str = "Unlock the flight path by talking to the #N_Flight Master# at #C_[33,50]#.", x = 33, y = 50, zone = "Loch Modan" },
			[30] = { str = "Look for the wandering NPC #N_Mountaineer Kadrell# and accept #Q_'Rat Catching'#." },

			[31] = { str = "Kill troggs from #C_[27,53]# and north for #Q_'In Defense of the King's Lands'# and #Q_'The Trogg Threat'#.", x = 27, y = 53, zone = "Loch Modan" },
			[32] = { str = "Kill mobs from #C_[26,43]# and north for #Q_'Rat Catching'#, then turn it in at #A_Thelsamar#.", x = 26, y = 43, zone = "Loch Modan" },
			[33] = { str = "Go back to #C_[22,73]# and turn them both in.", x = 22, y = 73, zone = "Loch Modan" },
			[34] = { str = "Go north to the tower at #C_[24,18]# and turn in #Q_'Stormpike's Delivery'#.", x = 24, y = 18, zone = "Loch Modan" },
			[35] = { str = "You should be 12 now or close to it. You can grind if you’d like but it doesn’t matter much. Follow the Night Elf to #A_Ironforge# guide but just go backwards. You’re going to go north through the #A_Wetlands# to #A_Menethil Harbor#, then boat to #A_Auberdine# from here." },
		}
	},
}
