Table_002_DunMorogh = {
-----------1-6 Coldridge Valley
	[0106] = {
		title = "1-6 Coldridge Valley",
		items = {
			[1] = { str = "1-6 Coldridge Valley" },
			[2] = { str = "Right in front of where you start accept Dwarven Outfitters." },
			[3] = { str = "Go south around #COORDS[28,73]# and kill wolves for the meat then go back to #COORDS[29,71]# and turn in Dwarven Outfitters then accept Encrypted Rune and Coldridge Valley Mail Delivery pt.1.", x = 29, y = 71, zone = "Dun Morogh" },
			[4] = { str = "To your left accept A New Threat." },
			[5] = { str = "At #COORDS[30,74]# kill burly troggs and at #COORDS[26,72]# there is a camp of rockjaw troggs, kill them for A New Threat.", x = 26, y = 72, zone = "Dun Morogh" },
			[6] = { str = "Go back to #COORDS[29,71]# and turn in A New Threat you should be 3 now.", x = 29, y = 71, zone = "Dun Morogh" },
			[7] = { str = "Go in Anvilmar at #COORDS[28,69]# and turn in your classes skill npc quest which was Encrypted Rune for a rogue.", x = 28, y = 69, zone = "Dun Morogh" },
			[8] = { str = "Accept A Refugee's Quandary inside." },
			[9] = { str = "Follow the road south to #COORDS[22,71]# and turn in Coldridge Valley Mail Delivery pt.1 accept Coldridge Valley Mail Delivery pt.2 and The Boar Hunter.", x = 22, y = 71, zone = "Dun Morogh" },
			[10] = { str = "Just behind him start killing small boars until you have 12 for The Boar Hunter then go back to #COORDS[22,71]# and turn it in" },

			[11] = { str = "At #COORDS[20,76]# clear the front of the tent and grab Felix's Box for A Refugee's Quandary.", x = 20, y = 76, zone = "Dun Morogh" },
			[12] = { str = "At #COORDS[22,80]# clear in front of the tent and grab Felix's Chest for A Refugee's Quandary.", x = 22, y = 80, zone = "Dun Morogh" },
			[13] = { str = "Run up to #COORDS[25,75]# (it’s the end of the road on the map) and turn in Coldridge Valley Mail Delivery pt.2 and accept The Troll Cave.", x = 25, y = 75, zone = "Dun Morogh" },
			[14] = { str = "At #COORDS[26,79]# clear in front of the cave and grab Felix's Bucket of Bolts for A Refugee's Quandary then kill the trolls in and out of it until you complete The Troll Cave.", x = 26, y = 79, zone = "Dun Morogh" },
			[15] = { str = "Run back up to #COORDS[25,75]# and turn in 'The Troll Cave' accept 'The Stolen Journal' you should be 5 or very close to it now.", x = 25, y = 75, zone = "Dun Morogh" },
			[16] = { str = "Go back in the cave at #COORDS[26,79]# and go left at the 3 directions to #COORDS[30,80]# and kill Grik'nir the Cold for 'The Stolen Journal'.", x = 30, y = 80, zone = "Dun Morogh" },
			[17] = { str = "Return back to #COORDS[25,75]# and turn in 'The Stolen Journal' accept 'Senir's Observations pt.1'", x = 25, y = 75, zone = "Dun Morogh" },
			[18] = { str = "Turn around and Accept 'Scalding Mornbrew Delivery' and hearth." },
			[19] = { str = "Run up into Anvilmar at #COORDS[28,69]# and turn in 'A Refugee's Quandary'.", x = 28, y = 69, zone = "Dun Morogh" },
			[20] = { str = "Go further back and turn in 'Scalding Mornbrew Delivery' accept 'Bring Back the Mug'." },

			[21] = { str = "Talk to your #NPCClass Trainer# to learn new spells and abilities." },
			[22] = { str = "Run right to #COORDS[25,75]#, everything is yellow so nothing will attack you, and turn in 'Bring Back the Mug'.", x = 25, y = 75, zone = "Dun Morogh" },
			[23] = { str = "Head toward the tunnel and turn in 'Senir's Observations pt.1' at #COORDS[33,71]# and accept 'Senir's Observations pt.2'.", x = 33, y = 71, zone = "Dun Morogh" },
			[24] = { str = "You should be about 500 XP from level 6 now." },
			[25] = { str = "About 10 feet away accept 'Supplies to Tannok'." },
		}
	},

-----------6-12 Dun Morogh
	[0612] = {
		title = "6-12 Dun Morogh",
		items = {
			[1] = { str = "6-12 Dun Morogh" },
			[2] = { str = "Go through the tunnel and kill all the stuff on the way. Follow the road to #COORDS[46,53]# in Kharanos and kill stuff on the way until you’re 6. Save your boar ribs and boar meat.", x = 46, y = 53, zone = "Dun Morogh" },
			[3] = { str = "Once at #COORDS[46,53]# turn in 'Senir's Observations pt.2'." },
			[4] = { str = "Up ahead on the right, in front of the Inn, accept 'Beer Basted Boar Ribs'." },
			[5] = { str = "Go in the Inn and turn in 'Supplies to Tannok'." },
			[6] = { str = "Go to the Innkeeper, make it your home and purchase the rhapsody malt for 'Beer Basted Boar Ribs'." },
			[7] = { str = "Talk to your #NPCClass Trainer# to learn new spells and abilities." },
			[8] = { str = "Go across the road from the Inn and accept 'Tools For Steelgrill'." },
			[9] = { str = "Go NE to #COORDS[49,48]# and accept 'Stocking Jetsteam' and 'The Grizzled Den'", x = 49, y = 48, zone = "Dun Morogh" },
			[10] = { str = "Go to the left house and turn in 'Tools For Steelgrill'." },

			[11] = { str = "By the tree out front accept 'Ammo For Rumbleshot'." },
			[12] = { str = "Go to the small camp at #COORDS[44,56]# and open the box for 'Ammo For Rumbleshot'", x = 44, y = 56, zone = "Dun Morogh" },
			[13] = { str = "From around this camp to the SW kill boars and bears until you finish 'Stocking Jetsteam' and 'Beer Basted Boar Ribs'." },
			[14] = { str = "If you’re having trouble finding boars, just go to around #COORDS[40,65]# there is a lot.", x = 40, y = 65, zone = "Dun Morogh" },
			[15] = { str = "Go into the grizzled den at #COORDS[42,54]# and kill wendingos until you get 8 manes for 'The Grizzled Den'", x = 42, y = 54, zone = "Dun Morogh" },
			[16] = { str = "You also wanna head out to #COORDS[40,65]# and turn in 'Ammo For Rumbleshot' watch the scene it’s cool, only if you aren’t time running. You should be 7 or very close now.", x = 40, y = 65, zone = "Dun Morogh" },
			[17] = { str = "Hearth back to Kharanos" },
			[18] = { str = "Just outside the Inn, turn in 'Beer Basted Boar Ribs'." },
			[19] = { str = "Go to the house at #COORDS[45,49]#, NW of the Inn, and accept Operation Recombobulation.", x = 45, y = 49, zone = "Dun Morogh" },
			[20] = { str = "Run NE to #COORDS[49,48]# and turn in 'Stocking Jetsteam' accept 'Evershine'", x = 49, y = 48, zone = "Dun Morogh" },

			[21] = { str = "Turn in 'The Grizzled Den'." },
			[22] = { str = "You should be close to half way through lvl 7." },
			[23] = { str = "Run west to #COORDS[30,45]# and turn in 'Evershine' accept 'A Favor For Evershine' and 'The Perfect Stout'.", x = 30, y = 45, zone = "Dun Morogh" },
			[24] = { str = "Beside him accept 'Bitter Rivals'." },
			[25] = { str = "To the North/NE from here you’ll find tons of bears,leopards, and boars to kill for 'A Favor For Evershine' You should ding 8 while killing for this." },
			[26] = { str = "Kill troll seers and open baskets at #COORDS[41,44]# and #COORDS[41,35]# for 'The Perfect Stout' the drops kinda suck off the trolls but the baskets can be hard to get.", x = 41, y = 44, zone = "Dun Morogh" },
			[27] = { str = "Die so you end up in Kharanos" },
			[28] = { str = "Next to the GY accept 'Frostmane Hold'." },
			[29] = { str = "Go into the Inn and buy a thunder ale off the Innkeeper and down in the basement, give the ale to Jarven Thunderbrew. When he leaves touch the barrel to turn in 'Bitter Rivals' accept 'Return to Marleth'." },
			[30] = { str = "Talk to your #NPCClass Trainer# to learn new spells and abilities." },

			[31] = { str = "Go west to brewnall village again at #COORDS[30,45]# and turn in 'The Perfect Stout' and 'A Favor For Evershine' accept 'Return to Bellowfiz' and 'Shimmer Stout'.", x = 30, y = 45, zone = "Dun Morogh" },
			[32] = { str = "Next to him turn in 'Return to Marleth' you should be past half way to 9 now" },
			[33] = { str = "Go west of brewnall and kill leper gnomes until you complete Operation Recombobulation you should hit 9 getting kills." },
			[34] = { str = "Go to #COORDS[24,50]# and enter the cave kill 5 headhunters.", x = 24, y = 50, zone = "Dun Morogh" },
			[35] = { str = "Explore the cave for 'Frostmane Hold' To explore it just run in and stay to the right, it will curve left and you can see a raised platform with mobs, get near it to complete exploration." },
			[36] = { str = "Either straight down the steps of the Inn, or N of the GY, turn in 'Frostmane Hold' accept 'The Reports'." },
			[37] = { str = "Go NW in the house at #COORDS[45,49]# and turn in Operation Recombobulation.", x = 45, y = 49, zone = "Dun Morogh" },
			[38] = { str = "Go east to #COORDS[49,48]# and turn in 'Return to Bellowfiz' you should be half way to 10 now.", x = 49, y = 48, zone = "Dun Morogh" },
			[39] = { str = "Go North to IF at #COORDS[53,35]#.", x = 53, y = 35, zone = "Dun Morogh" },
			[40] = { str = "Make IF your home at #COORDS[21,55]#.", x = 21, y = 55, zone = "Ironforge" },

			[41] = { str = "Go to #COORDS[39,56]# in IF, behind the bank, in the kings room, turn in 'The Reports'.", x = 39, y = 56, zone = "Ironforge" },
			[42] = { str = "Enter the tram at #COORDS[76,51]#.", x = 76, y = 51, zone = "Ironforge" },
			[43] = { str = "Take the tram down to SW." },
			[44] = { str = "Go to #COORDS[66,62]# and get the FP.", x = 66, y = 62, zone = "Stormwind City" },
			[45] = { str = "Reach goldshire and enter the Inn at #COORDS[42,65]#.", x = 42, y = 65, zone = "Elwynn Forest" },
			[46] = { str = "Just to your left accept 'Kobold Candles'." },
			[47] = { str = "Exit the Inn and go straight out and accept 'The Fargodeep Mine'." },
			[48] = { str = "In the blacksmith house right here accept 'Elmore's Task'." },
			[49] = { str = "Go near the carts at #COORDS[42,67]# and accept 'Gold Dust Exchange'.", x = 42, y = 67, zone = "Elwynn Forest" },
			[50] = { str = "Go south to the Fargodeep Mine at #COORDS[39,82]# and kill the kobold until you complete all 3 quests 'The Fargodeep Mine', 'Gold Dust Exchange', and 'Kobold Candles' Make sure you go in the lower entrance so 'The Fargodeep Mine' is easier.", x = 39, y = 82, zone = "Elwynn Forest" },

			[51] = { str = "Once all 3 are done go to the stonefield farm just up the hill east at #COORDS[34,84]# and accept 'Lost Necklace' SKIP 'Princess Must Die!'.", x = 34, y = 84, zone = "Elwynn Forest" },
			[52] = { str = "Go east to the Maclure Vinyard st #COORDS[43,85]# and turn in 'Lost Necklace' accept 'Pie For Billy' then turn around and kill boars until it’s finished.", x = 43, y = 85, zone = "Elwynn Forest" },
			[53] = { str = "At #COORDS[43,90]# and accept 'Young Lovers'.", x = 43, y = 90, zone = "Elwynn Forest" },
			[54] = { str = "Go back west to #COORDS[34,84]# and turn in 'Pie For Billy' SKIP 'Back to Billy'.", x = 34, y = 84, zone = "Elwynn Forest" },
			[55] = { str = "Go west some to the river at #COORDS[29,85]# and turn in 'Young Lovers' accept 'Speak with Gramma'.", x = 29, y = 85, zone = "Elwynn Forest" },
			[56] = { str = "Go back to #COORDS[34,84]# and turn in 'Speak with Gramma' in the house, accept 'Note to William' You should be 10 now.", x = 34, y = 84, zone = "Elwynn Forest" },
			[57] = { str = "Go back to Goldshire, turn in 'Gold Dust Exchange', accept 'A Fishy Peril' and turn it in. Turn in 'The Fargodeep Mine', skip the followup. Turn in 'Kobold Candles' and 'Note to William', accept 'Shipment to Stormwind'. Run to Stormwind and turn it in" },
			[58] = { str = "Go to #COORDS[52,12]# and turn in 'Elmore's Task', accept 'Stormpike's Delivery'", x = 52, y = 12, zone = "Stormwind City" },
			[59] = { str = "Go into the tram again at #COORDS[63,10]# accept 'Deeprun Rat Roundup' just collect 5 rats and turn it in. You could skip this and keep the flute, It can really piss people off if you play it non stop around the IF bank. SKIP 'Me Brother, Nipsy' unless you go back to SW on the tram because you get crap xp.", x = 63, y = 10, zone = "Stormwind City" },
			[60] = { str = "Back in Dun Morogh, run east to #COORDS[68,55]# and accept 'The Public Servant'.", x = 68, y = 55, zone = "Dun Morogh" },

			[61] = { str = "Go behind him and accept 'Those Blasted Troggs!'." },
			[62] = { str = "Go in the pidd below and kill the troggs here and in the cave for both quests then turn them back in at #COORDS[68,55]#." },
			[63] = { str = "Go east to #COORDS[86,49]# and turn in 'Shimmer Stout', accept the followup, then follow the path into Loch Modan.", x = 86, y = 49, zone = "Dun Morogh" },
			[64] = { str = "Go to #COORDS[22,73]# and accept In Defense of the King's Lands.", x = 22, y = 73, zone = "Loch Modan" },
			[65] = { str = "Go up in the tower and accept The Trogg Threat." },
			[66] = { str = "At #COORDS[33,50]# grab the FP.", x = 33, y = 50, zone = "Loch Modan" },
			[67] = { str = "Look for the wandering NPC Mountaineer Kadrell, turn in 'Stout to Kadrell' and accept 'Rat Catching'." },
			[68] = { str = "Kill troggs from #COORDS[27,53]# and north for In Defense of the King's Lands and The Trogg Threat.", x = 27, y = 53, zone = "Loch Modan" },
			[69] = { str = "Kill mobs from #COORDS[26,43]# and north for Rat Catching, then turn it in at Thelsamar at Mountaineer Kadrell, accept 'Mountaineer Stormpike's Task'.", x = 26, y = 43, zone = "Loch Modan" },
			[70] = { str = "Go back to #COORDS[22,73]# and turn in In Defense of the King's Lands and The Trogg Threat.", x = 22, y = 73, zone = "Loch Modan" },

			[71] = { str = "Go north to the tower at #COORDS[24,18]# and turn in 'Stormpike's Delivery' and 'Mountaineer Stormpike's Task'.", x = 24, y = 18, zone = "Loch Modan" },
			[72] = { str = "You should be 12 now or close to it. You can grind if you’d like but it doesn’t matter much. Follow the Night Elf to IF guide but just go backwards. You’re going to go north through the wetlands to menethil, then boat to auberdine from here." },
		}
	},
}
