Table_002_Teldrassil = {
-----------1-6 Teldrassil
	[0106] = {
		title = "1-6 Teldrassil",
		items = {
			[1] = { str = "Welcome to Azeroth, friend! \nThis section of the VanillaGuide will guide you through levels 1 to 6 in #A_Teldrassil#" },
			[2] = { str = "Accept #Q_'The Balance of Nature'# at #C_[58,44]# and go do it by killing mobs at #C_[57,45]# and #C_[61,43]#. Turn it in at #C_[58,44]#.", x = 58, y = 44, zone = "Teldrassil" },
			[3] = { str = "Accept #Q_'The Balance of Nature'#(2) and Etched Sigil at #C_[58,44]#. #Q_'The Woodland Protector'# at #C_[59,42]# and #Q_'A Good Friend'# at #C_[60,41]#.", x = 59, y = 42, zone = "Teldrassil" },
			[4] = { str = "Hand in #Q_'The Woodland Protector'# at #C_[57,45]# and accept #Q_'The Woodland Protector'#(2) Mobs are at #C_[56,46]#. Turn it in at #C_[57,45]#.", x = 56, y = 46, zone = "Teldrassil" },
			[5] = { str = "Accept #Q_'Webwood Venom'# at #C_[57,41]#.", x = 57, y = 41, zone = "Teldrassil" },
			[6] = { str = "Run up the ramp to the top of the tree, turn in Etched Sigil at #C_[58,40]# (hunter trainer) and get beast tracking.", x = 58, y = 40, zone = "Teldrassil" },
			[7] = { str = "Jump down and go do the following #Q_'The Balance of Nature'#(2) mobs are all around #C_[60,35]#.", x = 60, y = 35, zone = "Teldrassil" },
			[8] = { str = "#Q_'Webwood Venom'# at #C_[57,32]# in and outside the cave.", x = 57, y = 32, zone = "Teldrassil" },
			[9] = { str = "Turn in #Q_'A Good Friend'# at #C_[54,32]# in a cove just west of the cave. Accept #Q_'A Friend in Need'#.", x = 54, y = 32, zone = "Teldrassil" },
			[10] = { str = "Turn in #Q_'Webwood Venom'# at #C_[57,41]#. Accept #Q_'Webwood Egg'#.", x = 57, y = 41, zone = "Teldrassil" },

			[11] = { str = "Turn in #Q_'The Balance of Nature'#(2) at #C_[58,44]#.", x = 58, y = 44, zone = "Teldrassil" },
			[12] = { str = "Turn in #Q_'A Friend in Need'# at #C_[60,41]#, accept #Q_'Iverron’s Antidote'#.", x = 60, y = 41, zone = "Teldrassil" },
			[13] = { str = "#Q_'Iverron’s Antidote'# (lilies and mushrooms) around #C_[57,37]#.", x = 57, y = 37, zone = "Teldrassil" },
			[14] = { str = "#Q_'Iverron’s Antidote'# (ichor) in the cave #C_[57,32]# along with #Q_'Webwood Egg'# at #C_[56,26]#.", x = 57, y = 32, zone = "Teldrassil" },
			[15] = { str = "Turn in #Q_'Webwood Egg'# at #C_[57,41]# Accept #Q_'Tenaron’s Summons'# then Run up the ramp to the top of the tree and hand it in at #C_[59,39]#. Accept #Q_'Crown of the Earth'#.", x = 57, y = 41, zone = "Teldrassil" },
			[16] = { str = "Turn in #Q_'Iverron’s Antidote'# accept #Q_'Iverron’s Antidote'#(2)." },
			[17] = { str = "Do #Q_'Crown of the Earth'# at #C_[59,32]#.", x = 59, y = 32, zone = "Teldrassil" },
			[18] = { str = "Turn in #Q_'Iverron’s Antidote'#(2) at #C_[54,32]#.", x = 54, y = 32, zone = "Teldrassil" },
			[19] = { str = "Turn in #Q_'Crown of the Earth'# at #C_[59,39]# Accept #Q_'Crown of the Earth'#(2).", x = 59, y = 39, zone = "Teldrassil" },
			[20] = { str = "If you’re not level 6 yet, you should be close. Level up and talk to your #N_Class Trainer# to learn new spells and abilities. Head towards #A_Dolanaar# (#A_Teldrassil#)." },
		}
	},

-----------6-12 Teldrassil
	[0612] = {
		title = "6-12 Teldrassil",
		items = {
			[1] = { str = "Welcome to Azeroth, friend! \nThis section of the VanillaGuide will guide you through levels 6 to 12 in #A_Teldrassil#." },
			[2] = { str = "Accept #Q_'Dolanaar Delivery'# at #C_[61,47]#.", x = 61, y = 47, zone = "Teldrassil" },
			[3] = { str = "Accept #Q_'Zenn’s Bidding'# at #C_[60,56]#.", x = 60, y = 56, zone = "Teldrassil" },
			[4] = { str = "Talk to the #N_Innkeeper# to make #A_Dolanaar# (#A_Teldrassil#) your home." },
			[5] = { str = "Turn in #Q_'Dolanaar Delivery'# at #C_[55,59]# in #A_Dolanaar# (#A_Teldrassil#).", x = 55, y = 59, zone = "Teldrassil" },
			[6] = { str = "Turn in #Q_'Crown of the Earth'#(2) at #C_[56,61]# accept #Q_'Crown of the Earth'#(3).", x = 56, y = 61, zone = "Teldrassil" },
			[7] = { str = "At the tower in #A_Dolanaar# (#A_Teldrassil#) grab the following." },
			[8] = { str = "#Q_'Denalan’s Earth'# #Q_'A Troubling Breeze'# Get First Aid #Q_'The Emerald Dreamcatcher'# #Q_'Twisted Hatred'#." },
			[9] = { str = "Accept #Q_'The Road to Darnassus'# from the mounted patrol (if she’s there) right around #C_[56,57]#.", x = 56, y = 57, zone = "Teldrassil" },
			[10] = { str = "#Q_'Zenn’s Bidding'# mobs east of #A_Dolanaar# (#A_Teldrassil#)." },

			[11] = { str = "#Q_'Crown of the Earth'#(3) at #C_[63,58]#.", x = 63, y = 58, zone = "Teldrassil" },
			[12] = { str = "Turn in #Q_'A Troubling Breeze'# at #C_[66,58]# accept #Q_'Gnarlpine Corruption'#.", x = 66, y = 58, zone = "Teldrassil" },
			[13] = { str = "#Q_'The Emerald Dreamcatcher'# #C_[68,59]#.", x = 68, y = 59, zone = "Teldrassil" },
			[14] = { str = "Turn in #Q_'Zenn’s Bidding'# at #C_[60,56]# then go to the Dolanaar tower and get #Q_'Seek Redemption!'#", x = 60, y = 56, zone = "Teldrassil" },
			[15] = { str = "Do #Q_'Seek Redemption!'# (cones under trees) while heading to #C_[60,68]# and turn in #Q_'Denalan’s Earth'#.", x = 60, y = 68, zone = "Teldrassil" },
			[16] = { str = "Accept and do #Q_'Timberling Seeds'# (mobs all around lake) & #Q_'Timberling Sprouts'# (seeds around trees near lake)." },
			[17] = { str = "Hand those back in and accept #Q_'Rellian Greenspyre'#." },
			[18] = { str = "Turn in #Q_'Crown of the Earth'#(3) accept #Q_'Crown of the Earth'#(4)." },
			[19] = { str = "Turn in #Q_'Gnarlpine Corruption'# accept #Q_'The Relics of Wakening'#." },
			[20] = { str = "Turn in #Q_'The Emerald Dreamcatcher'# accept #Q_'Ferocitas the Dream Eater'#." },

			[21] = { str = "You should be 8 by now. Talk to your #N_Class Trainer# to learn new spells and abilities." },
			[22] = { str = "Finish #Q_'Seek Redemption!'# Then go North of Starbreeze." },
			[23] = { str = "Do #Q_'Ferocitas the Dream Eater'# mobs around #C_[68,53]#.", x = 68, y = 53, zone = "Teldrassil" },
			[24] = { str = "Die on purpose so you end up at #A_Dolanaar# (#A_Teldrassil#)." },
			[25] = { str = "Run to Fel Rock Cave at #C_[54,52]# and do #Q_'Twisted Hatred'# you can also wait until you’re 10 to do this. Makes it easier.", x = 54, y = 52, zone = "Teldrassil" },
			[26] = { str = "Turn in #Q_'Ferocitas the Dream Eater'# & #Q_'Twisted Hatred'# at #A_Dolanaar# (#A_Teldrassil#)." },
			[27] = { str = "Do #Q_'The Road to Darnassus'# at #C_[46,52]#.", x = 46, y = 52, zone = "Teldrassil" },
			[28] = { str = "Go do #Q_'The Relics of Wakening'# at #C_[44,57]# in the cave.", x = 44, y = 57, zone = "Teldrassil" },
			[29] = { str = "Accept #Q_'The Sleeping Druid'# inside, kill shamans to get it, turn it in." },
			[30] = { str = "Accept #Q_'Druid of the Claw'# do it at #C_[45,58]#.", x = 45, y = 58, zone = "Teldrassil" },

			[31] = { str = "Go south and do #Q_'Crown of the Earth'#(4) at #C_[42,67]#.", x = 42, y = 67, zone = "Teldrassil" },
			[32] = { str = "Die so you end up at #A_Dolanaar# (#A_Teldrassil#)." },
			[33] = { str = "Turn in #Q_'Crown of the Earth'#(4) accept #Q_'Crown of the Earth'#(5)." },
			[34] = { str = "Turn in #Q_'The Road to Darnassus'# just west of tower to mountie." },
			[35] = { str = "Turn in #Q_'The Relics of Wakening'# accept #Q_'Ursal the Mauler'#." },
			[36] = { str = "You should be 10 now, if not grind to it." },
			[37] = { str = "Run to #A_Darnassus# Hand in #Q_'Rellian Greenspyre'# at #C_[38,21]#- Accept #Q_'Tumors'#.", x = 38, y = 21, zone = "Teldrassil" },
			[38] = { str = "Get #Q_'Nessa Shadowsong'# at #C_[70,45]# in #A_Darnassus#.", x = 70, y = 45, zone = "Teldrassil" },
			[39] = { str = "Get #Q_'The Glowing Fruit'# at #C_[42,76]#.", x = 42, y = 76, zone = "Teldrassil" },
			[40] = { str = "Do #Q_'Ursal the Mauler'# at #C_[38,77]#.", x = 38, y = 77, zone = "Teldrassil" },

			[41] = { str = "Die so you’re in front of #A_Darnassus#." },
			[42] = { str = "#Q_'Tumors'# at #C_[42,42]#.", x = 42, y = 42, zone = "Teldrassil" },
			[43] = { str = "#Q_'Crown of the Earth'#(5) at #C_[38,34]#.", x = 38, y = 34, zone = "Teldrassil" },
			[44] = { str = "Accept #Q_'The Enchanted Glade'# at #C_[38,34]#. Then do it at #C_[35,43]#. Turn it back in.", x = 38, y = 34, zone = "Teldrassil" },
			[45] = { str = "Accept #Q_'Teldrassil'#." },
			[46] = { str = "Run back to #A_Darnassus#, turn in #Q_'Tumors'# at #C_[38,21]# accept #Q_'Return to Denalan'#.", x = 38, y = 21, zone = "Teldrassil" },
			[47] = { str = "Turn in #Q_'Teldrassil'# atop the tower at #C_[36,12]# accept #Q_'Grove of the Ancients'#.", x = 36, y = 12, zone = "Teldrassil" },
			[48] = { str = "Use your #I_[Hearthstone]# to return to #A_Dolanaar# (#A_Teldrassil#)." },
			[49] = { str = "Hand in #Q_'Crown of the Earth'#(5) accept #Q_'Crown of the Earth'#(6)." },
			[50] = { str = "Turn in #Q_'Ursal the Mauler'#." },

			[51] = { str = "Go SE to #C_[60,68]# Turn in #Q_'Return to Denalan'# accept #Q_'Oakenscowl Elite'#.", x = 60, y = 68, zone = "Teldrassil" },
			[52] = { str = "Turn in #Q_'The Glowing Fruit'#." },
			[53] = { str = "Go kill Oakenscowl at #C_[53,74]#. Turn it in at #C_[60,68]#.", x = 53, y = 74, zone = "Teldrassil" },
			[54] = { str = "Run to #A_Darnassus#, if you’re not within 1100xp to 12 yet grind on harpies North of the #A_Darnassus# entrance." },
			[55] = { str = "Turn in #Q_'Crown of the Earth'#(6) #C_[34,8]# in #A_Darnassus#.", x = 34, y = 8, zone = "Darnassus" },
			[56] = { str = "Talk to your #N_Class Trainer# to learn new spells and abilities and run through gate at #C_[30,41]#.", x = 30, y = 41, zone = "Darnassus" },
			[57] = { str = "Run straight ahead to #C_[56,92]#, hand in #Q_'Nessa Shadowsong'# accept #Q_'The Bounty of Teldrassil'# go hand it in to the hippograph guy at #C_[58,93]# to get a free ride and start #Q_'Flight to Auberdine'#.", x = 56, y = 92, zone = "Teldrassil" },
 		}
	},
}
