Table_002_DunMorogh = {
-----------1-6 Coldridge Valley
	[0106] = {
		title = "1-6 Coldridge Valley",
		items = {
			[1] = { str = "Welcome to Azeroth, friend! \nThis section of the VanillaGuide will guide you through levels 1 to 6 in #A_Coldridge Valley#." },
			[2] = { str = "Right in front of where you start accept #Q_'Dwarven Outfitters'#." },
			[3] = { str = "Go south around #C_[28,73]# and kill wolves for the meat then go back to #C_[29,71]# and turn in #Q_'Dwarven Outfitters'# then accept Encrypted Rune and #Q_'Coldridge Valley Mail Delivery'#.", x = 29, y = 71, zone = "Dun Morogh" },
			[4] = { str = "To your left accept #Q_'A New Threat'#." },
			[5] = { str = "At #C_[30,74]# kill burly troggs and at #C_[26,72]# there is a camp of rockjaw troggs, kill them for #Q_'A New Threat'#.", x = 26, y = 72, zone = "Dun Morogh" },
			[6] = { str = "Go back to #C_[29,71]# and turn in #Q_'A New Threat'# you should be 3 now.", x = 29, y = 71, zone = "Dun Morogh" },
			[7] = { str = "Go in Anvilmar at #C_[28,69]# and turn in your classes skill npc quest which was Encrypted Rune for a rogue.", x = 28, y = 69, zone = "Dun Morogh" },
			[8] = { str = "Accept #Q_'A Refugee’s Quandary'# inside." },
			[9] = { str = "Follow the road south to #C_[22,71]# and turn in #Q_'Coldridge Valley Mail Delivery'# accept #Q_'Coldridge Valley Mail Delivery'#(2) and #Q_'The Boar Hunter'#.", x = 22, y = 71, zone = "Dun Morogh" },
			[10] = { str = "Just behind him start killing small boars until you have 12 for #Q_'The Boar Hunter'# then go back to #C_[22,71]# and turn it in." },

			[11] = { str = "At #C_[20,76]# clear the front of the tent and grab #I_[Felix’s Box]# for #Q_'A Refugee’s Quandary'#.", x = 20, y = 76, zone = "Dun Morogh" },
			[12] = { str = "At #C_[22,80]# clear in front of the tent and grab #I_[Felix’s Chest]# for #Q_'A Refugee’s Quandary'#.", x = 22, y = 80, zone = "Dun Morogh" },
			[13] = { str = "Run up to #C_[25,75]# (it’s the end of the road on the map) and turn in #Q_'Coldridge Valley Mail Delivery'#(2) and accept #Q_'The Troll Cave'#.", x = 25, y = 75, zone = "Dun Morogh" },
			[14] = { str = "At #C_[26,79]# clear in front of the cave and grab #I_[Felix’s Bucket of Bolts]# for #Q_'A Refugee’s Quandary'# then kill the trolls in and out of it until you complete #Q_'The Troll Cave'#.", x = 26, y = 79, zone = "Dun Morogh" },
			[15] = { str = "Run back up to #C_[25,75]# and turn in #Q_'The Troll Cave'# accept #Q_'The Stolen Journal'# you should be 5 or very close to it now.", x = 25, y = 75, zone = "Dun Morogh" },
			[16] = { str = "Go back in the cave at #C_[26,79]# and go left at the 3 directions to #C_[30,80]# and kill Grik’nir the Cold for #Q_'The Stolen Journal'#.", x = 30, y = 80, zone = "Dun Morogh" },
			[17] = { str = "Return back to #C_[25,75]# and turn in #Q_'The Stolen Journal'# accept #Q_'Senir’s Observations'#.", x = 25, y = 75, zone = "Dun Morogh" },
			[18] = { str = "Turn around and accept #Q_'Scalding Mornbrew Delivery'# and use your #I_[Hearthstone]#." },
			[19] = { str = "Run up into Anvilmar at #C_[28,69]# and turn in #Q_'A Refugee’s Quandary'#.", x = 28, y = 69, zone = "Dun Morogh" },
			[20] = { str = "Go further back and turn in #Q_'Scalding Mornbrew Delivery'#. Accept #Q_'Bring Back the Mug'#." },

			[21] = { str = "Talk to your #N_Class Trainer# to learn new spells and abilities." },
			[22] = { str = "Run right to #C_[25,75]#, everything is yellow so nothing will attack you, and turn in #Q_'Bring Back the Mug'#.", x = 25, y = 75, zone = "Dun Morogh" },
			[23] = { str = "Head toward the tunnel and turn in #Q_'Senir’s Observations'# at #C_[33,71]# and accept #Q_'Senir’s Observations'#(2).", x = 33, y = 71, zone = "Dun Morogh" },
			[24] = { str = "You should be about 500 XP from level 6 now." },
			[25] = { str = "About 10 feet away accept #Q_'Supplies to Tannok'#." },
		}
	},

-----------6-12 Dun Morogh
	[0612] = {
		title = "6-12 Dun Morogh",
		items = {
			[1] = { str = "Welcome to Azeroth, friend! \nThis section of the VanillaGuide will guide you through levels 6 to 12 in #A_Dun Morogh#." },
			[2] = { str = "Go through the tunnel and kill all the stuff on the way. Follow the road to #C_[46,53]# in #A_Kharanos# (#A_Dun Morogh#) and kill stuff on the way until you’re 6. Save your boar ribs and boar meat.", x = 46, y = 53, zone = "Dun Morogh" },
			[3] = { str = "Once at #C_[46,53]# turn in #Q_'Senir’s Observations'#(2)." },
			[4] = { str = "Up ahead on the right, in front of the Inn, accept #Q_'Beer Basted Boar Ribs'#." },
			[5] = { str = "Go in the Inn and turn in #Q_'Supplies to Tannok'#." },
			[6] = { str = "Talk to the #N_Innkeeper# to make #A_Kharanos# (#A_Dun Morogh#) your home. Purchase the #I_[Rhapsody Malt]# for #Q_'Beer Basted Boar Ribs'#." },
			[7] = { str = "Talk to your #N_Class Trainer# to learn new spells and abilities." },
			[8] = { str = "Go across the road from the Inn and accept #Q_'Tools For Steelgrill'#." },
			[9] = { str = "Go NE to #C_[49,48]# and accept #Q_'Stocking Jetsteam'# and #Q_'The Grizzled Den'#.", x = 49, y = 48, zone = "Dun Morogh" },
			[10] = { str = "Go to the left house and turn in #Q_'Tools For Steelgrill'#." },

			[11] = { str = "By the tree out front accept #Q_'Ammo For Rumbleshot'#." },
			[12] = { str = "Go to the small camp at #C_[44,56]# and open the box for #Q_'Ammo For Rumbleshot'#.", x = 44, y = 56, zone = "Dun Morogh" },
			[13] = { str = "From around this camp to the SW kill boars and bears until you finish #Q_'Stocking Jetsteam'# and #Q_'Beer Basted Boar Ribs'#." },
			[14] = { str = "If you’re having trouble finding boars, just go to around #C_[40,65]# there is a lot.", x = 40, y = 65, zone = "Dun Morogh" },
			[15] = { str = "Go into the grizzled den at #C_[42,54]# and kill wendingos until you get 8 manes for #Q_'The Grizzled Den'#.", x = 42, y = 54, zone = "Dun Morogh" },
			[16] = { str = "You also wanna head out to #C_[40,65]# and turn in #Q_'Ammo For Rumbleshot'# watch the scene it’s cool, only if you aren’t time running. You should be 7 or very close now.", x = 40, y = 65, zone = "Dun Morogh" },
			[17] = { str = "Use your #I_[Hearthstone]# to return to #A_Kharanos# (#A_Dun Morogh#)." },
			[18] = { str = "Just outside the Inn, turn in #Q_'Beer Basted Boar Ribs'#." },
			[19] = { str = "Go to the house at #C_[45,49]#, NW of the Inn, and accept #Q_'Operation Recombobulation'#.", x = 45, y = 49, zone = "Dun Morogh" },
			[20] = { str = "Run NE to #C_[49,48]# and turn in #Q_'Stocking Jetsteam'# accept #Q_'Evershine'#.", x = 49, y = 48, zone = "Dun Morogh" },

			[21] = { str = "Turn in #Q_'The Grizzled Den'#." },
			[22] = { str = "You should be close to half way through lvl 7." },
			[23] = { str = "Run west to #C_[30,45]# and turn in #Q_'Evershine'# accept #Q_'A Favor For Evershine'# and #Q_'The Perfect Stout'#.", x = 30, y = 45, zone = "Dun Morogh" },
			[24] = { str = "Beside him accept #Q_'Bitter Rivals'#." },
			[25] = { str = "To the North/NE from here you’ll find tons of bears,leopards, and boars to kill for #Q_'A Favor For Evershine'# You should ding 8 while killing for this." },
			[26] = { str = "Kill troll seers and open baskets at #C_[41,44]# and #C_[41,35]# for #Q_'The Perfect Stout'# the drops kinda suck off the trolls but the baskets can be hard to get.", x = 41, y = 44, zone = "Dun Morogh" },
			[27] = { str = "Die so you end up in #A_Kharanos# (#A_Dun Morogh#)." },
			[28] = { str = "Next to the #A_Graveyard# accept #Q_'Frostmane Hold'#." },
			[29] = { str = "Go into the Inn and buy a #I_[Thunder Ale]# off the Innkeeper and down in the basement, give the ale to #N_[Jarven Thunderbrew]#. When he leaves touch the barrel to turn in #Q_'Bitter Rivals'# accept #Q_'Return to Marleth'#." },
			[30] = { str = "Talk to your #N_Class Trainer# to learn new spells and abilities." },

			[31] = { str = "Go west to #A_Brewnall Village# (#A_Dun Morogh#) again at #C_[30,45]# and turn in #Q_'The Perfect Stout'# and #Q_'A Favor For Evershine'# accept #Q_'Return to Bellowfiz'# and #Q_'Shimmer Stout'#.", x = 30, y = 45, zone = "Dun Morogh" },
			[32] = { str = "Next to him turn in #Q_'Return to Marleth'# you should be past half way to 9 now." },
			[33] = { str = "Go west of #A_Brewnall Village# (#A_Dun Morogh#) and kill leper gnomes until you complete #Q_'Operation Recombobulation'# you should hit 9 getting kills." },
			[34] = { str = "Go to #C_[24,50]# and enter the cave kill 5 headhunters.", x = 24, y = 50, zone = "Dun Morogh" },
			[35] = { str = "Explore the cave for #Q_'Frostmane Hold'# To explore it just run in and stay to the right, it will curve left and you can see a raised platform with mobs, get near it to complete exploration." },
			[36] = { str = "Either straight down the steps of the Inn, or N of the #A_Graveyard#, turn in #Q_'Frostmane Hold'# accept #Q_'The Reports'#." },
			[37] = { str = "Go NW in the house at #C_[45,49]# and turn in #Q_'Operation Recombobulation'#.", x = 45, y = 49, zone = "Dun Morogh" },
			[38] = { str = "Go east to #C_[49,48]# and turn in #Q_'Return to Bellowfiz'# you should be half way to 10 now.", x = 49, y = 48, zone = "Dun Morogh" },
			[39] = { str = "Go North to #A_Ironforge# at #C_[53,35]#.", x = 53, y = 35, zone = "Dun Morogh" },
			[40] = { str = "Talk to the #N_Innkeeper# to make #A_Ironforge# your home at #C_[21,55]#.", x = 21, y = 55, zone = "Ironforge" },

			[41] = { str = "Go to #C_[39,56]# in #A_Ironforge#, behind the bank, in the kings room, turn in #Q_'The Reports'#.", x = 39, y = 56, zone = "Ironforge" },
			[42] = { str = "Enter the tram at #C_[76,51]#.", x = 76, y = 51, zone = "Ironforge" },
			[43] = { str = "Take the tram down to #A_Stormwind#." },
			[44] = { str = "Unlock the flight path by talking to the #N_Flight Master# at #C_[66,62]#.", x = 66, y = 62, zone = "Stormwind City" },
			[45] = { str = "Reach #A_Goldshire# (#A_Elwynn Forest#) and enter the Inn at #C_[42,65]#.", x = 42, y = 65, zone = "Elwynn Forest" },
			[46] = { str = "Just to your left accept #Q_'Kobold Candles'#." },
			[47] = { str = "Exit the Inn and go straight out and accept #Q_'The Fargodeep Mine'#." },
			[48] = { str = "In the blacksmith house right here accept #Q_'Elmore’s Task'#." },
			[49] = { str = "Go near the carts at #C_[42,67]# and accept #Q_'Gold Dust Exchange'#.", x = 42, y = 67, zone = "Elwynn Forest" },
			[50] = { str = "Go south to the #A_Fargodeep Mine# at #C_[39,82]# and kill the kobold until you complete all 3 quests #Q_'The Fargodeep Mine'#, #Q_'Gold Dust Exchange'#, and #Q_'Kobold Candles'# Make sure you go in the lower entrance so #Q_'The Fargodeep Mine'# is easier.", x = 39, y = 82, zone = "Elwynn Forest" },

			[51] = { str = "Once all 3 are done go to the stonefield farm just up the hill east at #C_[34,84]# and accept #Q_'Lost Necklace'# SKIP #Q_'Princess Must Die!'#.", x = 34, y = 84, zone = "Elwynn Forest" },
			[52] = { str = "Go east to the #A_Maclure Vinyard# at #C_[43,85]# and turn in #Q_'Lost Necklace'# accept #Q_'Pie For Billy'# then turn around and kill boars until it’s finished.", x = 43, y = 85, zone = "Elwynn Forest" },
			[53] = { str = "At #C_[43,90]# and accept #Q_'Young Lovers'#.", x = 43, y = 90, zone = "Elwynn Forest" },
			[54] = { str = "Go back west to #C_[34,84]# and turn in #Q_'Pie For Billy'# SKIP #Q_'Back to Billy'#.", x = 34, y = 84, zone = "Elwynn Forest" },
			[55] = { str = "Go west some to the river at #C_[29,85]# and turn in #Q_'Young Lovers'# accept #Q_'Speak with Gramma'#.", x = 29, y = 85, zone = "Elwynn Forest" },
			[56] = { str = "Go back to #C_[34,84]# and turn in #Q_'Speak with Gramma'# in the house, accept #Q_'Note to William'# You should be 10 now.", x = 34, y = 84, zone = "Elwynn Forest" },
			[57] = { str = "Go back to #A_Goldshire# (#A_Elwynn Forest#), turn in #Q_'Gold Dust Exchange'#, accept #Q_'A Fishy Peril'# and turn it in. Turn in #Q_'The Fargodeep Mine'#, skip the followup. Turn in #Q_'Kobold Candles'# and #Q_'Note to William'#, accept #Q_'Shipment to Stormwind'#. Run to #A_Stormwind# and turn it in." },
			[58] = { str = "Go to #C_[52,12]# and turn in #Q_'Elmore’s Task'#, accept #Q_'Stormpike’s Delivery'#.", x = 52, y = 12, zone = "Stormwind City" },
			[59] = { str = "Go into the tram again at #C_[63,10]# accept #Q_'Deeprun Rat Roundup'# just collect 5 rats and turn it in. You could skip this and keep the flute, It can really piss people off if you play it non stop around the #A_Ironforge# bank. SKIP #Q_'Me Brother, Nipsy'# unless you go back to #A_Stormwind# on the tram because you get crap xp.", x = 63, y = 10, zone = "Stormwind City" },
			[60] = { str = "Back in #A_Dun Morogh#, run east to #C_[68,55]# and accept #Q_'The Public Servant'#.", x = 68, y = 55, zone = "Dun Morogh" },

			[61] = { str = "Go behind him and accept #Q_'Those Blasted Troggs!'#." },
			[62] = { str = "Go in the pit below and kill the troggs here and in the cave for both quests then turn them back in at #C_[68,55]#." },
			[63] = { str = "Go east to #C_[86,49]# and turn in #Q_'Shimmer Stout'#, accept the followup, then follow the path into #A_Loch Modan#.", x = 86, y = 49, zone = "Dun Morogh" },
			[64] = { str = "Go to #C_[22,73]# and accept #Q_'In Defense of the King’s Lands'#.", x = 22, y = 73, zone = "Loch Modan" },
			[65] = { str = "Go up in the tower and accept #Q_'The Trogg Threat'#." },
			[66] = { str = "Unlock the flight path by talking to the #N_Flight Master# at #C_[33,50]#.", x = 33, y = 50, zone = "Loch Modan" },
			[67] = { str = "Look for the wandering #N_Mountaineer Kadrell#, turn in #Q_'Stout to Kadrell'# and accept #Q_'Rat Catching'#." },
			[68] = { str = "Kill troggs from #C_[27,53]# and north for #Q_'In Defense of the King’s Lands'# and #Q_'The Trogg Threat'#.", x = 27, y = 53, zone = "Loch Modan" },
			[69] = { str = "Kill mobs from #C_[26,43]# and north for #Q_'Rat Catching'#, then turn it in at #A_Thelsamar# (#A_Loch Modan#) at #N_Mountaineer Kadrell#, accept #Q_'Mountaineer Stormpike’s Task'#.", x = 26, y = 43, zone = "Loch Modan" },
			[70] = { str = "Go back to #C_[22,73]# and turn in #Q_'In Defense of the King’s Lands'# and #Q_'The Trogg Threat'#.", x = 22, y = 73, zone = "Loch Modan" },

			[71] = { str = "Go north to the tower at #C_[24,18]# and turn in #Q_'Stormpike’s Delivery'# and #Q_'Mountaineer Stormpike’s Task'#.", x = 24, y = 18, zone = "Loch Modan" },
			[72] = { str = "You should be 12 now or close to it. You can grind if you’d like but it doesn’t matter much. Follow the Night Elf to #A_Ironforge# guide but just go backwards. You’re going to go north through the #A_Wetlands# to #A_Menethil Harbor# (#A_The Wetlands#), then boat to #A_Auberdine# (#A_Darkshore#) from here." },
		}
	},
}
