Table_003_Alliance_12to20 = {
-----------12-14 Darkshore
	[1214] = {
		title = "12-14 Darkshore",
		items = {
			[1] = { str = "12-14 Darkshore" },
			[2] = { str = "Once you land grab Washed Ashore pt.1 right in front of you at #COORDS[37,46]#.", x = 37, y = 46, zone = "Darkshore" },
			[3] = { str = "Turn in Flight to Auberdine accept Return to Nessa I fly back to darnassus to get it done. She’s right off the edge of the dock." },
			[4] = { str = "Make Auberdine your home. Run out on the docks of Auberdine grab For Love Eternal at #COORDS[35,43]#.", x = 35, y = 43, zone = "Darkshore" },
			[5] = { str = "Go upstairs accept Buzzbox 827." },
			[6] = { str = "Accept Cave Mushrooms in front of the Inn." },
			[7] = { str = "Grab The Red Crystal near the bridge." },
			[8] = { str = "Buy some 6 slot bags if you haven’t found 3 by now at #COORDS[37,40]# then grab Bashal'Aran pt.1 and Tools of the Highborne.", x = 37, y = 40, zone = "Darkshore" },
			[9] = { str = "Go south over the bridge, grab Plagued Lands." },
			[10] = { str = "Run inside, grab How Big a Threat? pt.1." },

			[11] = { str = "Go do Washed Ashore pt.1 at #COORDS[36,50]# grind from town to there to get Crawler legs for Buzzbox 827.", x = 36, y = 50, zone = "Darkshore" },
			[12] = { str = "Turn in Buzzbox 827 at #COORDS[36,46]# accept Buzzbox 411.", x = 36, y = 46, zone = "Darkshore" },
			[13] = { str = "Turn in Washed Ashore pt.1 accept Washed Ashore pt.2." },
			[14] = { str = "Do Washed Ashore pt.2 at #COORDS[31,46]# in the water west of boat dock. Turn it in.", x = 31, y = 46, zone = "Darkshore" },
			[15] = { str = "Buzzbox 411 Threshers look like loch ness in the water, Turn it in at #COORDS[41,28]# accept Buzzbox 323.", x = 41, y = 28, zone = "Darkshore" },
			[16] = { str = "Stop at #COORDS[42,32]# accept Beached Sea Creature.", x = 42, y = 32, zone = "Darkshore" },
			[17] = { str = "Bashal'Aran pt.1 at #COORDS[44,36]# grinding along the way, accept Bashal'Aran pt.2 killing grells around him for earrings.", x = 44, y = 36, zone = "Darkshore" },
			[18] = { str = "Turn in Bashal'Aran pt.2 at #COORDS[44,36]# accept Bashal’Aran pt.3.", x = 44, y = 36, zone = "Darkshore" },
			[19] = { str = "Do Bashal’Aran pt.3 by killing satyr’s and turn it in accept Bashal’Aran pt.4." },
			[20] = { str = "Grind to #COORDS[47,48]# and do The Red Crystal.", x = 47, y = 48, zone = "Darkshore" },

			[21] = { str = "Grind to #COORDS[40,53]# to find the camp for How Big a Threat? pt.1.", x = 40, y = 53, zone = "Darkshore" },
			[22] = { str = "Run down to Ameth’Aran at #COORDS[40,59]# and accept The Fall of Ameth'Aran do it at #COORDS[43,58]# and #COORDS[42,63]#.", x = 40, y = 59, zone = "Darkshore" },
			[23] = { str = "Do Tools of the Highborne while in here, killing mobs for them." },
			[24] = { str = "Do For Love Eternal at #COORDS[41,58]# she’s lvl 16 but easy.", x = 41, y = 58, zone = "Darkshore" },
			[25] = { str = "Do Bashal’Aran pt.4 at #COORDS[42,61]#.", x = 42, y = 61, zone = "Darkshore" },
			[26] = { str = "Turn in The Fall of Ameth'Aran at #COORDS[40,59]#.", x = 40, y = 59, zone = "Darkshore" },
			[27] = { str = "To the west of Amath’Aran do Plagued Lands." },
			[28] = { str = "Hearth back to Auberdine Turn in Plagued Lands at the first house accept Cleansing the Infected." },
			[29] = { str = "Go inside hand in How Big a Threat? pt.1 accept How Big a Threat? Pt.2." },
			[30] = { str = "Accept Thundris Windweaver." },

			[31] = { str = "Go Upstairs accept The Tower of Althalaxx pt.1." },
			[32] = { str = "Don’t do Deep Ocean, Vast Sea it’s not worth it and too hard." },
			[33] = { str = "Go in the merchant house, turn in Tools of the Highborne." },
			[34] = { str = "Turn in Thundris Windweaver accept The Cliffspring River." },
			[35] = { str = "Turn in The Red Crystal near the Inn accept As Water Cascades." },
			[36] = { str = "Fill the Vial in the Moonwell for As Water Cascades." },
			[37] = { str = "Accept WANTED: Murkdeep! in front of the Inn (lvl 15 quest now)." },
			[38] = { str = "Turn in For Love Eternal on the dock. Watch the love story." },
			[39] = { str = "You should be 14 by now. Talk to your #NPCClass Trainer# in Darnassus to learn new spells and abilities. Be sure to accept the quest Trouble In Darkshore? from Chief Archaeologist Greywhisker at #COORDS[31,84]#.", x = 31, y = 84, zone = "Darnassus" },
		}
	},

-----------14-17 Darkshore
	[1417] = {
		title = "14-17 Darkshore",
		items = {
			[1] = { str = "14-17 Darkshore" },
			[2] = { str = "Go back to Darkshore. Turn in Trouble In Darkshore? at #COORDS[37,42]#. Then turn in Bashal’Aran pt.4 at #COORDS[44,36]#.", x = 44, y = 36, zone = "Darkshore" },
			[3] = { str = "Kill Moonstalkers and Rabid Thistle Bears all around #COORDS[48,30]# while you head to #COORDS[50,25]# for The Cliffspring River.", x = 50, y = 25, zone = "Darkshore" },
			[4] = { str = "Accept Beached Sea Turtle at #COORDS[44,20]#.", x = 44, y = 20, zone = "Darkshore" },
			[5] = { str = "Turn in Buzzbox 323 at #COORDS[51,24]# accept Buzzbox 525.", x = 51, y = 24, zone = "Darkshore" },
			[6] = { str = "Go to #COORDS[54,32]# and do Cave Mushrooms.", x = 54, y = 32, zone = "Darkshore" },
			[7] = { str = "Head south stopping at #COORDS[47,48]# to turn in As Water Cascades accept The Fragments Within.", x = 47, y = 48, zone = "Darkshore" },
			[8] = { str = "Grind to #COORDS[40,53]# and do How Big a Threat? Pt.2.", x = 40, y = 53, zone = "Darkshore" },
			[9] = { str = "Stop at #COORDS[37,62]# and grab Beached Sea Turtle.", x = 37, y = 62, zone = "Darkshore" },
			[10] = { str = "Follow the shore and grab another Beached Sea Creature at #COORDS[36,70]#.", x = 36, y = 70, zone = "Darkshore" },

			[11] = { str = "Turn in Grove of the Ancients at #COORDS[43,76]# if you have it.", x = 43, y = 76, zone = "Darkshore" },
			[12] = { str = "Kill Grizzled Thistle Bear South of Grove of the Ancients for Buzzbox 525 then turn it in at #COORDS[41,80]#.", x = 41, y = 80, zone = "Darkshore" },
			[13] = { str = "Stop at #COORDS[35,74]# and do WANTED: Murkdeep! you have to clear the camp, then the 2 waves from the ocean, then he comes. He’s lvl 19 If you have trouble with him just kite him.", x = 35, y = 74, zone = "Darkshore" },
			[14] = { str = "Grind over to #COORDS[32,80]# and get Beached Sea Creature.", x = 32, y = 80, zone = "Darkshore" },
			[15] = { str = "Hearth back to Auberdine and Turn in all beached creature quests at the hippograph dock." },
			[16] = { str = "Go under the dock grab Fruit of the Sea." },
			[17] = { str = "Turn in Cave Mushrooms in front of the Inn Accept Onu." },
			[18] = { str = "Turn in The Fragments Within in front of the Inn." },
			[19] = { str = "Accept The Absent Minded Prospector at #COORDS[37,41]#.", x = 37, y = 41, zone = "Darkshore" },
			[20] = { str = "Go to the merchant house turn in The Cliffspring River." },

			[21] = { str = "You should be 15 by now so you can accept: The Blackwood Corrupted." },
			[22] = { str = "Cleansing the Infected at the first house accept Tharnariun's Hope." },
			[23] = { str = "Turn in How Big a Threat? Pt.2 accept A Lost Master." },
			[24] = { str = "Fill the Cleansing Bowl at the Moonwell." },
			[25] = { str = "You should be 16 now. Talk to your #NPCClass Trainer# in Darnassus to learn new spells and abilities." },
			[26] = { str = "Do The Blackwood Corrupted at #COORDS[50,34]#(grains) clear b4 all 3 pick ups or the spawn will give adds. If so just run.", x = 50, y = 34, zone = "Darkshore" },
			[27] = { str = "Go do Tharnariun's Hope at #COORDS[51,37]# (den mother) If you can’t kill her with the lvl 9 adds, kill them off and run till she’s alone. Immolate trap her and shoot first so you get the adds, not the pet.", x = 51, y = 37, zone = "Darkshore" },
			[28] = { str = "Do The Blackwood Corrupted #COORDS[51,33]#(nuts) #COORDS[52,33]#(fruit).", x = 51, y = 33, zone = "Darkshore" },
			[29] = { str = "Clear around the Bonfire at #COORDS[52,33]# place the food. Don’t worry they turn good.When Xabraxxis appears kill him. Talisman falls beside.", x = 52, y = 33, zone = "Darkshore" },
			[30] = { str = "Go to #COORDS[54,24]# turn in The Tower of Althalaxx pt.1 Accept The Tower of Althalaxx pt.2 do it. Kill any mob around the tower, NOT in it.", x = 54, y = 24, zone = "Darkshore" },

			[31] = { str = "Hand in The Tower of Althalaxx pt.2 accept The Tower of Althalaxx pt.3." },
			[32] = { str = "Run to #COORDS[53,18]# and grab Beached Sea Creature.", x = 53, y = 18, zone = "Darkshore" },
			[33] = { str = "Do Fruit of the Sea from crawlers around here." },
			[34] = { str = "Hearth back to Auberdine (if you’re not 17 yet you will be) turn in Beached Sea Creature on the dock." },
			[35] = { str = "Turn in Fruit of the Sea under the dock." },
			[36] = { str = "Turn in The Blackwood Corrupted in the merchant house." },
			[37] = { str = "Turn in Tharnariun's Hope at the last house." },
			[38] = { str = "Get on boat to Menethil Harbor. Follow attached run to IF." },
		}
	},

-----------17-18 Loch Modan
	[1718] = {
		title = "17-18 Loch Modan",
		items = {
			[1] = { str = "17-18 Loch Modan" },
			[2] = { str = "Stop right in Loch Modan tower at #COORDS[24,18]# and accept Filthy Paws and Stormpike's Order.", x = 24, y = 18, zone = "Loch Modan" },
			[3] = { str = "Run in the Cave at #COORDS[35,18]# and do Filthy Paws Boxes are on the ground. Then turn it back in at #COORDS[24,18]#.", x = 35, y = 18, zone = "Loch Modan" },
			[4] = { str = "Arrive at Thelsamar get Flight Point at #COORDS[33,50]#.", x = 33, y = 50, zone = "Loch Modan" },
			[5] = { str = "Grab Ironband's Excavation in the last house on the right." },
			[6] = { str = "Turn in Ironband's Excavation at #COORDS[64,66]# Accept Gathering Idols.", x = 64, y = 66, zone = "Loch Modan" },
			[7] = { str = "Grab Excavation Progress Report at #COORDS[65,65]#.", x = 65, y = 65, zone = "Loch Modan" },
			[8] = { str = "Do Gathering Idols behind here then turn it back in." },
			[9] = { str = "Go behind the excavation site to the house at #COORDS[82,62]#.", x = 82, y = 62, zone = "Loch Modan" },
			[10] = { str = "Turn right when you enter and get Crocolisk Hunting (behind hunter trainer) then go to the other side and grab A Hunter's Boast." },

			[11] = { str = "Go do A Hunter's Boast birds in front of the house." },
			[12] = { str = "Turn in A Hunter's Boast accept A Hunter's Challenge do it,mobs are around #COORDS[75,41]#.", x = 75, y = 41, zone = "Loch Modan" },
			[13] = { str = "Turn in A Hunter's Challenge Accept Vyrin's Revenge pt.1." },
			[14] = { str = "Go to #COORDS[63,47]# and accept Bingles' Missing Supplies. Requieries pre-quest Find Bingles from Gnoarn at #COORDS[69,50]# in Ironforge.", x = 63, y = 47, zone = "Loch Modan" },
			[15] = { str = "Do Crocolisk Hunting here on the shore and the island at #COORDS[54,38]#.", x = 54, y = 38, zone = "Loch Modan" },
			[16] = { str = "Grab all the parts for Bingles' Missing Supplies at (#COORDS[54,27]# blastencapper), (#COORDS[48,30]# wrench), (#COORDS[51,23]# hammer), (#COORDS[48,20]# screwdriver).", x = 54, y = 27, zone = "Loch Modan" },
			[17] = { str = "Run up to the dam from the west side and accept A Dark Threat Looms pt.1 at #COORDS[45,13]# then run out the east entrance and turn it in on the barrel guarded by 2 sappers accept A Dark Threat Looms pt.2.", x = 45, y = 13, zone = "Loch Modan" },
			[18] = { str = "Turn in A Dark Threat Looms pt.2 at #COORDS[45,13]#.", x = 45, y = 13, zone = "Loch Modan" },
			[19] = { str = "Run down the west coast Turn in Excavation Progress Report in Thelsamar, accept Report to Ironforge." },
			[20] = { str = "Go to #COORDS[38,61]# and do Vyrin's Revenge pt.1.", x = 38, y = 61, zone = "Loch Modan" },

			[21] = { str = "Run back to the house at #COORDS[83,62]# turn in Crocolisk Hunting and Vyrin's Revenge pt.1 accept Wyrin’s Revenge pt.2.", x = 83, y = 62, zone = "Loch Modan" },
			[22] = { str = "Turn in Wyrin’s Revenge pt.2 behind you." },
			[23] = { str = "Go to #COORDS[63,47]# Turn in Bingles' Missing Supplies.", x = 63, y = 47, zone = "Loch Modan" },
			[24] = { str = "If you don't have IF flight path, run down to #COORDS[22,70]# and follow the path North into Dun Morogh.", x = 22, y = 70, zone = "Loch Modan" },
			[25] = { str = "Run along the road to IronForge at #COORDS[53,35]#.", x = 53, y = 35, zone = "Dun Morogh" },
			[26] = { str = "Get IF weapon training at #COORDS[61,89]# Get Flight Path at #COORDS[55,38]# inside then turn in Report to Ironforge at #COORDS[74,12]# skip Powder to Ironband.", x = 74, y = 12, zone = "Ironforge" },
			[27] = { str = "If you don't have SW flight path, get on the tram at #COORDS[76,51]#.", x = 76, y = 51, zone = "Ironforge" },
			[28] = { str = "Turn in Stormpike's Order at #COORDS[58,16]# in Stormwind.", x = 58, y = 16, zone = "Stormwind City" },
			[29] = { str = "Get SW weapons training at #COORDS[57,57]# and FP at #COORDS[66,62]#.", x = 66, y = 62, zone = "Stormwind City" },
			[30] = { str = "Run towards #COORDS[91,73]# in Elwynn Forest and enter Redridge Mountains.", x = 91, y = 73, zone = "Elwynn Forest" },
		}
	},

-----------18-20 Redridge Mountains
	[1820] = {
		title = "18-20 Redridge Mountains",
		items = {
			[1] = { str = "18-20 Redridge Mountains" },
			[2] = { str = "Accept Encroaching Gnolls from the patrol around #COORDS[15,71]#.", x = 15, y = 71, zone = "Redridge Mountains" },
			[3] = { str = "Turn in Encroaching Gnolls at #COORDS[30,60]# Accept Assessing the Threat.", x = 30, y = 60, zone = "Redridge Mountains" },
			[4] = { str = "Get Flight Point." },
			[5] = { str = "Cross the bridge, on the right accept Blackrock Menace on the left accept The Lost Tools." },
			[6] = { str = "SKIP Elmore's Task SKIP The Price of Shoes." },
			[7] = { str = "Accept Hilary's Necklace on the dock." },
			[8] = { str = "Accept Selling Fish near the shed out front." },
			[9] = { str = "Go in the Inn and accept A Free Lunch, SKIP Dry Times." },
			[10] = { str = "Go west of Lakeshire and accept Redridge Goulash." },

			[11] = { str = "Get Great Goretusk Snouts just west of the houses (watch out for bellygrub we’ll get him later) for Redridge Goulash." },
			[12] = { str = "Then head toward #COORDS[41,54]# to do The Lost Tools and do Selling Fish by killing murlocs, keep an eye out for a glinting mud pile underwater for Hilary's Necklace Save at least 8 murloc fins for a later quest.", x = 41, y = 54, zone = "Redridge Mountains" },
			[13] = { str = "Turn in The Lost Tools by the bridge accept The Everstill Bridge." },
			[14] = { str = "Turn in Hilary's Necklace on the dock." },
			[15] = { str = "Turn in Selling Fish by the shed in front of the houses." },
			[16] = { str = "You should be half way to 20 at this point." },
			[17] = { str = "Turn in A Free Lunch around #COORDS[14,70]# accept Visit the Herbalist.", x = 14, y = 70, zone = "Redridge Mountains" },
			[18] = { str = "Kill spiders for Redridge Goulash between #COORDS[14,70]# and #COORDS[29,83]#.", x = 29, y = 83, zone = "Redridge Mountains" },
			[19] = { str = "Kill gnolls for Assessing the Threat at #COORDS[31,82]#.", x = 31, y = 82, zone = "Redridge Mountains" },
			[20] = { str = "Kill condors for Redridge Goulash around #COORDS[57,73]#.", x = 57, y = 73, zone = "Redridge Mountains" },

			[21] = { str = "Turn in Assessing the Threat near the FP." },
			[22] = { str = "Accept Murloc Poachers (requires lvl 20) in front of the shed." },
			[23] = { str = "Stop at the house just west of Lakeshire, turn in Visit the Herbalist accept Delivering Daffodils." },
			[24] = { str = "Go to the next house, turn in Redridge Goulash." },
			[25] = { str = "Go in the Inn and turn in Delivering Daffodils." },
			[26] = { str = "Kill Murlocs east of the bridge for Murloc Poachers." },
			[27] = { str = "Kill Gnolls north of Lakeshire for The Everstill Bridge." },
			[28] = { str = "Turn in The Everstill Bridge next to the Bridge." },
			[29] = { str = "Turn in Murloc Poachers in front of the shed." },
			[30] = { str = "Hearth back to Auberdine. You should definitely be 20 by this point and at least half way to 21." },
		}
	},
}
