Table_003_Alliance_12to20 = {
-----------12-14 Darkshore
	[1214] = {
		title = "12-14 Darkshore",
		items = {
			[1] = { str = "Welcome to Azeroth, friend! \nThis section of the VanillaGuide will guide you through levels 12 to 14 in #A_Darkshore#." },
			[2] = { str = "Once you land grab #Q_'Washed Ashore'# right in front of you at #C_[37,46]#.", x = 37, y = 46, zone = "Darkshore" },
			[3] = { str = "Turn in #Q_'Flight to Auberdine'# accept #Q_'Return to Nessa'# I fly back to #A_Darnassus# to get it done. She’s right off the edge of the dock." },
			[4] = { str = "Talk to the #N_Innkeeper# to make #A_Auberdine# (#A_Darkshore#) your home. Run out on the docks of #A_Auberdine# (#A_Darkshore#) grab #Q_'For Love Eternal'# at #C_[35,43]#.", x = 35, y = 43, zone = "Darkshore" },
			[5] = { str = "Go upstairs accept #Q_'Buzzbox 827'#." },
			[6] = { str = "Accept #Q_'Cave Mushrooms'# in front of the Inn." },
			[7] = { str = "Grab #Q_'The Red Crystal'# near the bridge." },
			[8] = { str = "Buy some 6 slot bags if you haven’t found 3 by now at #C_[37,40]# then grab #Q_'Bashal’Aran'# and #Q_'Tools of the Highborne'#.", x = 37, y = 40, zone = "Darkshore" },
			[9] = { str = "Go south over the bridge, grab #Q_'Plagued Lands'#." },
			[10] = { str = "Run inside, grab #Q_'How Big a Threat?'#." },

			[11] = { str = "Go do #Q_'Washed Ashore'# at #C_[36,50]# grind from town to there to get Crawler legs for #Q_'Buzzbox 827'#.", x = 36, y = 50, zone = "Darkshore" },
			[12] = { str = "Turn in #Q_'Buzzbox 827'# at #C_[36,46]# accept #Q_'Buzzbox 411'#.", x = 36, y = 46, zone = "Darkshore" },
			[13] = { str = "Turn in #Q_'Washed Ashore'# accept #Q_'Washed Ashore'#(2)." },
			[14] = { str = "Do #Q_'Washed Ashore'#(2) at #C_[31,46]# in the water west of boat dock. Turn it in.", x = 31, y = 46, zone = "Darkshore" },
			[15] = { str = "#Q_'Buzzbox 411'# Threshers look like loch ness in the water, Turn it in at #C_[41,28]# accept #Q_'Buzzbox 323'#.", x = 41, y = 28, zone = "Darkshore" },
			[16] = { str = "Stop at #C_[42,32]# accept #Q_'Beached Sea Creature'#.", x = 42, y = 32, zone = "Darkshore" },
			[17] = { str = "#Q_'Bashal’Aran'# at #C_[44,36]# grinding along the way, accept #Q_'Bashal’Aran'#(2) killing grells around him for earrings.", x = 44, y = 36, zone = "Darkshore" },
			[18] = { str = "Turn in #Q_'Bashal’Aran'#(2) at #C_[44,36]# accept #Q_'Bashal’Aran'#(3).", x = 44, y = 36, zone = "Darkshore" },
			[19] = { str = "Do #Q_'Bashal’Aran'#(3) by killing satyr’s and turn it in accept #Q_'Bashal’Aran'#(4)." },
			[20] = { str = "Grind to #C_[47,48]# and do #Q_'The Red Crystal'#.", x = 47, y = 48, zone = "Darkshore" },

			[21] = { str = "Grind to #C_[40,53]# to find the camp for #Q_'How Big a Threat?'#.", x = 40, y = 53, zone = "Darkshore" },
			[22] = { str = "Run down to Ameth’Aran at #C_[40,59]# and accept #Q_'The Fall of Ameth’Aran'# do it at #C_[43,58]# and #C_[42,63]#.", x = 40, y = 59, zone = "Darkshore" },
			[23] = { str = "Do #Q_'Tools of the Highborne'# while in here, killing mobs for them." },
			[24] = { str = "Do #Q_'For Love Eternal'# at #C_[41,58]# she’s lvl 16 but easy.", x = 41, y = 58, zone = "Darkshore" },
			[25] = { str = "Do #Q_'Bashal’Aran'#(4) at #C_[42,61]#.", x = 42, y = 61, zone = "Darkshore" },
			[26] = { str = "Turn in #Q_'The Fall of Ameth’Aran'# at #C_[40,59]#.", x = 40, y = 59, zone = "Darkshore" },
			[27] = { str = "To the west of Ameth’Aran do #Q_'Plagued Lands'#." },
			[28] = { str = "Use your #I_[Hearthstone]# to return to #A_Auberdine# (#A_Darkshore#) Turn in #Q_'Plagued Lands'# at the first house accept #Q_'Cleansing the Infected'#." },
			[29] = { str = "Go inside hand in #Q_'How Big a Threat?'# accept #Q_'How Big a Threat?'#(2))." },
			[30] = { str = "Accept #Q_'Thundris Windweaver'#." },

			[31] = { str = "Go Upstairs accept #Q_'The Tower of Althalaxx'#." },
			[32] = { str = "Don’t do #Q_'Deep Ocean, Vast Sea'# it’s not worth it and too hard." },
			[33] = { str = "Go in the merchant house, turn in #Q_'Tools of the Highborne'#." },
			[34] = { str = "Turn in #Q_'Thundris Windweaver'# accept #Q_'The Cliffspring River'#." },
			[35] = { str = "Turn in #Q_'The Red Crystal'# near the Inn accept #Q_'As Water Cascades'#." },
			[36] = { str = "Fill the Vial in the Moonwell for #Q_'As Water Cascades'#." },
			[37] = { str = "Accept #Q_'WANTED: Murkdeep!'# in front of the Inn (lvl 15 quest now)." },
			[38] = { str = "Turn in #Q_'For Love Eternal'# on the dock. Watch the love story." },
			[39] = { str = "You should be 14 by now. Talk to your #N_Class Trainer# in #A_Darnassus# to learn new spells and abilities. Be sure to accept the quest #Q_'Trouble In Darkshore?'# from Chief Archaeologist Greywhisker at #C_[31,84]#.", x = 31, y = 84, zone = "Darnassus" },
		}
	},

-----------14-17 Darkshore
	[1417] = {
		title = "14-17 Darkshore",
		items = {
			[1] = { str = "Welcome to Azeroth, friend! \nThis section of the VanillaGuide will guide you through levels 14 to 17 in #A_Darkshore#." },
			[2] = { str = "Go back to Darkshore. Turn in #Q_'Trouble In Darkshore?'# at #C_[37,42]#. Then turn in #Q_'Bashal’Aran'#(4) at #C_[44,36]#.", x = 44, y = 36, zone = "Darkshore" },
			[3] = { str = "Kill Moonstalkers and Rabid Thistle Bears all around #C_[48,30]# while you head to #C_[50,25]# for #Q_'The Cliffspring River'#.", x = 50, y = 25, zone = "Darkshore" },
			[4] = { str = "Accept #Q_'Beached Sea Turtle'# at #C_[44,20]#.", x = 44, y = 20, zone = "Darkshore" },
			[5] = { str = "Turn in #Q_'Buzzbox 323'# at #C_[51,24]# accept #Q_'Buzzbox 525'#.", x = 51, y = 24, zone = "Darkshore" },
			[6] = { str = "Go to #C_[54,32]# and do #Q_'Cave Mushrooms'#.", x = 54, y = 32, zone = "Darkshore" },
			[7] = { str = "Head south stopping at #C_[47,48]# to turn in #Q_'As Water Cascades'# accept #Q_'The Fragments Within'#.", x = 47, y = 48, zone = "Darkshore" },
			[8] = { str = "Grind to #C_[40,53]# and do #Q_'How Big a Threat?'#(2).", x = 40, y = 53, zone = "Darkshore" },
			[9] = { str = "Stop at #C_[37,62]# and grab #Q_'Beached Sea Turtle'#.", x = 37, y = 62, zone = "Darkshore" },
			[10] = { str = "Follow the shore and grab another #Q_'Beached Sea Creature'# at #C_[36,70]#.", x = 36, y = 70, zone = "Darkshore" },

			[11] = { str = "Turn in #Q_'Grove of the Ancients'# at #C_[43,76]# if you have it.", x = 43, y = 76, zone = "Darkshore" },
			[12] = { str = "Kill Grizzled Thistle Bear South of #Q_'Grove of the Ancients'# for #Q_'Buzzbox 525'# then turn it in at #C_[41,80]#.", x = 41, y = 80, zone = "Darkshore" },
			[13] = { str = "Stop at #C_[35,74]# and do #Q_'WANTED: Murkdeep!'# you have to clear the camp, then the 2 waves from the ocean, then he comes. He’s lvl 19 If you have trouble with him just kite him.", x = 35, y = 74, zone = "Darkshore" },
			[14] = { str = "Grind over to #C_[32,80]# and get #Q_'Beached Sea Creature'#.", x = 32, y = 80, zone = "Darkshore" },
			[15] = { str = "Use your #I_[Hearthstone]# to return to #A_Auberdine# (#A_Darkshore#) and Turn in all beached creature quests at the hippograph dock." },
			[16] = { str = "Go under the dock grab #Q_'Fruit of the Sea'#." },
			[17] = { str = "Turn in #Q_'Cave Mushrooms'# in front of the Inn Accept #Q_'Onu'#." },
			[18] = { str = "Turn in #Q_'The Fragments Within'# in front of the Inn." },
			[19] = { str = "Accept #Q_'The Absent Minded Prospector'# at #C_[37,41]#.", x = 37, y = 41, zone = "Darkshore" },
			[20] = { str = "Go to the merchant house turn in #Q_'The Cliffspring River'#." },

			[21] = { str = "You should be 15 by now so you can accept: #Q_'The Blackwood Corrupted'#." },
			[22] = { str = "#Q_'Cleansing the Infected'# at the first house accept #Q_'Tharnariun’s Hope'#." },
			[23] = { str = "Turn in #Q_'How Big a Threat?'#(2). Accept #Q_'A Lost Master'#." },
			[24] = { str = "Fill the Cleansing Bowl at the Moonwell." },
			[25] = { str = "You should be 16 now. Talk to your #N_Class Trainer# in #A_Darnassus# to learn new spells and abilities." },
			[26] = { str = "Do #Q_'The Blackwood Corrupted'# at #C_[50,34]#(grains) clear b4 all 3 pick ups or the spawn will give adds. If so just run.", x = 50, y = 34, zone = "Darkshore" },
			[27] = { str = "Go do #Q_'Tharnariun’s Hope'# at #C_[51,37]# (den mother) If you can’t kill her with the lvl 9 adds, kill them off and run till she’s alone. Immolate trap her and shoot first so you get the adds, not the pet.", x = 51, y = 37, zone = "Darkshore" },
			[28] = { str = "Do #Q_'The Blackwood Corrupted'# #C_[51,33]#(nuts) #C_[52,33]#(fruit).", x = 51, y = 33, zone = "Darkshore" },
			[29] = { str = "Clear around the Bonfire at #C_[52,33]# place the food. Don’t worry they turn good.When Xabraxxis appears kill him. Talisman falls beside.", x = 52, y = 33, zone = "Darkshore" },
			[30] = { str = "Go to #C_[54,24]# turn in #Q_'The Tower of Althalaxx'# Accept #Q_'The Tower of Althalaxx'#(2) do it. Kill any mob around the tower, NOT in it.", x = 54, y = 24, zone = "Darkshore" },

			[31] = { str = "Hand in #Q_'The Tower of Althalaxx'#(2) accept #Q_'The Tower of Althalaxx'#(3)." },
			[32] = { str = "Run to #C_[53,18]# and grab #Q_'Beached Sea Creature'#.", x = 53, y = 18, zone = "Darkshore" },
			[33] = { str = "Do #Q_'Fruit of the Sea'# from crawlers around here." },
			[34] = { str = "Use your #I_[Hearthstone]# to return to #A_Auberdine# (#A_Darkshore#) (if you’re not 17 yet you will be) turn in #Q_'Beached Sea Creature'# on the dock." },
			[35] = { str = "Turn in #Q_'Fruit of the Sea'# under the dock." },
			[36] = { str = "Turn in #Q_'The Blackwood Corrupted'# in the merchant house." },
			[37] = { str = "Turn in #Q_'Tharnariun’s Hope'# at the last house." },
			[38] = { str = "Get on boat to #A_Menethil Harbor# (#A_The Wetlands#). Follow attached run to #A_Ironforge#." },
		}
	},

-----------17-18 Loch Modan
	[1718] = {
		title = "17-18 Loch Modan",
		items = {
			[1] = { str = "Welcome to Azeroth, friend! \nThis section of the VanillaGuide will guide you through levels 17 to 18 in #A_Loch Modan#." },
			[2] = { str = "Stop right in #A_Loch Modan# tower at #C_[24,18]# and accept #Q_'Filthy Paws'# and #Q_'Stormpike’s Order'#.", x = 24, y = 18, zone = "Loch Modan" },
			[3] = { str = "Run in the Cave at #C_[35,18]# and do #Q_'Filthy Paws'# Boxes are on the ground. Then turn it back in at #C_[24,18]#.", x = 35, y = 18, zone = "Loch Modan" },
			[4] = { str = "Arrive at #A_Thelsamar# (#A_Loch Modan#) Unlock the flight path by talking to the #N_Flight Master# at #C_[33,50]#.", x = 33, y = 50, zone = "Loch Modan" },
			[5] = { str = "Grab #Q_'Ironband’s Excavation'# in the last house on the right." },
			[6] = { str = "Turn in #Q_'Ironband’s Excavation'# at #C_[64,66]#. Accept #Q_'Gathering Idols'#.", x = 64, y = 66, zone = "Loch Modan" },
			[7] = { str = "Grab #Q_'Excavation Progress Report'# at #C_[65,65]#.", x = 65, y = 65, zone = "Loch Modan" },
			[8] = { str = "Do #Q_'Gathering Idols'# behind here then turn it back in." },
			[9] = { str = "Go behind the excavation site to the house at #C_[82,62]#.", x = 82, y = 62, zone = "Loch Modan" },
			[10] = { str = "Turn right when you enter and get #Q_'Crocolisk Hunting'# (behind hunter trainer) then go to the other side and grab #Q_'A Hunter’s Boast'#." },

			[11] = { str = "Go do #Q_'A Hunter’s Boast'# birds in front of the house." },
			[12] = { str = "Turn in #Q_'A Hunter’s Boast'# accept #Q_'A Hunter’s Challenge'# do it,mobs are around #C_[75,41]#.", x = 75, y = 41, zone = "Loch Modan" },
			[13] = { str = "Turn in #Q_'A Hunter’s Challenge'# Accept #Q_'Vyrin’s Revenge'#." },
			[14] = { str = "Go to #C_[63,47]# and accept #Q_'Bingles’ Missing Supplies'#. Requieries pre-quest #Q_'Find Bingles'# from Gnoarn at #C_[69,50]# in Ironforge.", x = 63, y = 47, zone = "Loch Modan" },
			[15] = { str = "Do #Q_'Crocolisk Hunting'# here on the shore and the island at #C_[54,38]#.", x = 54, y = 38, zone = "Loch Modan" },
			[16] = { str = "Grab all the parts for #Q_'Bingles’ Missing Supplies'# at (#C_[54,27]# blastencapper), (#C_[48,30]# wrench), (#C_[51,23]# hammer), (#C_[48,20]# screwdriver).", x = 54, y = 27, zone = "Loch Modan" },
			[17] = { str = "Run up to the dam from the west side and accept #Q_'A Dark Threat Looms'# at #C_[45,13]# then run out the east entrance and turn it in on the barrel guarded by 2 sappers accept #Q_'A Dark Threat Looms'#(2).", x = 45, y = 13, zone = "Loch Modan" },
			[18] = { str = "Turn in #Q_'A Dark Threat Looms'#(2) at #C_[45,13]#.", x = 45, y = 13, zone = "Loch Modan" },
			[19] = { str = "Run down the west coast Turn in #Q_'Excavation Progress Report'# in #A_Thelsamar# (#A_Loch Modan#) accept #Q_'Report to Ironforge'#." },
			[20] = { str = "Go to #C_[38,61]# and do #Q_'Vyrin’s Revenge'#.", x = 38, y = 61, zone = "Loch Modan" },

			[21] = { str = "Run back to the house at #C_[83,62]# turn in #Q_'Crocolisk Hunting'# and #Q_'Vyrin’s Revenge'# accept #Q_'Vyrin’s Revenge'#(2).", x = 83, y = 62, zone = "Loch Modan" },
			[22] = { str = "Turn in #Q_'Vyrin’s Revenge'#(2) behind you." },
			[23] = { str = "Go to #C_[63,47]# Turn in #Q_'Bingles’ Missing Supplies'#.", x = 63, y = 47, zone = "Loch Modan" },
			[24] = { str = "If you don’t have #A_Ironforge# flight path, run down to #C_[22,70]# and follow the path North into #A_Dun Morogh#.", x = 22, y = 70, zone = "Loch Modan" },
			[25] = { str = "Run along the road to #A_Ironforge# at #C_[53,35]#.", x = 53, y = 35, zone = "Dun Morogh" },
			[26] = { str = "Talk to the #N_Weapon Master# in #A_Ironforge# to learn additional weapon skills at #C_[61,89]#. Unlock the flight path by talking to the #N_Flight Master# at #C_[55,38]# inside then turn in #Q_'Report to Ironforge'# at #C_[74,12]# skip #Q_'Powder to Ironband'#.", x = 74, y = 12, zone = "Ironforge" },
			[27] = { str = "If you don’t have #A_Stormwind# flight path, get on the tram at #C_[76,51]#.", x = 76, y = 51, zone = "Ironforge" },
			[28] = { str = "Turn in #Q_'Stormpike’s Order'# at #C_[58,16]# in #A_Stormwind#.", x = 58, y = 16, zone = "Stormwind City" },
			[29] = { str = "Talk to the #N_Weapon Master# in #A_Stormwind# to learn additional weapon skills at #C_[57,57]#. Unlock the flight path by talking to the #N_Flight Master# at #C_[66,62]#.", x = 66, y = 62, zone = "Stormwind City" },
			[30] = { str = "Run towards #C_[91,73]# in #A_Elwynn Forest# and enter #A_Redridge Mountains#.", x = 91, y = 73, zone = "Elwynn Forest" },
		}
	},

-----------18-20 Redridge Mountains
	[1820] = {
		title = "18-20 Redridge Mountains",
		items = {
			[1] = { str = "Welcome to Azeroth, friend! \nThis section of the VanillaGuide will guide you through levels 18 to 20 in #A_Redridge Mountains#." },
			[2] = { str = "Accept #Q_'Encroaching Gnolls'# from the patrol around #C_[15,71]#.", x = 15, y = 71, zone = "Redridge Mountains" },
			[3] = { str = "Turn in #Q_'Encroaching Gnolls'# at #C_[30,60]# Accept #Q_'Assessing the Threat'#.", x = 30, y = 60, zone = "Redridge Mountains" },
			[4] = { str = "Unlock the flight path by talking to the #N_Flight Master#." },
			[5] = { str = "Cross the bridge, on the right accept #Q_'Blackrock Menace'# on the left accept #Q_'The Lost Tools'#." },
			[6] = { str = "SKIP #Q_'Elmore’s Task'# SKIP #Q_'The Price of Shoes'#." },
			[7] = { str = "Accept #Q_'Hilary’s Necklace'# on the dock." },
			[8] = { str = "Accept #Q_'Selling Fish'# near the shed out front." },
			[9] = { str = "Go in the Inn and accept #Q_'A Free Lunch'#, SKIP Dry Times." },
			[10] = { str = "Go west of #A_Lakeshire# (#A_Redridge Mountains#) and accept #Q_'Redridge Goulash'#." },

			[11] = { str = "Get Great Goretusk Snouts just west of the houses (watch out for bellygrub we’ll get him later) for #Q_'Redridge Goulash'#." },
			[12] = { str = "Then head toward #C_[41,54]# to do #Q_'The Lost Tools'# and do #Q_'Selling Fish'# by killing murlocs, keep an eye out for a glinting mud pile underwater for #Q_'Hilary’s Necklace'# Save at least 8 murloc fins for a later quest.", x = 41, y = 54, zone = "Redridge Mountains" },
			[13] = { str = "Turn in #Q_'The Lost Tools'# by the bridge accept #Q_'The Everstill Bridge'#." },
			[14] = { str = "Turn in #Q_'Hilary’s Necklace'# on the dock." },
			[15] = { str = "Turn in #Q_'Selling Fish'# by the shed in front of the houses." },
			[16] = { str = "You should be half way to 20 at this point." },
			[17] = { str = "Turn in #Q_'A Free Lunch'# around #C_[14,70]# accept #Q_'Visit the Herbalist'#.", x = 14, y = 70, zone = "Redridge Mountains" },
			[18] = { str = "Kill spiders for #Q_'Redridge Goulash'# between #C_[14,70]# and #C_[29,83]#.", x = 29, y = 83, zone = "Redridge Mountains" },
			[19] = { str = "Kill gnolls for #Q_'Assessing the Threat'# at #C_[31,82]#.", x = 31, y = 82, zone = "Redridge Mountains" },
			[20] = { str = "Kill condors for #Q_'Redridge Goulash'# around #C_[57,73]#.", x = 57, y = 73, zone = "Redridge Mountains" },

			[21] = { str = "Turn in #Q_'Assessing the Threat'# near the flight path." },
			[22] = { str = "Accept #Q_'Murloc Poachers'# (requires lvl 20) in front of the shed." },
			[23] = { str = "Stop at the house just west of #A_Lakeshire# (#A_Redridge Mountains#), turn in #Q_'Visit the Herbalist'# accept #Q_'Delivering Daffodils'#." },
			[24] = { str = "Go to the next house, turn in #Q_'Redridge Goulash'#." },
			[25] = { str = "Go in the Inn and turn in #Q_'Delivering Daffodils'#." },
			[26] = { str = "Kill Murlocs east of the bridge for #Q_'Murloc Poachers'#." },
			[27] = { str = "Kill Gnolls north of #A_Lakeshire# (#A_Redridge Mountains#) for #Q_'The Everstill Bridge'#." },
			[28] = { str = "Turn in #Q_'The Everstill Bridge'# next to the Bridge." },
			[29] = { str = "Turn in #Q_'Murloc Poachers'# in front of the shed." },
			[30] = { str = "Use your #I_[Hearthstone]# to return to #A_Auberdine# (#A_Darkshore#). You should definitely be 20 by this point and at least half way to 21." },
		}
	},
}
