Table_003_Alliance_50to60 = {
-----------50-51 Searing Gorge
	[5051] = {
		title = "50-51 Searing Gorge",
		items = {
			[1] = { str = "50-51 Searing Gorge" },
			[2] = { str = "Go down to #C_[65,62]# and touch the outhouse, accept #Q_'Caught!'#.", x = 65, y = 62, zone = "Searing Gorge" },
			[3] = { str = "Go just below the outhouse and kill the geologists for #Q_'Caught!'#." },
			[4] = { str = "Clear all the mobs and at the bottom of the little pit, accept #Q_'Suntara Stones'# escort him to #C_[74,19]# and when he dies grab the note which starts #Q_'Suntara Stones'#(2).", x = 74, y = 19, zone = "Searing Gorge" },
			[5] = { str = "Run back down near the outhouse at #C_[65,62]# and get the last of your geologist kills if you need them and turn in #Q_'Caught!'# at the outhouse, accept #Q_'Ledger From Tanaris'# and grab the book he slips you under the door.", x = 65, y = 62, zone = "Searing Gorge" },
			[6] = { str = "Run down to #C_[71,72]# and kill Margol the Rager, and grab Margol's Horn off him which starts #Q_'The Horn of the Beast'#. This gives you the searing gorge key, useless now that there is a flight path here but good XP.", x = 71, y = 72, zone = "Searing Gorge" },
			[7] = { str = "Run over to #C_[39,38]# and accept #Q_'Divine Retribution'# then talk to him until completed, accept #Q_'The Flawless Flame'#.", x = 39, y = 38, zone = "Searing Gorge" },
			[8] = { str = "Run up to #A_Thorium Point# (#A_Searing Gorge#) at #C_[38,26]#.", x = 38, y = 26, zone = "Searing Gorge" },
			[9] = { str = "Grab these quests off the sign: #Q_'WANTED: Overseer Maltorius'# (this will require a group) #Q_'STOLEN: Smithing Tuyere'# and #Q_'Lookout's Spyglass'# and #Q_'JOB OPPORTUNITY: Culling the Competition'#." },
			[10] = { str = "Accept #Q_'Curse These Fat Fingers'# #Q_'Fiery Menace!'# #Q_'Incendosaurs? Whateverosaur is More Like It'# near the tower." },

			[11] = { str = "Under the tent accept #Q_'What The Flux?'#." },
			[12] = { str = "Unlock the flight path by talking to the #N_Flight Master# and fly to #A_Ironforge#." },
			[13] = { str = "Stop at #C_[71,16]# and turn in #Q_'Suntara Stones'#(2) accept #Q_'Dwarven Justice'#.", x = 71, y = 16, zone = "Searing Gorge" },
			[14] = { str = "Fly to #A_Thelsamar# (#A_Loch Modan#)." },
			[15] = { str = "Run down to #C_[18,83]# and turn in #Q_'The Horn of the Beast'#. Accept #Q_'Proof of Deed'#.", x = 18, y = 83, zone = "Searing Gorge" },
			[16] = { str = "Use your #I_[Hearthstone]# to return to #A_Ironforge#." },
			[17] = { str = "Go to #C_[69,11]# turn in, #Q_'Proof of Deed'#, accept #Q_'At Last!'#", x = 69, y = 11, zone = "Searing Gorge" },
			[18] = { str = "Go to #C_[75,23]# and accept #Q_'A Little Slime Goes A Long Way'#.", x = 75, y = 23, zone = "Searing Gorge" },
			[19] = { str = "Fly to #A_Thelsamar# (#A_Loch Modan#) and run to #C_[18,83]#.", x = 18, y = 83, zone = "Searing Gorge" },
			[20] = { str = "Turn in #Q_'At Last!'# put the key on your keyring. Easy 12k xp." },

			[21] = { str = "Now the fun part, doing all these quests. Some of the mobs you have to kill are in a widespread area so I really won’t list coords on them." },
			[22] = { str = "From here south kill glassweb spiders for #Q_'Ledger From Tanaris'#." },
			[23] = { str = "Kill any golems you see over here for #Q_'The Flawless Flame'#." },
			[24] = { str = "Go around the southern part of the cauldron (the pit) and circle it back towards #A_Thorium Point# (#A_Searing Gorge#) and do the following:" },
			[25] = { str = "Kill heavy war golems and infernal elementals (not magma elementalsfor #Q_'The Flawless Flame'# and heavy war golems for #Q_'Curse These Fat Fingers'#." },
			[26] = { str = "Kill dark iron lookouts and steamsmiths (Only 6 of them, so come back if they don’t drop, they seem to drop outhouse key a lot) for #Q_'STOLEN: Smithing Tuyere'# and #Q_'Lookout's Spyglass'#." },
			[27] = { str = "Turn in #Q_'The Flawless Flame'#. Accept #Q_'Forging the Shaft'# when you’re near #A_Thorium Point# (#A_Searing Gorge#) again." },
			[28] = { str = "Kill greater lava spiders (not searing) for #Q_'Fiery Menace!'# Mostly SW." },
			[29] = { str = "If the Grimesilt Outhouse Key dropped, use it to start #Q_'The Key to Freedom'# and turn it in at #C_[65,62]#.", x = 65, y = 62, zone = "Searing Gorge" },
			[30] = { str = "Go to #C_[63,38]# and start going down into the cauldron.", x = 63, y = 38, zone = "Searing Gorge" },

			[31] = { str = "Kill dark iron taskmasters and slavers down here and inside the cave if you see them for #Q_'JOB OPPORTUNITY: Culling the Competition'# and #Q_'Forging the Shaft'#." },
			[32] = { str = "Enter the caves at #C_[41,54]#.", x = 41, y = 54, zone = "Searing Gorge" },
			[33] = { str = "Go in the cave to #C_[41,25]# and go through the jail bar door, turn in #Q_'Dwarven Justice'#. Accept #Q_'Release Them'#.", x = 41, y = 25, zone = "Searing Gorge" },
			[34] = { str = "Go up the ramp and stay right until #C_[40,35]# kill the boss here for #Q_'WANTED: Overseer Maltorius'# and grab #Q_'What The Flux?'# on the rail behind him. If you can’t find a group have the pet get the aggro and run the guys away from the plans. This is doable with 2 people but very tough. If you can’t get this quest done no big deal but I usually get it done.", x = 40, y = 35, zone = "Searing Gorge" },
			[35] = { str = "Keep following the path that goes outside and curves back in. You’ll come to a big dead end area with lots of Incendosaur for #Q_'Incendosaurs? Whateverosaur is More Like It'# Save the scales." },
			[36] = { str = "Grind until youre 36k from leveling." },
			[37] = { str = "Die on purpose so you end up back at #A_Thorium Point# (#A_Searing Gorge#) and turn in these quests." },
			[38] = { str = "Go next to the sign, turn in #Q_'WANTED: Overseer Maltorius'#." },
			[39] = { str = "To the right of the tower, turn in #Q_'Curse These Fat Fingers'# #Q_'Fiery Menace!'# and #Q_'Incendosaurs? Whateverosaur is More Like It'#." },
			[40] = { str = "Go to the tent behind here, turn in #Q_'STOLEN: Smithing Tuyere'# and #Q_'Lookout's Spyglass'# and #Q_'JOB OPPORTUNITY: Culling the Competition'#." },

			[41] = { str = "Go to the next tent, turn in #Q_'What The Flux?'#." },
			[42] = { str = "Once this is all handed in you can now do repeat quests for small xp and faction with #A_Thunder Bluff#. The reason I said to save the scales or sell em." },
			[43] = { str = "You should be a hair from 51 now, go south of base to #C_[38,38]#.", x = 38, y = 38, zone = "Searing Gorge" },
			[44] = { str = "Turn in #Q_'Forging the Shaft'#. Accept #Q_'The Flame’s Casing'#." },
			[45] = { str = "Now you shoud be between 1-2 bars into 51." },
			[46] = { str = "Run over to the path up the mountain at #C_[24,32]#.", x = 24, y = 32, zone = "Searing Gorge" },
			[47] = { str = "Kill the elites 1 by 1 on your way up to the lava pit at #C_[29,25]# and clear the mobs around it, the idolators don’t chain link and don’t attack when you touch the rock in the center. Jump on the rock either with mount or jump in lava then on it. Open it for #Q_'Release Them'#.", x = 29, y = 25, zone = "Searing Gorge" },
			[48] = { str = "While killing these guys around the pool you should have found a Symbol of Ragnaros for #Q_'The Flame’s Casing'# if not kill until you do." },
			[49] = { str = "Make sure you talk to the caged npc next to the lava, he gives you #Q_'Prayer to Elune'# Listen to his short story and turn it in for #Q_'Prayer to Elune'#(2) Now you have to kill these for the Rag dropping and the #Q_'Prayer to Elune'#(2), Easy drops." },
			[50] = { str = "Go down to #C_[38,38]# and turn in #Q_'The Flame’s Casing'#. Accept #Q_'The Torch of Retribution'# then turn it back in accept #Q_'The Torch of Retribution'#(2) then grab the torch in front of him and complete it and accept #Q_'Squire Maltrake'# and turn that back in and accept #Q_'Set Them Ablaze!'#", x = 38, y = 38, zone = "Searing Gorge" },

			[51] = { str = "Now equip the staff and run to each of the 4 towers at N:#C_[33,53]# W:#C_[36,60]# S:#C_[44,61]# E:#C_[50,54]# and either kill the guys downstairs, and run up and light the brazier." },
			[52] = { str = "When you get them all, look for a safe spot to jump down and go in the caves at #C_[41,54]# again and through the jail bar door at #C_[37,44]# and run to the room with the golem at #C_[41,25]# and touch the candle covered stone and turn in #Q_'Release Them'# SKIP the next part unless you wanna do it with a group, it’s very tough you have to fight that golem and a dwarf both elites.", x = 41, y = 54, zone = "Searing Gorge" },
			[53] = { str = "Die on purpose so you end up at #A_Thorium Point# (#A_Searing Gorge#) and go down to #C_[29,38]# and turn in #Q_'Set Them Ablaze!'# watch the cutscene as he turns into a dragon.", x = 29, y = 38, zone = "Searing Gorge" },
			[54] = { str = "Open the chest on the ground accept #Q_'Trinkets'#. then open it again and complete it. Open it and keep the Black Dragonflight Molt for later In the #A_Burning Steppes#." },
			[55] = { str = "Fly to the Blasted Lands and run up into the Swamp of Sorrows." },
			[56] = { str = "Go to #C_[81,91]# and look for a named murloc Jarquia for #Q_'Ledger From Tanaris'#.", x = 81, y = 91, zone = "Swamp of Sorrows" },
			[57] = { str = "Once you kill him use your #I_[Hearthstone]# to return to #A_Ironforge# then either get a portal to #A_Darnassus# or fly to #A_Menethil Harbor# (#A_The Wetlands#) then boat to #A_Auberdine# (#A_Darkshore#) and fly to #A_Darnassus#." },
			[58] = { str = "Go to the top of the temple of the moon at #C_[38,80]# and turn in #Q_'Prayer to Elune'#(2).", x = 38, y = 80, zone = "Darnassus" },
			[59] = { str = "Go to the next section up here and turn in #Q_'Rise of the Silithid'#. Accept #Q_'March of the Silithid'#." },
			[60] = { str = "Go to #C_[34,9]# at the top of the tower and turn in #Q_'Assisting Arch Druid Staghelm'#. Accept #Q_'Un’Goro Soil'#.", x = 34, y = 9, zone = "Darnassus" },

			[61] = { str = "Talk to the #N_Innkeeper# to make #A_Darnassus# your home at #C_[67,15]#.", x = 67, y = 15, zone = "Darnassus" },
			[62] = { str = "Now either fly to #A_Theramore# (#A_Dustwallow Marsh#) or boat to #A_Menethil Harbor# then to #A_Theramore# (#A_Dustwallow Marsh#)." },
			[63] = { str = "Get first aid up to 290 if you haven’t for heavy runecloth bandages." },
			[64] = { str = "Go over to #C_[54,55]# to the wrecked ship and grab the overdue package for #Q_'Ledger From Tanaris'#.", x = 54, y = 55, zone = "Duskwallow Marsh" },
			[65] = { str = "Go to the cave at #C_[31,66]# and touch the scroll in the back of the cave which turns in #Q_'Cortello's Riddle'#(2) accept #Q_'Cortello's Riddle'#(3).", x = 31, y = 66, zone = "Duskwallow Marsh" },
			[66] = { str = "Aggro all the raptors and die so you end up at #A_Theramore# (#A_Dustwallow Marsh#)." },
			[67] = { str = "Fly to #A_Gadgetzan# (#A_Tanaris#)." },
			[68] = { str = "Just as you enter #A_Gadgetzan# (#A_Tanaris#), turn in #Q_'Ledger From Tanaris'#." },
			[69] = { str = "Get your level 52 set gloves out of bank or mail for later." },
			[70] = { str = "Between the 2 North gates accept #Q_'Super Sticky'#." },

			[71] = { str = "Go to the hut just west and turn in #Q_'March of the Silithid'#. Accept #Q_'Bungle in the Jungle'#." },
			[72] = { str = "Run down into the #A_Un’Goro Crater# at #C_[26,52]#.", x = 26, y = 52, zone = "Tanaris" },
		}
	},

-----------51-52 Un’Goro Crater
	[5152] = {
		title = "51-52 Un’Goro Crater",
		items = {
			[1] = { str = "51-52 Un’Goro Crater" },
			[2] = { str = "Keep an eye out for the following items laying around the crafter: Power Crystals (need 7 of red,blue,green,yellow), Un’Goro Dirt Piles (get as many as you can), and Bloodpetal Sprouts: save in sets of 15." },
			[3] = { str = "I tell you to grind through the raptors here only for 1 reason. To find the item A Mangled Journal. Once you have it you don’t have to grind through the raptors." },
			[4] = { str = "Follow the path down to the waterfall at #C_[71,75]# and accept #Q_'The Apes of Un’Goro'# and #Q_'The Fare of Lar'Korwi'#.", x = 71, y = 75, zone = "Un’Goro Crater" },
			[5] = { str = "Grind to #C_[62,68]# and click on the wrecked raft, accept #Q_'It's A Secret to Everybody'# then take 2 steps under the water, turn it in and accept #Q_'It's A Secret to Everybody'#(2).", x = 62, y = 68, zone = "Un’Goro Crater" },
			[6] = { str = "Grind to #C_[68,56]# and get the meat off the big dinosaur for #Q_'The Fare of Lar'Korwi'#.", x = 68, y = 56, zone = "Un’Goro Crater" },
			[7] = { str = "Go back to #C_[71,75]# and turn in #Q_'The Fare of Lar'Korwi'#. Accept #Q_'The Scent of Lar'Korwi'#.", x = 71, y = 75, zone = "Un’Goro Crater" },
			[8] = { str = "Grind west to about #C_[67,63]# and there will be 2 spots with a bunch of eggs. Clear the raptors around it and stand on the eggs to get the mates to spawn for #Q_'The Scent of Lar'Korwi'#.", x = 67, y = 63, zone = "Un’Goro Crater" },
			[9] = { str = "Once you have this done, go back to #C_[71,75]# and turn in #Q_'The Scent of Lar'Korwi'#. Accept #Q_'The Bait For Lar'Korwi'# you should have found the jornal by now as well, if not keep grinding raptors while you’re questing in this spot. If you have start the quest #Q_'Williden’s Journal'#.", x = 71, y = 75, zone = "Un’Goro Crater" },
			[10] = { str = "Go up to #C_[79,49]# it’s off to the east side in the mountains, behind the east pylon. You’ll see a big skeleton which is also the #A_Graveyard#. There is a fairly big flat stone, stand on it and use the meat and phermone. This will summon Lar’Korwi for #Q_'The Bait For Lar'Korwi'# super easy kill even at 51 and he’s 56, he has 3600 hp.", x = 79, y = 49, zone = "Un’Goro Crater" },

			[11] = { str = "Go to #C_[46,13]# and accept #Q_'Chasing A-Me 01'# and run up the path behind her into Marshal’s Refuge.", x = 46, y = 13, zone = "Un’Goro Crater" },
			[12] = { str = "Just to the left accept #Q_'Shizzle's Flyer'#." },
			[13] = { str = "Next to the left, a little bit back, accept #Q_'Muigin and Larion'#." },
			[14] = { str = "Next, near the sign accept #Q_'Lost!'# and on the sign accept #Q_'Beware of Pterrordax'#." },
			[15] = { str = "In front of the cave, accept #Q_'Roll the Bones'#." },
			[16] = { str = "If you have at least 15 bloodpetal sprouts, turn them in at the kodo for the repeatable quest #Q_'Dadanga is Hungry!'# you can get a very expensive recipe but it’s rare but worth trying." },
			[17] = { str = "To the right of the cave, accept #Q_'Alien Ecology'#." },
			[18] = { str = "To the right again, turn in #Q_'Williden’s Journal'#. Accept #Q_'Expedition Salvation'#." },
			[19] = { str = "Run just south a bit and you’ll find Linken just outside of a half hollow tree. Turn in #Q_'It's A Secret to Everybody'#(2) accept #Q_'It's A Secret to Everybody'#(3)." },
			[20] = { str = "Unlock the flight path by talking to the #N_Flight Master# to the right of the cave (added in 1.11) then go in the cave all the way to the end and accept #Q_'Crystals of Power'# and then turn it in Accept the 3 pylon quests #Q_'The Northern Pylon'# #Q_'The Eastern Pylon'# #Q_'The Western Pylon'#." },

			[21] = { str = "When ever you see the following mobs kill them on site until the quest associate with them is finished." },
			[22] = { str = "Kill bloodpetals for #Q_'Muigin and Larion'#." },
			[23] = { str = "Kill diametradons and pterrodaxes for #Q_'Shizzle's Flyer'# and #Q_'Roll the Bones'#." },
			[24] = { str = "Kill pterrodaxes and frenzied pterrodaxes for #Q_'Beware of Pterrordax'#." },
			[25] = { str = "Go east along the mountains to #C_[54,13]# and take that path up examine the pylon for #Q_'The Northern Pylon'# and go farther north, there should be sone pterrodaxes.", x = 54, y = 13, zone = "Un’Goro Crater" },
			[26] = { str = "Go east to #C_[63,16]# and kill gorillas for #Q_'The Apes of Un’Goro'# then go in the cave and stay right to turn in #Q_'Chasing A-Me 01'#. SKIP the next part for now.", x = 63, y = 16, zone = "Un’Goro Crater" },
			[27] = { str = "You’re gonna see a bunch of black lakes near the north of the map around #C_[52,23]# Kill the tar monsters around the lakes for #Q_'Super Sticky'# The 3 lakes south of the gorillas around #C_[61,27]# have lower level tar monsters and there is also bloodpetals around here for #Q_'Muigin and Larion'# there is also diametradons and pterrodaxes for #Q_'Shizzle's Flyer'# running around.", x = 61, y = 27, zone = "Un’Goro Crater" },
			[28] = { str = "Stop at #C_[68,36]# and grab the crate of foodstuff for #Q_'Expedition Salvation'#.", x = 68, y = 36, zone = "Un’Goro Crater" },
			[29] = { str = "Try to collect all the stuff for #Q_'Shizzle's Flyer'# out here if you aren’t just going around looking for them alone. I always seem to find them all before I finish the bloodpetals." },
			[30] = { str = "Go to #C_[76,51]# and follow the path up to the pylon for #Q_'The Eastern Pylon'# and there should be pterrodaxes further south at #C_[75,61]#.", x = 76, y = 51, zone = "Un’Goro Crater" },

			[31] = { str = "Go to #C_[71,75]# and turn in' #Q_'The Bait For Lar'Korwi'# and #Q_'The Apes of Un’Goro'# SKIP the next part for now.", x = 71, y = 75, zone = "Un’Goro Crater" },
			[32] = { str = "Now if you grinded a whole lot like I did on those damn flowers and dinosaurs, you should be really close to 52 if not 52 now." },
			[33] = { str = "Just east of the volcano (center of map) there are pterrodaxes all for #Q_'Beware of Pterrordax'# if you’re having trouble finding them there is a spawn of 6 of them all the way south at #C_[55,90]#.", x = 55, y = 90, zone = "Un’Goro Crater" },
			[34] = { str = "Run west to #C_[55,73]# there is a diametradon camp of about 5-6 Kill these if you need scales still for #Q_'Shizzle's Flyer'# or #Q_'Roll the Bones'#.", x = 55, y = 73, zone = "Un’Goro Crater" },
			[35] = { str = "Go west to #C_[50,77]# into the slithering scar, at the fork go left into the big room, stand in the middle, use the scraping vial for #Q_'Alien Ecology'#.", x = 50, y = 77, zone = "Un’Goro Crater" },
			[36] = { str = "There is another diametradon camp if you still need scales or bones for #Q_'Shizzle's Flyer'# or #Q_'Roll the Bones'# and they’re also all over now." },
			[37] = { str = "Run to the camp at #C_[38,65]# and grab the research equipment for #Q_'Expedition Salvation'#.", x = 38, y = 65, zone = "Un’Goro Crater" },
			[38] = { str = "Kill frenzied pterrodaxes all around #C_[35,38]# (they’re everywhere) in the NW part of the map for #Q_'Beware of Pterrordax'# plus there are many diametradons here for #Q_'Shizzle's Flyer'# or #Q_'Roll the Bones'#.", x = 35, y = 38, zone = "Un’Goro Crater" },
			[39] = { str = "Go down to #C_[23,59]# and touch the western pylon for #Q_'The Western Pylon'# and kill any pterrodaxes you need behind it.", x = 23, y = 59, zone = "Un’Goro Crater" },
			[40] = { str = "Go to #C_[30,50]# and accept #Q_'Finding the Source'#.", x = 30, y = 50, zone = "Un’Goro Crater" },

			[41] = { str = "Go over to Fire Plume Ridge at #C_[51,48]# and kill elementals, try to avoid anything 56+ for #Q_'Volcanic Activity'# Leave blazing invaders alone.", x = 51, y = 48, zone = "Un’Goro Crater" },
			[42] = { str = "Once you have that done, dismiss pet and mount up towards the top of the volcano and look for what looks like the instance waiting stones but with fire cracks in it. Dismount and FD then if there is a mob near it put pet on it and use the thermometer for #Q_'Finding the Source'# there is more than one and it doesn’t have to be at the top I see them at the bottom too." },
			[43] = { str = "Unless you need ashes still run to #C_[30,50]# and turn in #Q_'Finding the Source'#. Accept #Q_'The New Springs'#.", x = 30, y = 50, zone = "Un’Goro Crater" },
			[44] = { str = "Go up into the cave (in the same manner) at #C_[51,49]# and turn in #Q_'Lost!'# then accept #Q_'A Little Help From My Friends'# he follows you, once you get him out of the ridge it’s easy. Just go straight out the cave over the edge, if done right you only have to fight 1 element. Once you go north past the river it’s pie.", x = 51, y = 49, zone = "Un’Goro Crater" },
			[45] = { str = "When you get him back to town run up near the sign by the cave and it will complete then turn it in and #Q_'Beware of Pterrordax'#." },
			[46] = { str = "Turn in #Q_'Shizzle's Flyer'#." },
			[47] = { str = "Turn in #Q_'Muigin and Larion'# SKIP the rest." },
			[48] = { str = "Turn in #Q_'Roll the Bones'#." },
			[49] = { str = "Turn in #Q_'Alien Ecology'#." },
			[50] = { str = "Turn in #Q_'Expedition Salvation'#." },

			[51] = { str = "In the back of the cave turn in #Q_'The Northern Pylon'# #Q_'The Eastern Pylon'# #Q_'The Western Pylon'#. Accept #Q_'Making Sense of It'# then turn it back in. She then tells you about buffs from the pylons." },
			[52] = { str = "Run to #C_[29,22]# and follow the path into #A_Silithus# to #C_[50,34]#. Unlock the flight path by talking to the #N_Flight Master# and fly to #A_Gadgetzan# (#A_Tanaris#).", x = 29, y = 22, zone = "Un’Goro Crater" },
			[53] = { str = "Go to the NW part of town, turn in #Q_'Bungle in the Jungle'# SKIP the next part then hand in #Q_'Super Sticky'# between the 2 entrances." },
			[54] = { str = "Use your #I_[Hearthstone]# to return to #A_Darnassus# and talk to your #N_Class Trainer# to learn new spells and abilities." },
			[55] = { str = "You should have at least 50+ soils easy now." },
			[56] = { str = "Go to #C_[31,8]# and turn in #Q_'Un’Goro Soil'#.", x = 31, y = 8, zone = "Darnassus" },
			[57] = { str = "Now go up to the top of the tower and accept #Q_'Morrowgrain Research'# then go downstairs and turn it in, accept #Q_'Morrowgrain Research'#(2)." },
			[58] = { str = "Now you might want to get extra seed packets depending on how many soils you have. You can use the pouch every 10 minutes and you won’t always get a morrowgrain. All you need is 10 anyway." },
			[59] = { str = "Run through to Rut’theran Village and go in the house to the right and accept #Q_'Moontouched Wildkin'# it’s a Winterspring feather quest." },
			[60] = { str = "Fly to #A_Astranaar# (#A_Ashenvale#), then ride all the way east on the road to #C_[91,46]# which goes into #A_Azshara#, it’s far.", x = 91, y = 46, zone = "Ashenvale" },
		}
	},

-----------52-53 Azshara
	[5253] = {
		title = "52-53 Azshara",
		items = {
			[1] = { str = "52-53 Azshara" },
			[2] = { str = "Unlock the flight path by talking to the #N_Flight Master# on the right at #C_[11,77]#", x = 11, y = 77, zone = "Azshara" },
			[3] = { str = "Just behind him, accept #Q_'Spiritual Unrest'# and #Q_'A Land Filled With Hatred'#." },
			[4] = { str = "Go just north to around #C_[14,72]# and #C_[16,67]#and kill all the ghosts around here until you complete #Q_'Spiritual Unrest'#.", x = 14, y = 72, zone = "Azshara" },
			[5] = { str = "Go just north to #C_[19,61]# and kill all the satyr’s around here for #Q_'A Land Filled With Hatred'#.", x = 19, y = 61, zone = "Azshara" },
			[6] = { str = "Go back to #C_[11,77]# and turn in #Q_'Spiritual Unrest'# and #Q_'A Land Filled With Hatred'#.", x = 11, y = 77, zone = "Azshara" },
			[7] = { str = "Go to #C_[39,55]# and get the Markri rubbing for #Q_'Arcane Runes'#.", x = 39, y = 55, zone = "Azshara" },
			[8] = { str = "Go to #C_[36,53]# and get the Beth’Amara Rubbing for #Q_'Arcane Runes'#.", x = 36, y = 53, zone = "Azshara" },
			[9] = { str = "Go to #C_[39,50]# and get the Jin’yael rubbing for #Q_'Arcane Runes'#.", x = 39, y = 50, zone = "Azshara" },
			[10] = { str = "Go to #C_[42,42]# and turn in #Q_'The Hunter's Charm'# accept #Q_'Courser Antlers'# this quest and the follow up are optional to do after you turn 53, I do them so if you don’t you’ll be behind a little on the guide. It takes about 1-2 hours unless you get lucky, to get all the pieces for this and the next quest but will put you about 20-25% into the level.", x = 42, y = 42, zone = "Azshara" },
		}
	},

------------53-54 Felwood
	[5354] = {
		title = "53-54 Felwood",
		items = {
			[1] = { str = "53-54 Felwood" },
			[2] = { str = "Stop at #C_[54,86]# and accept #Q_'Cleansing Felwood'#.", x = 54, y = 86, zone = "Felwood" },
			[3] = { str = "Run north a little bit to #C_[51,81]# and accept #Q_'Forces of Jaedenar'#.", x = 51, y = 81, zone = "Felwood" },
			[4] = { str = "Inside the house, accept #Q_'The Corruption of the Jadefire'#." },
			[5] = { str = "Under the tent accept #Q_'Verifying the Corruption'# and #Q_'To Winterspring!'#." },
			[6] = { str = "Just across the road accept #Q_'Timbermaw Ally'#." },
			[7] = { str = "Go just SW of here around #C_[48,91]# and kill the Furlbogs until you finish #Q_'Timbermaw Ally'# Just grind em all for rep until you’re done.", x = 48, y = 91, zone = "Felwood" },
			[8] = { str = "Go back to #C_[50,85]# and turn in #Q_'Timbermaw Ally'# accept #Q_'Speak to Nefian'# the other is repeatable for rep.", x = 50, y = 85, zone = "Felwood" },
			[9] = { str = "Go up near the 2 lakes at #C_[40,69]# and kill the cursed oozes for the first part of #Q_'A Little Slime Goes A Long Way'#.", x = 40, y = 69, zone = "Felwood" },
			[10] = { str = "Go to the west of here now to #C_[37,69]# and kill the jadefire demons for #Q_'The Corruption of the Jadefire'# these are good to farm too.", x = 37, y = 69, zone = "Felwood" },

			[11] = { str = "Go up to #C_[39,59]# and kill the tainted oozes for the second part of #Q_'A Little Slime Goes A Long Way'#.", x = 39, y = 59, zone = "Felwood" },
			[12] = { str = "Go just west of here around #C_[37,59]# and kill the Jaedenar for #Q_'Forces of Jaedenar'# You don’t have to go in the caves.", x = 37, y = 59, zone = "Felwood" },
			[13] = { str = "Go back to #C_[51,82]# and turn in #Q_'Forces of Jaedenar'# accept #Q_'Collection of the Corrupt Water'#.", x = 51, y = 82, zone = "Felwood" },
			[14] = { str = "Inside the house turn in #Q_'The Corruption of the Jadefire'# accept #Q_'Further Corruption'#." },
			[15] = { str = "Go back up to Jaedenar to the green pool at #C_[35,59]# and fill the canteen for #Q_'Collection of the Corrupt Water'#.", x = 35, y = 59, zone = "Felwood" },
			[16] = { str = "Go back to #C_[51,82]# and turn in #Q_'Collection of the Corrupt Water'# accept #Q_'Seeking Spiritual Aid'#.", x = 51, y = 82, zone = "Felwood" },
			[17] = { str = "Go up to #C_[42,20]# and kill Entropic beasts and horrors and explore the craters for #Q_'Verifying the Corruption'#.", x = 42, y = 20, zone = "Felwood" },
			[18] = { str = "Go up to #C_[46,14]# and follow it to the back, killing the demons for #Q_'Further Corruption'# When you kill Xavaric he'll drop Flute of Xavaric which starts #Q_'Flute of Xavaric'# kill the satyr’s now to complete this.", x = 46, y = 14, zone = "Felwood" },
			[19] = { str = "Run over to Irontree Cavern at #C_[55,17]# and kill 15 of the elementals and that should be enough for #Q_'Cleansing Felwood'#.", x = 55, y = 17, zone = "Felwood" },
			[20] = { str = "Go up to #C_[62,24]#. Unlock the flight path by talking to the #N_Flight Master#.", x = 62, y = 24, zone = "Felwood" },

			[21] = { str = "Go north to #C_[64,8]# and turn in #Q_'Speak to Nefian'# accept #Q_'Deadwood of the North'#.", x = 64, y = 8, zone = "Felwood" },
			[22] = { str = "Now fall off the cliff to the west and start killing for #Q_'Deadwood of the North'# once you’re done you want to kill until you’re 150 rep from the next rank with the timbermaw (put the rep as an xp bar for ease)." },
			[23] = { str = "Go back to #C_[64,8]# and turn in #Q_'Deadwood of the North'# and you should be unfriendly now and not aggro’d any longer. Accept #Q_'Speak to Salfa'# and turn in any 5 sets of feathers for extra rep and 550 xp.", x = 64, y = 8, zone = "Felwood" },
			[24] = { str = "Go through the cave to Winterspring and just outside the cave to the right at #C_[27,34]# turn in #Q_'Speak to Salfa'#.", x = 27, y = 34, zone = "Winterspring" },
			[25] = { str = "Run south to #C_[31,45]# and turn in #Q_'The New Springs'# accept #Q_'Strange Sources'# also turn in #Q_'It's A Secret to Everybody'#(3) accept #Q_'The Videre Elixir'# and #Q_'Threat of the Winterfall'#.", x = 31, y = 45, zone = "Winterspring" },
			[26] = { str = "Run back throug the cave and go west at the fork into Moonglade." },
			[27] = { str = "Go to #C_[48,67]#. Unlock the flight path by talking to the #N_Flight Master#.", x = 48, y = 67, zone = "Moodglade" },
			[28] = { str = "You should be a hair from leveling now. You can kill something or just wait. Use your #I_[Hearthstone]# to return to #A_Astranaar# (#A_Ashenvale#) and fly to Feralas." },
			[29] = { str = "Go in the Inn, accept #Q_'Jonespyre's Request'#." },
			[30] = { str = "Go up to the top of the tower, turn it in, accept #Q_'The Mystery of Morrowgrain'# turn it back in unless you’re still making the stuff. If you don’t have enough no big deal during this guide I didn’t have enough." },

			[31] = { str = "Go up to #C_[45,25]# and buy a bait and read on how to get #Q_'The Videre Elixir'#.", x = 45, y = 25, zone = "Feralas" },
			[32] = { str = "At #C_[45,16]# you can be put up to the top of the colossal tower and parachute down. Just make sure you unmount, I forgot about that and smashed a crater in the ground.", x = 45, y = 16, zone = "Feralas" },
			[33] = { str = "Go up to #C_[44,10]# and place the bait on the ground then go loot an everroot.", x = 44, y = 10, zone = "Felalas" },
			[34] = { str = "Go back south to #C_[45,25]# to get your 3 videre elixir.", x = 45, y = 25, zone = "Felalas" },
			[35] = { str = "Use your #I_[Hearthstone]# to return to #A_Astranaar# (#A_Ashenvale#)." },
			[36] = { str = "Run back up into Felwood to #C_[54,86]# and turn in #Q_'Cleansing Felwood'#.", x = 54, y = 86, zone = "Felwood" },
			[37] = { str = "Now she allows you to get stuff for some neat potions that are on different cooldowns than potions are." },
			[38] = { str = "Go up to #C_[51,81]# and in the house turn in #Q_'Further Corruption'# and #Q_'Flute of Xavaric'# accept #Q_'Felbound Ancients'#.", x = 51, y = 81, zone = "Felwood" },
			[39] = { str = "Under the tent, turn in #Q_'Verifying the Corruption'#." },
			[40] = { str = "Run up to #C_[62,23]#.", x = 62, y = 23, zone = "Felwood" },

			[41] = { str = "Go through the cave to Winterfall and just outside the cave accept #Q_'Winterfall Activity'#." },
			[42] = { str = "Go to #C_[31,45]# and turn in #Q_'The Videre Elixir'# accept #Q_'Meet at the Grave'#.", x = 31, y = 45, zone = "Winterspring" },
			[43] = { str = "Go to #C_[62,36]#. Unlock the flight path by talking to the #N_Flight Master#.", x = 62, y = 36, zone = "Winterspring" },
			[44] = { str = "Fly to #A_Ratchet# (#A_The Barrens#)." },
			[45] = { str = "Run west of the dock and turn in #Q_'Volcanic Activity'#." },
			[46] = { str = "Run down to #C_[65,43]# and turn in #Q_'Seeking Spiritual Aid'# accept #Q_'Cleansed Water Returns to Felwood'#.", x = 65, y = 43, zone = "The Barrens" },
			[47] = { str = "Fly to #A_Theramore# (#A_Dustwallow Marsh#) and boat to #A_Menethil Harbor# (#A_The Wetlands#) then fly to #A_Ironforge#." },
			[48] = { str = "Just outside the military ward there should be a wandering npc, one is near flight path too, grab the quest #Q_'The New Frontier'#." },
			[49] = { str = "Go to #C_[75,23]# and turn in #Q_'A Little Slime Goes A Long Way'# accept #Q_'A Little Slime Goes A Long Way'#(2).", x = 75, y = 23, zone = "Ironforge" },
			[50] = { str = "Go to #C_[31,4]# and turn in #Q_'Return to Tymor'# see it was worth the run.", x = 31, y = 4, zone = "Ironforge" },

			[51] = { str = "Fly to #A_Menethil Harbor# (#A_The Wetlands#) then boat to #A_Theramore# (#A_Dustwallow Marsh#) and fly to #A_Gadgetzan# (#A_Tanaris#)." },
		}
	},

-----------54-54 Tanaris
	[5453] = {
		title = "54-54 Tanaris",
		items = {
			[1] = { str = "54-54 Tanaris" },
			[2] = { str = "Get your mithril casing out of your bank or mailbox." },
			[3] = { str = "Go east to the #A_Graveyard# at #C_[54,28]# and drink your videre elixir.", x = 54, y = 28, zone = "Tanaris" },
			[4] = { str = "Now you’re gonna die, don’t rez just release and run north to #C_[53,23]# and turn in #Q_'Meet at the Grave'# accept #Q_'A Grave Situation'#.", x = 53, y = 23, zone = "Tanaris" },
			[5] = { str = "Go back and rez at #C_[54,28]# and touch the only tombstone there, turn in #Q_'A Grave Situation'# accept #Q_'Linken's Sword'#.", x = 54, y = 28, zone = "Tanaris" },
			[6] = { str = "Run into Un’Goro, I’d say fly but we have to go way SE." },
			[7] = { str = "Run up to #C_[71,75]# and accept #Q_'The Mighty U'cha'#.", x = 71, y = 75, zone = "Un’Goro" },
			[8] = { str = "Keep collecting dirt here if you need more morrowgrain." },
			[9] = { str = "Now all around the crater is slimes but you can find all the ones you need west of the volcano around #C_[37,37]# for #Q_'A Little Slime Goes A Long Way'#(2) I think there are more on the west side of the volcano but you can look on both sides they’re scattered. If it says they’re cloning, finish them very fast or stun them. If they clone it’s a full health mob that you can’t scoop up.", x = 37, y = 37, zone = "Un’Goro" },
			[10] = { str = "Go to the cave at #C_[64,16]# and go to the right, when you see A-Me 01 accept #Q_'Chasing A-Me 01'# and turn it back in. Fall over the edge and to the right and up around until you see U’cha for #Q_'The Mighty U'cha'#.", x = 64, y = 16, zone = "Un’Goro" },

			[11] = { str = "Run back to the front and go right again and accept #Q_'Chasing A-Me 01'#(2) now escort her out." },
			[12] = { str = "Escort A-Me to Marshal’s at #C_[46,13]# and turn in #Q_'Chasing A-Me 01'#(2).", x = 46, y = 13, zone = "Un’Goro" },
			[13] = { str = "Go into Marshal’s and turn in #Q_'Linken's Sword'# accept #Q_'A Gnome's Assistance'#." },
			[14] = { str = "Go to the back of the cave and turn in #Q_'A Gnome's Assistance'# and accept #Q_'Linken’s Memory'#." },
			[15] = { str = "Run down and let the tar monsters kill you so you’re closer to the SE." },
			[16] = { str = "Run down to #C_[71,75]# and turn in #Q_'The Mighty U'cha'#.", x = 71, y = 75, zone = "Un’Goro" },
			[17] = { str = "You should be over half way to 55 now." },
			[18] = { str = "Use your #I_[Hearthstone]# to return to back to #A_Astranaar# (#A_Ashenvale#) and fly to #A_Darnassus#." },
			[19] = { str = "Go in the Temple of the Moon at #C_[39,84]# and fill the vial for #Q_'Felbound Ancients'#.", x = 39, y = 84, zone = "Darnassus" },
			[20] = { str = "Run into Felwood." },
		}
	},

-----------54-54 Felwood
	[5454] = {
		title = "54-54 Felwood",
		items = {
			[1] = { str = "54-54 Felwood" },
			[2] = { str = "Go to #C_[51,82]# and turn in #Q_'Cleansed Water Returns to Felwood'# accept #Q_'Dousing the Flames of Protection'#.", x = 51, y = 82, zone = "Felwood" },
			[3] = { str = "Go in the house, turn in #Q_'Felbound Ancients'# accept #Q_'Purified!'# then turn it back in, easy 10k xp. Also turn in #Q_'Linken’s Memory'# accept #Q_'Silver Heart'#." },
			[4] = { str = "You should be 70% through now or close to it." },
			[5] = { str = "Start killing all the bears and wolves from here north until you have 11 silvery clawas for #Q_'Silver Heart'#." },
			[6] = { str = "Go into the cave at #C_[35,58]#.", x = 35, y = 58, zone = "Felwood" },
			[7] = { str = "At the first open area with the caged npc at #C_[36,56]# is brazier for #Q_'Dousing the Flames of Protection'# the 2nd one is just up the ramp.", x = 36, y = 56, zone = "Felwood" },
			[8] = { str = "Continue past the room with candles surrounding the hole to the next open room at #C_[36,53]# for the 3rd and 4th brazier for #Q_'Dousing the Flames of Protection'#.", x = 36, y = 53, zone = "Felwood" },
			[9] = { str = "Don’t even bother trying to do the escort unless you get a group, I always skip it even if I find the key." },
			[10] = { str = "Run back outside and up to #C_[51,19]# and kill the tree elementals for #Q_'Silver Heart'#.", x = 51, y = 19, zone = "Felwood" },

			[11] = { str = "If you want to do the escort with the flute I suggest getting a group you get jumped by a lot of mobs." },
			[12] = { str = "Run All the way back down to #C_[51,82]# (I know no one wants to run back here, why the quest hub is so far from the flight path is beyond me).", x = 51, y = 82, zone = "Felwood" },
			[13] = { str = "Turn in #Q_'Dousing the Flames of Protection'# SKIP the next part for now." },
			[14] = { str = "In the house turn in #Q_'Silver Heart'# accept #Q_'Aquementas'#." },
			[15] = { str = "If you have skinning I’m sure you have at least 5 tainted hides, go down to #C_[54,86]# and turn them in for #Q_'Salve via Skinning'#.", x = 54, y = 86, zone = "Felwood" },
			[16] = { str = "Use your #I_[Hearthstone]# to return to #A_Astranaar# (#A_Ashenvale#) and fly to Winterspring." },
		}
	},

--------------54-55 Winterspring
	[5455] = {
		title = "54-55 Winterspring",
		items = {
			[1] = { str = "54-55 Winterspring" },
			[2] = { str = "Go in #A_Everlook# (#A_Winterspring#) accept #Q_'Enraged Wildkin'#." },
			[3] = { str = "Go in the Inn. Talk to the #N_Innkeeper# to make #A_Everlook# (#A_Winterspring#) your home." },
			[4] = { str = "Accept #Q_'The Everlook Report'# #Q_'Duke Nicholas Zverenhoff'# and #Q_'Sister Pamela'#." },
			[5] = { str = "On the other side of town accept #Q_'Are We There, Yeti?'#." },
			[6] = { str = "Keep your eye out for those blue moonkin feathers to finish up #Q_'Moontouched Wildkin'#." },
			[7] = { str = "Run All the way south to #C_[60,73]# to complete #Q_'Strange Sources'#.", x = 60, y = 73, zone = "Winterspring" },
			[8] = { str = "Use your #I_[Hearthstone]# to return to back to #A_Everlook# (#A_Winterspring#), if it’s not up die on purpose." },
			[9] = { str = "Go to #C_[65,45]# and kill yeti’s for #Q_'Are We There, Yeti?'#.", x = 65, y = 45, zone = "Winterspring" },
			[10] = { str = "Run back to #A_Everlook# (#A_Winterspring#) and turn in #Q_'Are We There, Yeti?'# accept #Q_'Are We There, Yeti?'#(2)." },

			[11] = { str = "Go back to #C_[65,45]# and kill matriarch’s and patriarch’s for #Q_'Are We There, Yeti?'#(2) there are a lot in the cave at #C_[67,42]#.", x = 67, y = 42, zone = "Winterspring" },
			[12] = { str = "Run back to #A_Everlook# (#A_Winterspring#) and turn in #Q_'Are We There, Yeti?'#(2) accept #Q_'Are We There, Yeti?'#(3)." },
			[13] = { str = "Go just east of the Inn and scare Legacki for #Q_'Are We There, Yeti?'#(3)." },
			[14] = { str = "Go east of Winterspring to #C_[66,34]# and kill the furlbogs there for #Q_'Winterfall Activity'# and part of #Q_'Threat of the Winterfall'#.", x = 66, y = 34, zone = "Winterspring" },
			[15] = { str = "Hopefully you’ll find an Empty Firewater Flask on one of them which starts #Q_'Winterfall Firewater'#." },
			[16] = { str = "Run up to Starfall Village at #C_[51,30]# and turn in #Q_'To Winterspring!'# accept #Q_'The Ruins of Kel'Theril'#.", x = 51, y = 30, zone = "Winterspring" },
			[17] = { str = "Turn in #Q_'Enraged Wildkin'# SKIP(2) for now also turn in #Q_'The Ruins of Kel'Theril'# accept #Q_'Troubled Spirits of Kel'Theril'#." },
			[18] = { str = "Grab the relic at #C_[55,42]# for #Q_'Troubled Spirits of Kel'Theril'# dismiss pet before you open them then run and FD. 2nd relic is at #C_[53,43]#. 3rd at #C_[52,41]# 4th at #C_[50,41]#." },
			[19] = { str = "Go west to #C_[39,43]# and kill furlbog here for #Q_'Threat of the Winterfall'# also make sure you have your 10 feathers for #Q_'Moontouched Wildkin'#.", x = 39, y = 43, zone = "Winterspring" },
			[20] = { str = "Go to #C_[31,45]# and turn in #Q_'Strange Sources'# #Q_'Threat of the Winterfall'# and #Q_'Winterfall Firewater'# accept #Q_'Falling to Corruption'#.", x = 31, y = 45, zone = "Winterspring" },

			[21] = { str = "Run to #C_[27,34]# and turn in #Q_'Winterfall Activity'#.", x = 27, y = 34, zone = "Winterspring" },
			[22] = { str = "You should now be 25-30% into 55." },
			[23] = { str = "Run through the tunnel to Felwood." },
			[24] = { str = "Go to #C_[60,5]# and touch the cauldron at the camp which turns in #Q_'Falling to Corruption'# accept #Q_'Mystery Goo'#.", x = 60, y = 5, zone = "Winterspring" },
			[25] = { str = "Use your #I_[Hearthstone]# to return to #A_Everlook# (#A_Winterspring#) then fly to #A_Darnassus#." },
			[26] = { str = "In Rut’theran Village turn in #Q_'Moontouched Wildkin'# #C_[55,92]# accept #Q_'Find Ranshalla'#.", x = 55, y = 92, zone = "Darnassus" },
			[27] = { str = "Go into #A_Darnassus# up to #C_[34,8]# in the big tower and turn in #Q_'The New Frontier'# accept #Q_'The New Frontier'#(2) go down 1 floor and turn that in, accept #Q_'Rabine Saturna'#.", x = 34, y = 8, zone = "Darnassus" },
			[28] = { str = "Fly to Moonglade to #C_[51,45]# and turn in #Q_'Rabine Saturna'# accept #Q_'Wasteland'#.", x = 51, y = 45, zone = "Moonglade" },
			[29] = { str = "Fly to #A_Auberdine# (#A_Darkshore#), boat to #A_Menethil Harbor# (#A_The Wetlands#) and fly to #A_Ironforge#. Talk to the #N_Innkeeper# to make #A_Ironforge# your home. Make sure you have your black dragonflight molt." },
			[30] = { str = "Go to #C_[75,23]# and turn in #Q_'A Little Slime Goes A Long Way'#(2).", x = 75, y = 23, zone = "Ironforge" },

			[31] = { str = "Go to #C_[38,55]# in the throne room and accept #Q_'The Smoldering Ruins of Thaurissan'# then click on her and listen to the story and turn it back in, accept #Q_'The Smoldering Ruins of Thaurissan'#(2).", x = 38, y = 55, zone = "Ironforge" },
			[32] = { str = "In front of the flight path accept #Q_'Taking Back Silithus'#." },
			[33] = { str = "Fly to #A_Lakeshire# (#A_Redridge Mountains#)." },
			[34] = { str = "Run north to #C_[46,6]# and enter the #A_Burning Steppes#.", x = 46, y = 6, zone = "Redridge Mountains" },
		}
	},

-----------55-56 Burning Steppes
	[5556] = {
		title = "55-56 Burning Steppes",
		items = {
			[1] = { str = "55-56 Burning Steppes" },
			[2] = { str = "Go to #C_[83,63]# and follow the path up. Unlock the flight path by talking to the #N_Flight Master#.", x = 83, y = 63, zone = "Burning Steps" },
			[3] = { str = "Accept #Q_'Extinguish the Firegut'# and #Q_'FIFTY! YEP!'#." },
			[4] = { str = "In front of the broken house, accept #Q_'Dragonkin Menace'# This is the start of the ony key chain." },
			[5] = { str = "Start killing ogres all over the mountain at #C_[81,42]# for #Q_'Extinguish the Firegut'# then run back to #C_[84,68]# and turn it in, accept #Q_'Gor'tesh the Brute Lord'#.", x = 81, y = 42, zone = "Burning Steps" },
			[6] = { str = "Go NW to around #C_[66,40]# and collect the ruins that look like tombstones for #Q_'The Smoldering Ruins of Thaurissan'#(2).", x = 66, y = 40, zone = "Burning Steps" },
			[7] = { str = "Run up to #C_[65,24]# and go in the cave, turn in #Q_'Yuka Screwspigot'# SKIP the rest.", x = 65, y = 24, zone = "Burning Steps" },
			[8] = { str = "Outside accept #Q_'Tablet of the Seven'# and #Q_'Broodling Essence'#." },
			[9] = { str = "Go to #C_[54,40]# and touch the dwarf statue for #Q_'Tablet of the Seven'#.", x = 54, y = 40, zone = "Burning Steps" },
			[10] = { str = "Go west to #C_[43,46]# to blackrock stronghold or south to #C_[49,55]# the pillar of ash and kill the orcs for #Q_'FIFTY! YEP!'# they drop in large amounts.", x = 43, y = 46, zone = "Burning Steps" },

			[11] = { str = "While in the pillar of ash at #C_[40,56]# you should kill Gor’tesh for #Q_'Gor'tesh the Brute Lord'#.", x = 40, y = 56, zone = "Burning Steps" },
			[12] = { str = "Get a group if you can for #Q_'Dragonkin Menace'# and then kill the mobs for it just ne of the camp along the east wall. It’s soloable but cutting it Also get 8 of the broodlings for #Q_'Broodling Essence'# by using the device on them before you attack them." },
			[13] = { str = "Go to the cave at #C_[94,31]# and accept #Q_'A Taste of Flame'# then give him the molt and hand the quest back in. SKIP the next part.", x = 94, y = 31, zone = "Burning Steps" },
			[14] = { str = "Run back up to #C_[65,23]# and turn in #Q_'Tablet of the Seven'# and #Q_'Broodling Essence'# accept #Q_'Felnok Steelspring'#.", x = 65, y = 23, zone = "Burning Steps" },
			[15] = { str = "Ride back to #C_[84,68]# and next to the griffin turn in #Q_'FIFTY! YEP!'# and #Q_'Gor'tesh the Brute Lord'# accept #Q_'Ogre Head On A Stick = Party'#.", x = 84, y = 68, zone = "Burning Steps" },
			[16] = { str = "In front of the broken house, turn in #Q_'Dragonkin Menace'# accept #Q_'The True Masters'#." },
			[17] = { str = "Run up to the top of the mountin at #C_[80,45]# and click the soft dirt pile for #Q_'Ogre Head On A Stick = Party'# then run back to #C_[84,68]# and turn it in.", x = 80, y = 45, zone = "Burning Steps" },
			[18] = { str = "Fly to #A_Lakeshire# (#A_Redridge Mountains#) and run to the town hall at #C_[29,44]# and turn in #Q_'The True Masters'# accept #Q_'The True Masters'#(2).", x = 29, y = 44, zone = "Redridge Mountains" },
			[19] = { str = "Fly to #A_Stormwind#." },
			[20] = { str = "Go to #C_[78,18]# into the #A_Stormwind# keep and turn in #Q_'The True Masters'#(2) accept #Q_'The True Masters'#(3) then talk to the lady and then turn it back in and accept #Q_'The True Masters'#(4).", x = 78, y = 18, zone = "Stormwind City" },

			[21] = { str = "Fly back to #A_Lakeshire# (#A_Redridge Mountains#) and go to the townhall at #C_[29,44]# and turn in #Q_'The True Masters'#(4) accept #Q_'The True Masters'#(5).", x = 29, y = 44, zone = "Redridge Mountains" },
			[22] = { str = "Fly to the #A_Morgan's Vigil# (#A_Burning Steppes#) and turn in #Q_'The True Masters'#(5) when you land and accept #Q_'The True Masters'#(6)." },
			[23] = { str = "Run up to #C_[64,23]# and listen to ragged john then run back to #C_[84,68]# and turn in #Q_'The True Masters'#(6) I SKIP the next part, do it later if you’re worried about speed leveling. That was an easy 30k xp for doing nothing and your ony key chain is started.", x = 64, y = 23, zone = "Burning Steps" },
			[24] = { str = "You should be about 10k from 56, go grind until 5k on the orcs at #C_[49,55]#.", x = 49, y = 55, zone = "Burning Steps" },
			[25] = { str = "Use your #I_[Hearthstone]# to return to #A_Ironforge#." },
			[26] = { str = "Go to the throne room at #C_[38,55]# and turn in #Q_'The Smoldering Ruins of Thaurissan'#(2).", x = 38, y = 55, zone = "Ironforge" },
			[27] = { str = "You should now be 56, talk to your #N_Class Trainer# to learn new spells and abilities." },
			[28] = { str = "Fly to #A_Menethil Harbor# (#A_The Wetlands#) and boat to #A_Theramore# (#A_Dustwallow Marsh#)." },
			[29] = { str = "Fly to #A_Gadgetzan# (#A_Tanaris#)." },
		}
	},

-----------56-56 Tanaris
	[5655] = {
		title = "56-56 Tanaris",
		items = {
			[1] = { str = "56-56 Tanaris" },
			[2] = { str = "Go to the NW side of town and scare sprinkle for #Q_'Are We There, Yeti?'#(3)." },
			[3] = { str = "Talk to the #N_Innkeeper# to make #A_Gadgetzan# (#A_Tanaris#) your home." },
			[4] = { str = "To the south of lost rigger cove at #C_[70,49]# is a bunch of stones in a circle, Loot the stuff from the blue backpack and use the book to summon Aquementas He’s a level 54 water elemental pansy.", x = 70, y = 49, zone = "Tanaris" },
			[5] = { str = "Use your #I_[Hearthstone]# to return to #A_Gadgetzan# (#A_Tanaris#) or die if it’s not up yet." },
			[6] = { str = "Fly to Un’goro." },
			[7] = { str = "Find Quixxil and scare him for #Q_'Are We There, Yeti?'#(3)." },
			[8] = { str = "Go to the back of the cave and turn in #Q_'Aquementas'# accept #Q_'Linken's Adventure'# and turn it in just outside the cave by the big tree SKIP the next part." },
			[9] = { str = "Fly to #A_Cenarion Hold# (#A_Silithus#)." },
		}
	},

-----------56-56 Silithus
	[5656] = {
		title = "56-56 Silithus",
		items = {
			[1] = { str = "56-56 Silithus" },
			[2] = { str = "Near the moonwell accept #Q_'The Twilight Mystery'#." },
			[3] = { str = "In front of the Inn, turn in #Q_'Taking Back Silithus'# accept #Q_'Securing the Supply Lines'#." },
			[4] = { str = "SKIP the quest on the sign unless you get a group." },
			[5] = { str = "Talk to the #N_Innkeeper# to make #A_Cenarion Hold# (#A_Silithus#) your home." },
			[6] = { str = "Upstairs accept #Q_'Deadly Desert Venom'#." },
			[7] = { str = "There seems to be a lot of white ! because that’s a lot of AQ stuff you don’t have to worry about yet." },
			[8] = { str = "Go do #Q_'Securing the Supply Lines'# and #Q_'Deadly Desert Venom'# North and NE of town all around #C_[55,24]# the dredges, scorpids, and skitterers for these 2 quests are all over this area.", x = 55, y = 24, zone = "Silithus" },
			[9] = { str = "Run up to #C_[81,18]# and turn in #Q_'Wasteland'# accept #Q_'The Spirits of Southwind'#.", x = 81, y = 18, zone = "Silithus" },
			[10] = { str = "Run up NW to around 22.9 and pick up the twilight tablet fragments for #Q_'The Twilight Mystery'# They litter this spot.", x = 22, y = 9, zone = "Silithus" },

			[11] = { str = "Use your #I_[Hearthstone]# to return to Cenarion Hold." },
			[12] = { str = "Up stairs turn in #Q_'Deadly Desert Venom'# accept #Q_'Noggle's Last Hope'#." },
			[13] = { str = "In front of the Inn, turn in #Q_'Securing the Supply Lines'# accept #Q_'Stepping Up Security'#." },
			[14] = { str = "Go next to the moonwell and turn in #Q_'The Twilight Mystery'# accept #Q_'The Deserter'#." },
			[15] = { str = "You should be about 30-35% into 56." },
			[16] = { str = "Go SE to #C_[62,53]# and kill the undead guys here for #Q_'The Spirits of Southwind'# becareful when they die they spawn 1-2 bugs.", x = 62, y = 53, zone = "Silithus" },
			[17] = { str = "Kill the pincers for #Q_'Noggle's Last Hope'# and drudges for #Q_'The Deserter'# south of here around #C_[56,58]#.", x = 56, y = 58, zone = "Silithus" },
			[18] = { str = "Go to the cave at #C_[67,69]# and turn in #Q_'The Deserter'# accept #Q_'The Twilight Lexicon'#.", x = 67, y = 69, zone = "Silithus" },
			[19] = { str = "You can find flayers and stalkers outside of the cave for #Q_'Noggle's Last Hope'# they are also both around #C_[43,72]# on the other side of the hive.", x = 43, y = 72, zone = "Silithus" },
			[20] = { str = "Use your #I_[Hearthstone]# to return to back to Cenarion Hold or die so you end up there." },

			[21] = { str = "Go upstairs and turn in for #Q_'Noggle's Last Hope'# accept #Q_'Noggle's Lost Satchel'#." },
			[22] = { str = "Outside the Inn, turn in #Q_'Stepping Up Security'#." },
			[23] = { str = "Go to #C_[29,35]# and kill Twilight Keeper Manya for #Q_'The Twilight Lexicon'# she fears a bit. She’s at the SE corner of came.", x = 29, y = 35, zone = "Silithus" },
			[24] = { str = "Go to #C_[41,41]# and kill Twilight Keeper Havanuth for #Q_'The Twilight Lexicon'# he’s on the east side of camp, he has a nasty aoe.", x = 41, y = 41, zone = "Silithus" },
			[25] = { str = "Go all the way down south to the little camp at #C_[42,90]# and go up the hill behind it, you’ll find Deathclasp, in the middle of the path on the wall is a pouch, grab it when deathclasp is in the back for #Q_'Noggle's Lost Satchel'#.", x = 42, y = 90, zone = "Silithus" },
			[26] = { str = "Head to the SW to #C_[16,87]# and kill Twilight Keeper Exeter for #Q_'The Twilight Lexicon'# he’s at the SW corner of camp.", x = 16, y = 87, zone = "Silithus" },
			[27] = { str = "Go back to the cave at #C_[67,69]# and turn in #Q_'The Twilight Lexicon'# accept #Q_'A Terrible Purpose'# He also offers another quest for 10 twilight texts, this is more for cen circle rep later on.", x = 67, y = 69, zone = "Silithus" },
			[28] = { str = "Run up to #C_[81,18]# and turn in #Q_'The Spirits of Southwind'# accept #Q_'Hive in the Tower'#.", x = 81, y = 18, zone = "Silithus" },
			[29] = { str = "Go to the top of the tower at #C_[61,52]# Be careful 3 bugs spawn when you enter. Shift right click the pod because as soon as you open it some amushers spawn. Kill at least 1 and loot it for #Q_'Hive in the Tower'#.", x = 61, y = 52, zone = "Silithus" },
			[30] = { str = "Go up to #C_[81,18]# and turn in #Q_'Hive in the Tower'# accept #Q_'Umber, Archivist'#.", x = 81, y = 18, zone = "Silithus" },

			[31] = { str = "Use your #I_[Hearthstone]# to return to Cenarion Hold." },
			[32] = { str = "Ignore." },
			[33] = { str = "Go upstairs and turn in #Q_'Noggle's Lost Satchel'#." },
			[34] = { str = "Go into the long building and turn in #Q_'A Terrible Purpose'#." },
			[35] = { str = "Fly to Moonglade." },
			[36] = { str = "Go to #C_[44,35]# and turn in #Q_'Umber, Archivist'# accept #Q_'Uncovering Past Secrets'#.", x = 44, y = 35, zone = "Moonglade" },
			[37] = { str = "Run over to #C_[51,44]# and turn in #Q_'Uncovering Past Secrets'#.", x = 44, y = 35, zone = "Moonglade" },
			[38] = { str = "You should now be 80-85% into leveling." },
			[39] = { str = "Fly to #A_Auberdine# (#A_Darkshore#) and boat to #A_Menethil Harbor# (#A_The Wetlands#) then fly to #A_Ironforge#." },
			[40] = { str = "Talk to the #N_Innkeeper# to make #A_Ironforge# your home. Find the wandering commander dwarf and accept #Q_'A Call To Arms: The Plaguelands!'#" },

			[41] = { str = "Fly to #A_Southshore# (#A_Hillsbrad Foothills#)." },
			[42] = { str = "Run north into Alterac Mountains and over NE to #C_[80,34]# and run into Western Plaguelands (WPL).", x = 80, y = 34, zone = "Alterac Mountains" },
		}
	},

------------56-57 Western Plaguelands
	[5657] = {
		title = "56-57 Western Plaguelands",
		items = {
			[1] = { str = "56-57 Western Plaguelands" },
			[2] = { str = "Next to the shack accept #Q_'A Plague Upon Thee'#." },
			[3] = { str = "Unlock the flight path by talking to the #N_Flight Master#." },
			[3] = { str = "Whenever you come back to camp here always check the vendor for the stormshroud pants recipe. It’s like 1.3g and you can easily sell it for 10 or 20g+ It’s a limited recipe that restocks 1 every hour." },
			[4] = { str = "Go to the tent and turn in #Q_'A Call To Arms: The Plaguelands!'#, accept #Q_'Clear The Way'#." },
			[5] = { str = "Go to the 3 Argent Dawn people near the other tent and turn in #Q_'The Everlook Report'# and also complete #Q_'Argent Dawn Commission'# it’s not a quest you had she just uses it to give you the trinket which you should always wear when in WPL and EPL because it gives you AD rep and allows the scourge tokens to drop, which she also has 3 new quests on those for turn ins. You most likely won’t get anything past the first quest as the rest are mainly in the instances." },
			[6] = { str = "Save the tokens until I say to hand em in." },
			[7] = { str = "Go NE to around #C_[51,78]# and grind the ghouls here until you got enough for #Q_'Clear The Way'#.", x = 51, y = 78, zone = "Western Plaguelands" },
			[8] = { str = "Go back to Chillwind Camp at #C_[42,84]# and turn in #Q_'Clear The Way'# accept #Q_'All Along the Watchtowers'# and #Q_'The Scourge Cauldrons'#.", x = 42, y = 84, zone = "Western Plaguelands" },
			[9] = { str = "Turn around and turn in #Q_'The Scourge Cauldrons'# accept #Q_'Target: Felstone Field'#." },
			[10] = { str = "You should now be about 5-10k from 57." },

			[11] = { str = "Go back NE to #C_[48,72]# and go over the bridge.", x = 48, y = 72, zone = "Western Plaguelands" },
			[12] = { str = "Just in the town on the left at #C_[47,71]# is the 4th tower for #Q_'All Along the Watchtowers'#, there are elites inside but you can stand out of LOS on the edge and mark the doors easily. 1st tower West of here at #C_[40,71]#. 2nd tower NE of here at #C_[42,66]#. 3rd tower NE of here at #C_[44,63]#. Just behind this tower.", x = 47, y = 71, zone = "Western Plaguelands" },
			[13] = { str = "Go NW to #C_[37,56]# to Felstone field, kill Cauldron Lord Bilemaw for his cauldron key. Then go right click the cauldron and turn in #Q_'Target: Felstone Field'# accept #Q_'Return to Chillwind Camp'#.", x = 37, y = 56, zone = "Western Plaguelands" },
			[14] = { str = "Theres 2 houses on the NE side of the field at #C_[38,54]#, enter the northern house and go upstairs. Accept #Q_'Better Late Than Never'#.", x = 38, y = 54, zone = "Western Plaguelands" },
			[15] = { str = "Go in the barn next door and grab the box on the floor and turn in #Q_'Better Late Than Never'# accept #Q_'Better Late Than Never'#(2)." },
			[16] = { str = "Run back to Chillwind Camp at #C_[42,84]# and turn in #Q_'All Along the Watchtowers'#, accept #Q_'Scholomance'# SKIP the other unless you get about 10-20 people.", x = 42, y = 84, zone = "Western Plaguelands" },
			[17] = { str = "Turn in #Q_'Scholomance'# just behind him, accept #Q_'Skeletal Fragments'# Bones for this will take a while and drop off any skeletons." },
			[18] = { str = "Near the flight path turn in #Q_'Return to Chillwind Camp'# accept #Q_'Target: Dalson's Tears'#." },
			[19] = { str = "Go up to #C_[46,52]# to Dalson’Tears, kill Cauldron Lord Malvinious for his cauldron key. Then go right click the cauldron and turn in #Q_'Target: Dalson's Tears'# accept #Q_'Return to Chillwind Camp'#.", x = 46, y = 52, zone = "Western Plaguelands" },
			[20] = { str = "Enter the barn here at #C_[47,50]# and Touch the diary on the floor and complete it, another quest that isn’t a quest.", x = 47, y = 50, zone = "Western Plaguelands" },

			[21] = { str = "Go behind the barn and look for a Wandering Skeleton and get Dalson Outhouse Key off of him. Use this to open the outhouse back here and kill Farmer Dalson and get his Dalson Cabinet Key. Use the key on the locked cabinet upsairs in the house now at #C_[47,49]# next to the barn and complete the quest #Q_'Locked Away'#.", x = 47, y = 49, zone = "Western Plaguelands" },
			[22] = { str = "Go back to Chillwind Camp at #C_[42,84]# and turn in #Q_'Return to Chillwind Camp'# accept #Q_'Target: Writhing Haunt'#.", x = 42, y = 84, zone = "Western Plaguelands" },
			[23] = { str = "Use your #I_[Hearthstone]# to return to #A_Ironforge# then fly to #A_Stormwind#." },
			[24] = { str = "Go to the building at #C_[48,30]# on the 2nd floor of the cathedral area and turn in #Q_'Better Late Than Never'#(2) accept #Q_'Good Natured Emma'#.", x = 48, y = 30, zone = "Stormwind" },
			[25] = { str = "Emma travels between the cathedral and the trade district, find her and turn in #Q_'Good Natured Emma'# accept #Q_'Good Luck Charm'#." },
			[26] = { str = "Go into the keep at #C_[78,17]# and accept #Q_'The First and the Last'#.", x = 78, y = 17, zone = "Stormwind" },
			[27] = { str = "Go to #C_[75,79]# and turn in #Q_'The First and the Last'# accept #Q_'Honor the Dead'# then turn it right back in, accept #Q_'Flint Shadowmore'#.", x = 75, y = 79, zone = "Stormwind" },
			[28] = { str = "Fly back to WPL." },
			[29] = { str = "In front of the house turn in #Q_'Flint Shadowmore'# accept #Q_'The Eastern Plagues'#." },
			[30] = { str = "Go back to Felstone field to the house upstairs at #C_[38,54]# and turn in #Q_'Good Luck Charm'# accept #Q_'Two Halves Become One'# Go outside and look for a jabbering ghoul. You can’t miss him he carry’s a pitchfork. Keep clearing in front of the house until you find him. This will give you a good time to get those #Q_'Skeletal Fragments'#.", x = 38, y = 54, zone = "Western Plaguelands" },

			[31] = { str = "Combine the halves and go back upstairs and turn in #Q_'Two Halves Become One'#." },
			[32] = { str = "Go SE to #C_[53,65]# to Writhing Haunt, kill Cauldron Lord Razarch for his cauldron key. Then go right click the cauldron and turn in #Q_'Target: Writhing Haunt'# accept #Q_'Return to Chillwind Camp'#.", x = 53, y = 65, zone = "Western Plaguelands" },
			[33] = { str = "In the house at #C_[54,65]# accept #Q_'The Wildlife Suffers Too'# now go north of the haunt and kill the diseased wolves. Don’t go any farther east to find these just go North, maybe NW some.", x = 54, y = 65, zone = "Western Plaguelands" },
			[34] = { str = "Go back to #C_[54,65]# and turn in #Q_'The Wildlife Suffers Too'# accept #Q_'The Wildlife Suffers Too'#(2).", x = 54, y = 65, zone = "Western Plaguelands" },
			[35] = { str = "Go back to Chillwind Camp at #C_[42,84]# anc turn in #Q_'Return to Chillwind Camp'# accept #Q_'Target: Gahrron's Withering'#.", x = 42, y = 84, zone = "Western Plaguelands" },
			[36] = { str = "Go just north of the Writhing Haunt between the mountains on the map at, #C_[52,56]# and kill diseased grizzleys on your way down to #C_[62,58]# for #Q_'The Wildlife Suffers Too'#(2).", x = 52, y = 56, zone = "Western Plaguelands" },
			[37] = { str = "Go NE to #C_[62,58]# to Gahrron’s Withering, kill Cauldron Lord Soulwrath for his cauldron key. Then go right click the cauldron and turn in #Q_'Target: Gahrron's Withering'# accept #Q_'Return to Chillwind Camp'#.", x = 62, y = 58, zone = "Western Plaguelands" },
			[38] = { str = "Go back to #C_[54,65]# and turn in #Q_'The Wildlife Suffers Too'#(2) accept #Q_'Glyphed Oaken Branch'#.", x = 54, y = 65, zone = "Western Plaguelands" },
			[39] = { str = "If you haven’t finished #Q_'Skeletal Fragments'# yet go to the crypt at #C_[54,79]# and kill the skeletons until you have 15 fragments.", x = 54, y = 79, zone = "Western Plaguelands" },
			[40] = { str = "Go back to Chillwind Camp at #C_[42,84]# and turn in #Q_'Return to Chillwind Camp'#.", x = 42, y = 84, zone = "Western Plaguelands" },

			[41] = { str = "Turn around to the guy in front of the tent, and complete the quest #Q_'Mission Accomplished!'# no link for it cuz it’s not a quest again lol. Now see that running back and forth seemed out of the way but there was a huge xp boost at the end, and nice xp throughout." },
			[42] = { str = "To your right turn in #Q_'Skeletal Fragments'# SKIP the next part unless you want to start on your scholo key." },
			[43] = { str = "Run east to #C_[70,50]# and enter #A_Eastern Plaguelands#.", x = 70, y = 50, zone = "Western Plaguelands" },
		}
	},

-----------57-58 Eastern Plaguelands
	[5758] = {
		title = "57-58 Eastern Plaguelands",
		items = {
			[1] = { str = "57-58 Eastern Plaguelands" },
			[2] = { str = "Run up the west coast to #C_[67,4]# and accept the 3 quests #Q_'Demon Dogs'# #Q_'Blood Tinged Skies'# and #Q_'Carrion Grubbage'#.", x = 67, y = 4, zone = "Eastern Plaguelands" },
			[3] = { str = "These are annoying quests that can take a while. Anytime from now until these are done, kill any plaguehound runts, carrion worms, or plaguebats." },
			[4] = { str = "From here on down to the bigger area, kill any dogs, worms, and bats. Focus on them while you head to the next step." },
			[5] = { str = "Keep killing the dogs and bats and head over to the skeleton at #C_[28,74]# open it and grab the insignia for #Q_'The Eastern Plagues'# then run up a bit further to the next skeleton at #C_[27,74]# and grab the insignia, it’s practically right in front of him and you will also get the blightcaller found complete message. Now go down near the road to #C_[28,79]# and loot the last insignia off the skeleton.", x = 28, y = 74, zone = "Eastern Plaguelands" },
			[6] = { str = "Focus on the dogs and bats while you head to Darrowshire at #C_[36,90]# in the broken down house. Turn in #Q_'Sister Pamela'# accept #Q_'Pamela's Doll'# then head towards the houses here, in any of the houses can be any of the 3 doll parts. They are random. Ghosts spawn when you get near the parts so be aware. Once you have all 3 parts combine them and go back to #C_[36,90]# and turn in #Q_'Pamela's Doll'# accept #Q_'Auntie Marlene'# and #Q_'Uncle Carlin'#.", x = 36, y = 90, zone = "Eastern Plaguelands" },
			[7] = { str = "Look on your map at #C_[48,76]# This lines up with that middle ridge mountain. Don’t go past this spot east until you have your plaguehound runt kills for #Q_'Demon Dogs'# and plaguebats for #Q_'Blood Tinged Skies'# because there is none past that point.", x = 48, y = 76, zone = "Eastern Plaguelands" },
			[8] = { str = "Don’t forget to kill the grubs along the way too for #Q_'Carrion Grubbage'#, they’re not as important because they’re all over." },
			[9] = { str = "Kill Plaguehounds for #Q_'Demon Dogs'# all around #C_[56,57]# this is north of the scar and south of blackwood lake. Don’t forget the grubs.", x = 56, y = 57, zone = "Eastern Plaguelands" },
			[10] = { str = "Kill Frenzied Plaguehounds for #Q_'Demon Dogs'# all around #C_[61,41]# this is north of blackwood lake but now west of it.", x = 61, y = 41, zone = "Eastern Plaguelands" },

			[11] = { str = "Head to #A_Lights Hope Chapel# (#A_Eastern Plaguelands#) at #C_[81,58]# if you still need grub meat for #Q_'Carrion Grubbage'#, then kill them as you go.", x = 81, y = 58, zone = "Eastern Plaguelands" },
			[12] = { str = "Unlock the flight path by talking to the #N_Flight Master#." },
			[13] = { str = "Turn in #Q_'Uncle Carlin'# accept #Q_'Defenders of Darrowshire'#." },
			[14] = { str = "Turn around and turn in #Q_'Duke Nicholas Zverenhoff'#." },
			[15] = { str = "Run SW to #C_[79,63]# and accept #Q_'Zaeldarr the Outcast'#.", x = 79, y = 63, zone = "Eastern Plaguelands" },
			[16] = { str = "Fly back to EPL." },
			[17] = { str = "In front of the house turn in #Q_'The Eastern Plagues'# accept #Q_'The Blightcaller Cometh'#." },
			[18] = { str = "If you’re within 6600 XP to level then Use your #I_[Hearthstone]# to return to #A_Ironforge# and fly to #A_Stormwind#, if not then grind until you’re within range." },
			[19] = { str = "Go to #C_[78,18]# in the keep and turn in #Q_'The Blightcaller Cometh'# now I SKIP the next part but it’s a good quest to do at 60.", x = 78, y = 18, zone = "Eastern Plaguelands" },
			[18] = { str = "Talk to your #N_Class Trainer# to learn new spells and abilities." },
			[19] = { str = "Fly back to #A_Chillwind Point# (#A_Western Plaguelands#)." },
		}
	},

-----------58-58 Western Plaguelands
	[5857] = {
		title = "58-58 Western Plaguelands",
		items = {
			[1] = { str = "58-58 Western Plaguelands" },
			[2] = { str = "Go NE to the house at #C_[49,78]# and go upstairs. Turn in #Q_'Pamela's Doll'# accept #Q_'A Strange Historian'#.", x = 49, y = 78, zone = "Western Plaguelands" },
			[3] = { str = "Just north of the house at #C_[49,76]# you’ll see an off color gravestone. Loot it and get the wedding ring for #Q_'A Strange Historian'#.", x = 49, y = 76, zone = "Western Plaguelands" },
			[4] = { str = "Go in the west entrance to Andorhal at #C_[39,71]# and you should see the only full building, looks like an Inn at #C_[39,68]#. Go upstairs and turn in #Q_'A Strange Historian'# accept #Q_'The Annals of Darrowshire'# also accept #Q_'A Matter of Time'#.", x = 39, y = 68, zone = "Western Plaguelands" },
			[5] = { str = "Now look all around the city here for busted up silo’s with a blue light coming out of them. Use the silo horn to summon the worms, it spawns 1-3 mobs for #Q_'A Matter of Time'#. Once you kill the last one they have a tendency to spawn another. They’re more on the East side of town." },
			[6] = { str = "Go to the Town Hall near all the mobs in the middle of town, you can sneak in from the SW side. Grab the books on the floor until you get the #Q_'The Annals of Darrowshire'# Some will spawn mobs." },
			[7] = { str = "Go back to the Inn at #C_[39,68]# and to the top floor, turn in #Q_'A Matter of Time'# accept #Q_'Counting Out Time'# also turn in #Q_'The Annals of Darrowshire'# accept #Q_'Brother Carlin'#.", x = 39, y = 68, zone = "Western Plaguelands" },
			[8] = { str = "Go outside and look around the busted houses for little metal lunchboxes for #Q_'Counting Out Time'#." },
			[9] = { str = "Go back to the Inn at #C_[39,68]# and turn in #Q_'Counting Out Time'# you can now repeat this quest for a dampener. This is used vs the 61 elite.", x = 39, y = 68, zone = "Western Plaguelands" },
		}
	},

-----------58-58 Eastern Plaguelands
	[5858] = {
		title = "58-58 Eastern Plaguelands",
		items = {
			[1] = { str = "58-58 Eastern Plaguelands" },
			[2] = { str = "Run out of here and into #A_Eastern Plaguelands# up to the NW at #C_[7,43]# and turn in the 3 quests #Q_'Demon Dogs'# #Q_'Blood Tinged Skies'# and #Q_'Carrion Grubbage'# accept #Q_'Redemption'# then listen to him and turn it back in. Then accept #Q_'Of Forgotten Memories'#.", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[3] = { str = "Go to the Undercroft at #C_[28,86]# and run behind it. Touch the dirt pile to summon Mercutio and 3 guards. Easiest way to do this is to kite him away from his buddies or get a group. Loot his body for the hammer for #Q_'Of Forgotten Memories'#.", x = 28, y = 86, zone = "Eastern Plaguelands" },
			[4] = { str = "Now go to the bottom of the crypt and kill the very big troll for #Q_'Zaeldarr the Outcast'# Only grab the scroll on the floor if u want." },
			[5] = { str = "Go back to #C_[7,43]# and turn in #Q_'Of Forgotten Memories'# accept #Q_'Of Lost Honor'#.", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[6] = { str = "Either Run to Light’s Hope Chapel or back to Chillwind and fly there." },
			[7] = { str = "Turn in #Q_'Brother Carlin'# accept #Q_'Villains of Darrowshire'#." },
			[8] = { str = "Go down to #C_[79,63]# and turn in #Q_'Zaeldarr the Outcast'#.", x = 79, y = 63, zone = "Eastern Plaguelands" },
			[9] = { str = "Go down just North of Corin’s Crossing to #C_[53,65]# and grab the sword for #Q_'Villains of Darrowshire'# It’s down in the scar. Don’t forget to do some of #Q_'Defenders of Darrowshire'# at Corin’s Just get what you can.", x = 53, y = 65, zone = "Eastern Plaguelands" },
			[10] = { str = "Go north to Blackwood Lake at #C_[51,49]# and grab the skull under the water for #Q_'Villains of Darrowshire'#.", x = 51, y = 49, zone = "Eastern Plaguelands" },

			[11] = { str = "Go NE to around #C_[65,41]# and kill the zombies for part of #Q_'Defenders of Darrowshire'# there are quite a lot here you could probably finish.", x = 65, y = 41, zone = "Eastern Plaguelands" },
			[12] = { str = "Go to the lake at #C_[71,33]# and grab the flag next to the cage, it’s hard to see and is laying flat for #Q_'Of Lost Honor'#.", x = 71, y = 33, zone = "Eastern Plaguelands" },
			[13] = { str = "Go NW to the tower at #C_[56,24]# and turn in #Q_'Troubled Spirits of Kel'Theril# SKIP the next part.", x = 56, y = 24, zone = "Eastern Plaguelands" },
			[14] = { str = "Run West to #C_[45,34]# and loot the termite mounds here for #Q_'A Plague Upon Thee'# until you get 100 termites, also kill ghouls to finish up #Q_'Defenders of Darrowshire'#.", x = 45, y = 34, zone = "Eastern Plaguelands" },
			[15] = { str = "Run to #A_Lights Hope Chapel# (#A_Eastern Plaguelands#) now." },
			[16] = { str = "Go by the tent and turn in #Q_'Defenders of Darrowshire'# and #Q_'Villains of Darrowshire'#." },
			[17] = { str = "Fly to #A_Chillwind Point# (#A_Western Plaguelands#)." },
			[18] = { str = "Next to the house turn in #Q_'A Plague Upon Thee'#. Accept #Q_'A Plague Upon Thee'#(2)." },
		}
	},

------------58-59 Western Plaguelands
	[5859] = {
		title = "58-59 Western Plaguelands",
		items = {
			[1] = { str = "58-59 Western Plaguelands" },
			[2] = { str = "Run up to #C_[51,28]# and accept #Q_'Unfinished Business'#.", x = 52, y = 30, zone = "Western Plaguelands" },
			[3] = { str = "Start heading back SW around #C_[47,32]# and clear your way into the mill. Right click the box and place the termintes, then click the barrel and turn in #Q_'A Plague Upon Thee'#(2). Accept #Q_'A Plague Upon Thee'#(3).", x = 47, y = 32, zone = "Western Plaguelands" },
			[4] = { str = "Go just south of #C_[49,42]# and kill 2 knights and mages for #Q_'Unfinished Business'#then #C_[51,43]# for the hunters and medics.", x = 49, y = 42, zone = "Western Plaguelands" },
			[5] = { str = "Go to #C_[51,28]# and turn in #Q_'Unfinished Business'#. Accept #Q_'Unfinished Business'#(2).", x = 51, y = 28, zone = "Western Plaguelands" },
			[6] = { str = "Go to #C_[57,36]# and kill Huntsman Radly for #Q_'Unfinished Business'#(2) then north to the tower at #C_[55,23]# and kill Cavalier Durgen at the top.", x = 57, y = 36, zone = "Western Plaguelands" },
			[7] = { str = "Go straight out of the tower over the mountains to #C_[51,28]# and turn in #Q_'Unfinished Business'#(2) doing the 3rd part #Q_'Unfinished Business'#(3) is optional. Some classes can do it easier than others. You have to run north to hearthglen and run up into the big tower in the center of town at #C_[45,18]# and look over the edge until it says complete.", x = 45, y = 18, zone = "Western Plaguelands" },
			[8] = { str = "Run back straight south over the mountains to #C_[51,28]# and turn in #Q_'Unfinished Business'#(3).", x = 51, y = 28, zone = "Western Plaguelands" },
			[9] = { str = "Run into EPL and up to #C_[7,43]# and turn in #Q_'Of Lost Honor'# accept #Q_'Of Love and Family'#.", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[10] = { str = "Go back to WPL and run/swim to the island Scholo is on at #C_[65,75]# and turn in #Q_'Of Love and Family'# SKIP the rest until you do strat.", x = 65, y = 75, zone = "Western Plaguelands" },

			[11] = { str = "Go back to Chillwind Camp at #C_[43,84]# and turn in #Q_'A Plague Upon Thee'#(3).", x = 43, y = 84, zone = "Western Plaguelands" },
			[12] = { str = "Now you want to do 2 things here. Get friendly with Argent Dawn and get 8-8.5k from leveling. You can do #Q_'Alas, Andorhal'# if you can find a group, it’s not that hard but can take 5-10 people. This will give you an easy 8300 xp instead of grinding." },
			[13] = { str = "Now you want to go up to andorhal and just grind until you’re friendly, once you’re friendly go back to Chillwind Camp and turn in all your scourge tokens. This allows you to buy mana biscuits which restore mana and health and more than food can. If you still need to level then go grind on mobs in andorhal again until you’re 8-8.5k from 59." },
			[14] = { str = "Once you’re 8k-8.5k from leveling, fly to Hinterlands and run all the way NE to the waterfall at #C_[80,46]# and jump off. Under the water loot the chest and finish #Q_'Cortello’s Riddle'#(3) I bet you thought I forgot about it.", x = 80, y = 46, zone = "The Hinterlands" },
			[15] = { str = "Use your #I_[Hearthstone]# to return to #A_Ironforge#." },
			[16] = { str = "Go to the throne room at #C_[43,52]# and accept #Q_'An Earnest Proposition'# (pick your class from the list) You have to have your classes tier 0 bracers in order to do this quest. You can buy it on AH.", x = 43, y = 52, zone = "Ironforge" },
			[17] = { str = "Fly to #A_Menethil Harbor# (#A_The Wetlands#) and boat to #A_Auberdine# (#A_Darkshore#), fly to #A_Darnassus#." },
			[18] = { str = "Go to #C_[35,8]# on the 2nd floor and turn in #Q_'Glyphed Oaken Branch'#.", x = 35, y = 8, zone = "Darnassus" },
			[19] = { str = "You should be 59, fly to #A_Everlook# (#A_Winterspring#)." },
		}
	},

------------59-60 Winterspring
	[5960] = {
		title = "59-60 Winterspring",
		items = {
			[1] = { str = "59-60 Winterspring" },
			[2] = { str = "On your left after entering turn in #Q_'Are We There, Yeti?'#(3)." },
			[3] = { str = "Near the back are 2 horde, accept #Q_'Luck Be With You'#." },
			[4] = { str = "Turn around and turn in #Q_'Felnok Steelspring'# accept #Q_'Chillwind Horns'#." },
			[5] = { str = "Do #Q_'An Earnest Proposition'# just kill the sabers until you have 15 blood." },
			[6] = { str = "Go just SE of here around #C_[55,18]# and kill the chimera’s for #Q_'Chillwind Horns'#.", x = 55, y = 18, zone = "Winterspring" },
			[7] = { str = "Run to Starfall Village at #C_[52,30]# and accept #Q_'Enraged Wildkin'# '.", x = 52, y = 30, zone = "Winterspring" },
			[8] = { str = "Turn in #Q_'Chillwind Horns'# SKIP the other unless you wanna go there." },
			[9] = { str = "Go south to #C_[59,59]# and touch the crate and turn in #Q_'Enraged Wildkin'#. Accept #Q_'Enraged Wildkin'#(2).", x = 59, y = 59, zone = "Winterspring" },
			[10] = { str = "Go back to the road at #C_[61,60]# and touch the wagon, turn in #Q_'Enraged Wildkin'#(2). Accept #Q_'Enraged Wildkin'#(3) grab the box in the snow.", x = 61, y = 60, zone = "Winterspring" },

			[11] = { str = "Run east again to #C_[63,59]# and turn in #Q_'Find Ranshalla'# accept #Q_'Guardians of the Altar'#.", x = 63, y = 59, zone = "Winterspring" },
			[12] = { str = "Now protect her while she does her thing. Make sure you get the feather off an owl for #Q_'Enraged Wildkin'#(3) When she stops in a cave, light the torch for her. If you don’t get the feather before you’re done keep killing until you got it." },
			[13] = { str = "Go south to #C_[62,69]# and loot the gems for #Q_'Luck Be With You'# hunters and locks can use pet to distract mobs while u loot, other classes will have to group.", x = 62, y = 69, zone = "Winterspring" },
			[14] = { str = "Use your #I_[Hearthstone]# to return to #A_Everlook# (#A_Winterspring#)." },
			[15] = { str = "Turn in #Q_'Luck Be With You'# at the 2 horde near the back of #A_Everlook# (#A_Winterspring#)." },
			[16] = { str = "You should be about 25% into 59 now." },
			[17] = { str = "Accept #Q_''Cache of Mau'Ari''# if you want to. This just gives you an item which allows the mobs here to drop stuff which you can turn in for buffs." },
			[18] = { str = "Go up to Starfall Village at #C_[52,30]# and turn in #Q_'Enraged Wildkin'#(3).", x = 52, y = 30, zone = "Winterspring" },
			[19] = { str = "Run to #C_[31,45]# and turn in #Q_'Mystery Goo'# accept #Q_'Toxic Horrors'#.", x = 31, y = 45, zone = "Winterspring" },
			[20] = { str = "Run into Felwood and go to #C_[48,24]# and kill toxic horrors for #Q_'Toxic Horrors'# these also drop essence of waters.", x = 48, y = 24, zone = "Felwood" },

			[21] = { str = "Fly to Rut’theran Village and go to the house at #C_[55,92]# and turn in #Q_'Guardians of the Altar'# accept #Q_'Wildkin of Elune'#.", x = 55, y = 92, zone = "Teldrassil" },
			[22] = { str = "Go in #A_Darnassus# and up to the top of the tower at #C_[34,8]# and turn in #Q_'Wildkin of Elune'#.", x = 34, y = 8, zone = "Darnassus" },
			[23] = { str = "Fly back to Felwood." },
			[24] = { str = "Run back up into Winterspring and over to #C_[31,45]# turn in #Q_'Toxic Horrors'# accept #Q_'Winterfall Runners'#.", x = 31, y = 45, zone = "Winterspring" },
			[25] = { str = "Now to find the runners. They travel anywhere from the Timbermaw Cave east to #C_[53,34]# then up around the mountains north of #A_Everlook# (#A_Winterspring#) over to Winterfall Village. If you didn’t see them from the cave to here, head east. You don’t have to kill all 3.", x = 53, y = 34, zone = "Winterspring" },
			[26] = { str = "Once you get the crate run back to #C_[31,45]# Turn in Winterfall Runners an ambush will come from the lake, if u don’t move from the tent they won’t aggro you. SKIP the next part unless you get a group.", x = 31, y = 45, zone = "Winterspring" },
			[27] = { str = "Use your #I_[Hearthstone]# to return to #A_Everlook# (#A_Winterspring#)." },
			[28] = { str = "You should be 45-50% through 59. Now I make sure I got my mana bisquits and I start grinding until im 6600 to 60. Anywhere is fine where there is a lot of mobs It’s all a matter of preference. I choose the owl wing thicket at #C_[64,62]# or anything north of #A_Everlook# (#A_Winterspring#). I like to kill the furlbogs for timbermaw rep also.", x = 64, y = 62, zone = "Winterspring" },
			[29] = { str = "If you don’t want to grind this large amount then do BRD, scholo, or strat. You have a lot of quests in those spots to do." },
			[30] = { str = "Once you’re 6600 to 60 go to #A_Ironforge# and turn in #Q_'An Earnest Proposition'#." },

			[31] = { str = "Grats on 60.fuck the police." },
		}
	},
}
